/**
 * aiot.js — aiot page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 10
 *
 * Usage: node complete_website/divi5/build-page.js --page aiot [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/aiot-hero');
const sectionBuilder = require('./sections/aiot-section');
const problemBuilder = require('./sections/aiot-problem');
const dataflowBuilder = require('./sections/aiot-dataflow');
const capabilitiesBuilder = require('./sections/aiot-capabilities');
const metricsBuilder = require('./sections/aiot-metrics');
const protocolBuilder = require('./sections/aiot-protocol');
const integrationBuilder = require('./sections/aiot-integration');
const section2Builder = require('./sections/aiot-section-2');
const ctaBuilder = require('./sections/aiot-cta');
const relatedBuilder = require('./sections/aiot-related-solutions');

module.exports = {
  pageId: 100564, // TODO: Create WP page and set page ID
  title: 'AIoT — Smart Factory Intelligence — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Aiot_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'products/aiot.html'),
  protoFile: 'products/aiot.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'problem', builder: problemBuilder },
    { name: 'dataflow', builder: dataflowBuilder },
    { name: 'capabilities', builder: capabilitiesBuilder },
    { name: 'metrics', builder: metricsBuilder },
    { name: 'protocol', builder: protocolBuilder },
    { name: 'integration', builder: integrationBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'cta', builder: ctaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100564', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.aiot-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.aiot-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_1', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'problem', wpSelector: '.et_pb_section_2', htmlSelector: '.problem-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.problem-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'dataflow', wpSelector: '.et_pb_section_3', htmlSelector: '.dataflow-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dataflow-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'capabilities', wpSelector: '.et_pb_section_4', htmlSelector: '.capabilities-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.capabilities-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'metrics', wpSelector: '.et_pb_section_5', htmlSelector: '.metrics-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.metrics-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'protocol', wpSelector: '.et_pb_section_6', htmlSelector: '.protocol-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.protocol-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'integration', wpSelector: '.et_pb_section_7', htmlSelector: '.integration-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.integration-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_8', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'cta', wpSelector: '.et_pb_section_9', htmlSelector: '.cta-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.cta-section h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_10', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_10 h2' },
        ],
      },
    ],
  },
};
