/**
 * automotive.js — automotive page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 9
 *
 * Usage: node complete_website/divi5/build-page.js --page automotive [--dry-run]
 */

const path = require('path');

// Section builders
const autoHeroBuilder = require('./sections/automotive-auto-hero');
const contextBuilder = require('./sections/automotive-context');
const stakesBuilder = require('./sections/automotive-stakes');
const solutionsBuilder = require('./sections/automotive-solutions');
const productsBuilder = require('./sections/automotive-products');
const sectionBuilder = require('./sections/automotive-section');
const section2Builder = require('./sections/automotive-section-2');
const section3Builder = require('./sections/automotive-section-3');
const ctaBuilder = require('./sections/automotive-cta');
const relatedBuilder = require('./sections/automotive-related-solutions');

module.exports = {
  pageId: 100565, // TODO: Create WP page and set page ID
  title: 'Automotive Manufacturing Solutions — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Automotive_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'industries/automotive.html'),
  protoFile: 'industries/automotive.html',

  sections: [
    { name: 'auto-hero', builder: autoHeroBuilder },
    { name: 'context', builder: contextBuilder },
    { name: 'stakes', builder: stakesBuilder },
    { name: 'solutions', builder: solutionsBuilder },
    { name: 'products', builder: productsBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'section-3', builder: section3Builder },
    { name: 'cta', builder: ctaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100565', // TODO: Set page ID
    sections: [
      {
        name: 'auto-hero', wpSelector: '.et_pb_section_0', htmlSelector: '.auto-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.auto-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'context', wpSelector: '.et_pb_section_1', htmlSelector: '.context-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.context-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'stakes', wpSelector: '.et_pb_section_2', htmlSelector: '.stakes-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.stakes-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'solutions', wpSelector: '.et_pb_section_3', htmlSelector: '.solutions-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.solutions-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'products', wpSelector: '.et_pb_section_4', htmlSelector: '.products-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.products-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_5', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_6', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'section-3', wpSelector: '.et_pb_section_7', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'cta', wpSelector: '.et_pb_section_8', htmlSelector: '.cta-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.cta-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_9', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
    ],
  },
};
