/**
 * automotive.js — automotive page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 9
 *
 * Usage: node complete_website/divi5/build-page.js --page automotive [--dry-run]
 */

const path = require('path');

// Section builders
const autoHeroBuilder = require('./sections/automotive-auto-hero');
const contextBuilder = require('./sections/automotive-context');
const stakesBuilder = require('./sections/automotive-stakes');
const solutionsBuilder = require('./sections/automotive-solutions');
const productsBuilder = require('./sections/automotive-products');
const sectionBuilder = require('./sections/automotive-section');
const section2Builder = require('./sections/automotive-section-2');
const section3Builder = require('./sections/automotive-section-3');
const ctaBuilder = require('./sections/automotive-cta');
const relatedBuilder = require('./sections/automotive-related-solutions');
const schema = require('../lib/schema');

module.exports = {
  pageId: 100565, // TODO: Create WP page and set page ID
  title: 'Automotive Manufacturing Solutions — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Automotive_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'industries/automotive.html'),
  protoFile: 'industries/automotive.html',

  sections: [
    { name: 'auto-hero', builder: autoHeroBuilder },
    { name: 'context', builder: contextBuilder },
    { name: 'stakes', builder: stakesBuilder },
    { name: 'solutions', builder: solutionsBuilder },
    { name: 'products', builder: productsBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'section-3', builder: section3Builder },
    { name: 'cta', builder: ctaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],


  schema() {
    return [
      schema.breadcrumbList([
        { name: 'Home', url: '/' },
        { name: 'Industries', url: '/industries/' },
        { name: 'Automotive Parts', url: '/industries/automotive/' },
      ]),
      schema.webPage({
        name: 'Automotive Parts Manufacturing Solutions',
        description: 'ERP and MES solutions for automotive parts manufacturers in Thailand. JIT scheduling, EDI integration, IATF 16949 compliance.',
        url: '/industries/automotive/',
      }),
      schema.faqPage([
        { question: 'What ERP system do automotive parts factories in Thailand use?', answer: 'DigiWin is the ERP of choice for over 500 automotive tier 1-3 suppliers across Thailand and ASEAN. Our system is purpose-built for the automotive supply chain, with native support for JIT scheduling, OEM EDI integration, and IATF 16949 quality compliance. Unlike generic ERP platforms, DigiWin understands kanban signals, sequence delivery, and the multi-plant coordination that automotive production demands.' },
        { question: 'Does DigiWin ERP support EDI for automotive supply chains?', answer: 'Yes. DigiWin ERP supports EDI integration for automotive supply chains, enabling electronic exchange of forecasts, purchase orders, ASN confirmations, and quality data with your OEM customers. This reduces manual data entry and helps maintain the tight JIT delivery windows that automotive production demands.' },
        { question: 'Does DigiWin support IATF 16949 quality documentation?', answer: 'Yes. DigiWin includes built-in quality management modules designed for IATF 16949 compliance. The system supports PPAP documentation, control plans, inspection records, SPC charts and analysis, and 8D reporting. All quality data is captured digitally and is audit-ready at all times, eliminating the documentation anxiety that comes with quarterly customer audits and growing compliance requirements.' },
        { question: 'How does DigiWin help with automotive lot traceability?', answer: 'DigiWin delivers 100% traceability coverage from raw material receiving through finished goods shipping. The system supports both forward and backward lot-level traceability with barcode and QR code scanning at every step. When a quality issue surfaces and an OEM asks which lot, which raw materials, and which operator were involved, DigiWin provides the answer in seconds rather than days, along with precise recall scope analysis.' },
        { question: 'What is the typical ROI timeline for automotive ERP?', answer: 'DigiWin customers in the automotive sector typically see measurable results within the first year of implementation. Key outcomes include on-time delivery rates reaching 99.5%, which directly protects OEM contracts and prevents costly line-stop penalties. With JIT scheduling, complete traceability, and automated EDI integration working together, the ROI is driven by both cost avoidance and operational efficiency gains across multi-plant operations.' },
      ]),
    ];
  },

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100565', // TODO: Set page ID
    sections: [
      {
        name: 'auto-hero', wpSelector: '.et_pb_section_0', htmlSelector: '.auto-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.auto-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'context', wpSelector: '.et_pb_section_1', htmlSelector: '.context-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.context-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'stakes', wpSelector: '.et_pb_section_2', htmlSelector: '.stakes-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.stakes-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'solutions', wpSelector: '.et_pb_section_3', htmlSelector: '.solutions-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.solutions-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'products', wpSelector: '.et_pb_section_4', htmlSelector: '.products-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.products-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_5', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_6', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'section-3', wpSelector: '.et_pb_section_7', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'cta', wpSelector: '.et_pb_section_8', htmlSelector: '.cta-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.cta-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_9', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
    ],
  },
};
