/**
 * blog.js — blog page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 5
 *
 * Usage: node complete_website/divi5/build-page.js --page blog [--dry-run]
 */

const path = require('path');

// Section builders
const hubHeroBuilder = require('./sections/blog-hub-hero');
const hubFeaturedBuilder = require('./sections/blog-hub-featured');
const articlesBuilder = require('./sections/blog-articles');
const libraryBuilder = require('./sections/blog-library');
const hubCtaBuilder = require('./sections/blog-hub-cta');

module.exports = {
  pageId: 100570,
  title: 'Blog',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Blog_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'blog.html'),
  protoFile: 'blog.html',

  sections: [
    { name: 'hub-hero', builder: hubHeroBuilder },
    { name: 'hub-featured', builder: hubFeaturedBuilder },
    { name: 'articles', builder: articlesBuilder },
    { name: 'library', builder: libraryBuilder },
    { name: 'hub-cta', builder: hubCtaBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 12,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100570',
    sections: [
      {
        name: 'hub-hero', wpSelector: '.hubh-hero-inner', htmlSelector: '.blog-hub-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Stat Number', htmlSel: '.blog-hub-hero [data-target]', wpSel: '.hubh-hero-inner [data-target]' },
        ],
      },
      {
        name: 'hub-featured', wpSelector: '.hubf-featured-inner', htmlSelector: '.blog-hub-featured-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.blog-hub-featured-section h2', wpSel: '.hubf-featured-inner h2' },
        ],
      },
      {
        name: 'articles', wpSelector: '.articles-inner', htmlSelector: '.articles-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.articles-section h2', wpSel: '.articles-inner h2' },
        ],
      },
      {
        name: 'library', wpSelector: '.lib-inner', htmlSelector: '.library-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.library-section h2', wpSel: '.lib-inner h2' },
        ],
      },
      {
        name: 'hub-cta', wpSelector: '.hubc-cta-inner', htmlSelector: '.blog-hub-cta',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.blog-hub-cta h2', wpSel: '.hubc-cta-inner h2' },
        ],
      },
    ],
  },
};
