/**
 * electronics.js — electronics page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 9
 *
 * Usage: node complete_website/divi5/build-page.js --page electronics [--dry-run]
 */

const path = require('path');

// Section builders
const elecHeroBuilder = require('./sections/electronics-elec-hero');
const contextBuilder = require('./sections/electronics-context');
const challengesBuilder = require('./sections/electronics-challenges');
const solutionsBuilder = require('./sections/electronics-solutions');
const equipmentBuilder = require('./sections/electronics-equipment');
const fadeInBuilder = require('./sections/electronics-fade-in');
const productsBuilder = require('./sections/electronics-products');
const sectionBuilder = require('./sections/electronics-section');
const ctaBuilder = require('./sections/electronics-cta');
const relatedBuilder = require('./sections/electronics-related-solutions');
const schema = require('../lib/schema');

module.exports = {
  pageId: 100566, // TODO: Create WP page and set page ID
  title: 'Electronics Manufacturing Solutions — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Electronics_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'industries/electronics.html'),
  protoFile: 'industries/electronics.html',

  sections: [
    { name: 'elec-hero', builder: elecHeroBuilder },
    { name: 'context', builder: contextBuilder },
    { name: 'challenges', builder: challengesBuilder },
    { name: 'solutions', builder: solutionsBuilder },
    { name: 'equipment', builder: equipmentBuilder },
    { name: 'fade-in', builder: fadeInBuilder },
    { name: 'products', builder: productsBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'cta', builder: ctaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],


  schema() {
    return [
      schema.breadcrumbList([
        { name: 'Home', url: '/' },
        { name: 'Industries', url: '/industries/' },
        { name: 'Electronics Assembly', url: '/industries/electronics/' },
      ]),
      schema.webPage({
        name: 'Electronics Assembly Manufacturing Solutions',
        description: 'MES and ERP for electronics assembly factories in Thailand. SMT integration, MSD tracking, component-level traceability.',
        url: '/industries/electronics/',
      }),
      schema.faqPage([
        { question: 'What MES system works best for electronics assembly in Thailand?', answer: 'DigiWin MES is purpose-built for the complexity of electronics assembly, with native SMT machine integration that generic MES platforms cannot match. The system handles high-mix, low-volume production with thousands of unique component types, tracking every reel to every board position. It is deployed across Thailand\'s electronics ecosystem, which exports over $40 billion in electronics annually, from hard disk drives to automotive electronics.' },
        { question: 'Can DigiWin MES integrate with Fuji and Panasonic SMT machines?', answer: 'Yes. DigiWin provides direct machine connectivity with all major SMT equipment brands including Fuji, Panasonic, Yamaha, Juki, and ASM pick-and-place machines, as well as AOI and ICT inspection systems from Koh Young, Omron, and Keysight. This integration enables reel verification at the feeder, wrong-part prevention, and automated program downloads, eliminating the manual data entry that causes costly component placement errors.' },
        { question: 'How does DigiWin handle moisture-sensitive component (MSD) tracking?', answer: 'DigiWin automates the entire floor-life management process for moisture-sensitive devices. The system starts an automatic countdown the moment an MSD package is opened and exposed to floor conditions, tracks bake-out cycles for components that need reconditioning, and sends expiry alerts that block expired components from being used on the line. This automated approach has achieved a 45% reduction in MSD-related scrap compared to manual tracking methods.' },
        { question: 'Does DigiWin support BOI compliance for electronics factories?', answer: 'Yes. DigiWin provides production-order-level material reconciliation specifically designed for BOI audits in electronics manufacturing. The system tracks actual component consumption per assembly order, which is critical for bonded electronic components that require precise import duty reconciliation. Electronics factories using DigiWin for BOI compliance have reported savings of over 10 million THB per year through accurate duty drawback claims and BOI-ready audit reports.' },
        { question: 'What pick accuracy can I achieve with DigiWin WMS?', answer: 'DigiWin sFLS WMS delivers 99.9% pick accuracy for electronics warehouse operations. The system manages reel-level inventory with precise moisture-sensitive component handling, automated kitting support for production orders, and barcode-driven verification at every step. For electronics factories managing hundreds of unique parts per product and thousands of reels in inventory, this level of accuracy prevents the costly errors where one wrong component placed can result in an entire batch being scrapped.' },
      ]),
    ];
  },

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100566', // TODO: Set page ID
    sections: [
      {
        name: 'elec-hero', wpSelector: '.et_pb_section_0', htmlSelector: '.elec-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.elec-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'context', wpSelector: '.et_pb_section_1', htmlSelector: '.context-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.context-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'challenges', wpSelector: '.et_pb_section_2', htmlSelector: '.challenges-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.challenges-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'solutions', wpSelector: '.et_pb_section_3', htmlSelector: '.solutions-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.solutions-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'equipment', wpSelector: '.et_pb_section_4', htmlSelector: '.equipment-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.equipment-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'fade-in', wpSelector: '.et_pb_section_5', htmlSelector: '.case-reference',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Case Title', htmlSel: '.case-reference h3', wpSel: '.et_pb_section_5 h3' },
        ],
      },
      {
        name: 'products', wpSelector: '.et_pb_section_6', htmlSelector: '.products-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.products-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_7', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'cta', wpSelector: '.et_pb_section_8', htmlSelector: '.cta-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.cta-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_9', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
    ],
  },
};
