/**
 * industries.js — industries page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 6
 *
 * Usage: node complete_website/divi5/build-page.js --page industries [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/industries-hero');
const contextBuilder = require('./sections/industries-context');
const sectionBuilder = require('./sections/industries-section');
const challengesBuilder = require('./sections/industries-challenges');
const approachBuilder = require('./sections/industries-approach');
const ctaBuilder = require('./sections/industries-cta');

module.exports = {
  pageId: 100557, // TODO: Create WP page and set page ID
  title: 'Industries We Serve — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Industries_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'industries.html'),
  protoFile: 'industries.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'context', builder: contextBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'challenges', builder: challengesBuilder },
    { name: 'approach', builder: approachBuilder },
    { name: 'cta', builder: ctaBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100557', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.industries-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.industries-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'context', wpSelector: '.et_pb_section_1', htmlSelector: '.context-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.context-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_2', htmlSelector: '.industries-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.industries-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'challenges', wpSelector: '.et_pb_section_3', htmlSelector: '.challenges-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.challenges-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'approach', wpSelector: '.et_pb_section_4', htmlSelector: '.approach-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.approach-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'cta', wpSelector: '.et_pb_section_5', htmlSelector: '.cta-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.cta-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
    ],
  },
};
