/**
 * mes.js — mes page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 10
 *
 * Usage: node complete_website/divi5/build-page.js --page mes [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/mes-hero');
const sectionBuilder = require('./sections/mes-section');
const beforeafterBuilder = require('./sections/mes-beforeafter');
const productsBuilder = require('./sections/mes-products');
const capabilitiesBuilder = require('./sections/mes-capabilities');
const integrationBuilder = require('./sections/mes-integration');
const resultsBuilder = require('./sections/mes-results');
const reportsBuilder = require('./sections/mes-reports');
const section2Builder = require('./sections/mes-section-2');
const productDetailCtaBuilder = require('./sections/mes-product-detail-cta');
const relatedBuilder = require('./sections/mes-related-solutions');
const schema = require('../lib/schema');

module.exports = {
  pageId: 100562, // TODO: Create WP page and set page ID
  title: 'MES — Manufacturing Execution System — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Mes_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'products/mes.html'),
  protoFile: 'products/mes.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'beforeafter', builder: beforeafterBuilder },
    { name: 'products', builder: productsBuilder },
    { name: 'capabilities', builder: capabilitiesBuilder },
    { name: 'integration', builder: integrationBuilder },
    { name: 'results', builder: resultsBuilder },
    { name: 'reports', builder: reportsBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'product-detail-cta', builder: productDetailCtaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],


  schema() {
    return [
      schema.breadcrumbList([
        { name: 'Home', url: '/' },
        { name: 'Products', url: '/products/' },
        { name: 'MES', url: '/mes/' },
      ]),
      schema.softwareApplication({
        name: 'DigiWin MES',
        subCategory: 'Manufacturing Execution System',
        description: 'Real-time shop floor visibility for Thai factories. Three tiers \u2014 MES for full production execution, SFT for lightweight tracking, AIoT Cloud for entry-level monitoring. OEE monitoring, quality data capture, and lot-level traceability.',
        url: '/mes/',
        featureList: 'OEE monitoring, Quality data capture, Lot-level traceability, Work order management, Real-time production dashboards, SPC analysis, Machine downtime tracking, Paperless shop floor',
      }),
      schema.faqPage([
        { question: 'What is a Manufacturing Execution System (MES)?', answer: 'A Manufacturing Execution System (MES) is software that tracks, monitors, and controls production on the factory floor in real time. It bridges the gap between ERP planning and actual shop floor execution \u2014 showing you what\'s happening on every machine and workstation right now, not what happened yesterday.' },
        { question: 'What is the difference between MES, SFT, and AIoT Cloud?', answer: 'MES is DigiWin\'s full-featured manufacturing execution system for comprehensive production management \u2014 work order tracking, quality control, material traceability, and OEE analytics. SFT (Shop Floor Tracking) is a mid-tier option that can be deployed in 2-4 weeks, focusing on production reporting and machine status monitoring. AIoT Cloud is the entry-level tier \u2014 cloud-based production monitoring with mobile apps and subscription pricing, ideal for factories starting their digitalization journey.' },
        { question: 'Do I need ERP before implementing MES?', answer: 'No. DigiWin MES connects to any ERP system through standard web services. Many manufacturers start with MES first to get immediate shop floor visibility, then add or upgrade ERP later. This approach lets you see ROI faster than a full ERP replacement.' },
        { question: 'What results can I expect with DigiWin MES?', answer: 'Based on implementation data across 50,000+ manufacturing clients, DigiWin MES customers report 45% reduction in production cycle time, 70% reduction in quality failures, and 26% improvement in operational efficiency. SFT users typically achieve 92% production transparency and 86% on-time delivery rate.' },
        { question: 'How does DigiWin MES connect to machines on the shop floor?', answer: 'DigiWin MES connects to shop floor equipment through DigiWin\'s AIoT platform, which supports 50+ industrial protocols including OPC-UA, Modbus, MQTT, and direct CNC/PLC connections. For machines without digital interfaces, barcode scanning and tablet-based operator input provide the data bridge.' },
      ]),
    ];
  },

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100562', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.mes-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.mes-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_1', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'beforeafter', wpSelector: '.et_pb_section_2', htmlSelector: '.beforeafter-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.beforeafter-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'products', wpSelector: '.et_pb_section_3', htmlSelector: '.products-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.products-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'capabilities', wpSelector: '.et_pb_section_4', htmlSelector: '.capabilities-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.capabilities-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'integration', wpSelector: '.et_pb_section_5', htmlSelector: '.integration-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.integration-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'results', wpSelector: '.et_pb_section_6', htmlSelector: '.results-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.results-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'reports', wpSelector: '.et_pb_section_7', htmlSelector: '.reports-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.reports-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_8', htmlSelector: '.dw-section:has(details)',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section:has(details) h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'product-detail-cta', wpSelector: '.et_pb_section_9', htmlSelector: '.product-detail-cta',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.product-detail-cta h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_10', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_10 h2' },
        ],
      },
    ],
  },
};
