/**
 * mes.js — mes page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 10
 *
 * Usage: node complete_website/divi5/build-page.js --page mes [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/mes-hero');
const sectionBuilder = require('./sections/mes-section');
const beforeafterBuilder = require('./sections/mes-beforeafter');
const productsBuilder = require('./sections/mes-products');
const capabilitiesBuilder = require('./sections/mes-capabilities');
const integrationBuilder = require('./sections/mes-integration');
const resultsBuilder = require('./sections/mes-results');
const reportsBuilder = require('./sections/mes-reports');
const section2Builder = require('./sections/mes-section-2');
const productDetailCtaBuilder = require('./sections/mes-product-detail-cta');

module.exports = {
  pageId: 100562, // TODO: Create WP page and set page ID
  title: 'MES — Manufacturing Execution System — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Mes_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'products/mes.html'),
  protoFile: 'products/mes.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'beforeafter', builder: beforeafterBuilder },
    { name: 'products', builder: productsBuilder },
    { name: 'capabilities', builder: capabilitiesBuilder },
    { name: 'integration', builder: integrationBuilder },
    { name: 'results', builder: resultsBuilder },
    { name: 'reports', builder: reportsBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'product-detail-cta', builder: productDetailCtaBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100562', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.mes-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.mes-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_1', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'beforeafter', wpSelector: '.et_pb_section_2', htmlSelector: '.beforeafter-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.beforeafter-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'products', wpSelector: '.et_pb_section_3', htmlSelector: '.products-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.products-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'capabilities', wpSelector: '.et_pb_section_4', htmlSelector: '.capabilities-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.capabilities-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'integration', wpSelector: '.et_pb_section_5', htmlSelector: '.integration-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.integration-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'results', wpSelector: '.et_pb_section_6', htmlSelector: '.results-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.results-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'reports', wpSelector: '.et_pb_section_7', htmlSelector: '.reports-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.reports-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_8', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'product-detail-cta', wpSelector: '.et_pb_section_9', htmlSelector: '.product-detail-cta',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.product-detail-cta h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
    ],
  },
};
