/**
 * news.js — news page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 6
 *
 * Usage: node complete_website/divi5/build-page.js --page news [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/news-hero');
const featuredBuilder = require('./sections/news-featured');
const upcomingBuilder = require('./sections/news-upcoming');
const seriesBuilder = require('./sections/news-series');
const pastBuilder = require('./sections/news-past');
const ctaBuilder = require('./sections/news-cta');

module.exports = {
  pageId: 100571,
  title: 'News',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_News_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'news.html'),
  protoFile: 'news.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'featured', builder: featuredBuilder },
    { name: 'upcoming', builder: upcomingBuilder },
    { name: 'series', builder: seriesBuilder },
    { name: 'past', builder: pastBuilder },
    { name: 'cta', builder: ctaBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 12,
  },

  verify: {
    wpUrl: 'http://digiwin-thailand.local/news/',
    sections: [
      {
        name: 'hero', wpSelector: '.hero-inner', htmlSelector: '.news-hero-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Hero Title', htmlSel: '.news-hero-inner h1', wpSel: '.hero-inner h1' },
          { label: 'Hero Subtitle', htmlSel: '.news-hero-subtitle', wpSel: '.hero-subtitle' },
          { label: 'Hero Badge', htmlSel: '.news-hero-badge', wpSel: '.hero-badge' },
          { label: 'Stat Value', htmlSel: '.news-hero-stat-value', wpSel: '.hero-stat-value' },
        ],
      },
      {
        name: 'featured', wpSelector: '.featured-inner', htmlSelector: '.featured-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Featured Label', htmlSel: '.featured-label', wpSel: '.featured-label' },
          { label: 'Event Title', htmlSel: '.featured-content h2', wpSel: '.featured-content h2' },
          { label: 'Event CTA', htmlSel: '.event-cta', wpSel: '.event-cta' },
        ],
      },
      {
        name: 'upcoming', wpSelector: '.upc-inner', htmlSelector: '.upcoming-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.upcoming-header h2', wpSel: '.upc-header h2' },
          { label: 'Card Title', htmlSel: '.upcoming-card h3', wpSel: '.upc-card h3' },
          { label: 'Section Label', htmlSel: '.upcoming-section .section-label', wpSel: '.upc-inner .section-label' },
        ],
      },
      {
        name: 'series', wpSelector: '.series-inner', htmlSelector: '.series-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.series-header h2', wpSel: '.series-header h2' },
          { label: 'Step Number', htmlSel: '.series-step-number', wpSel: '.series-step-number' },
          { label: 'Step Label', htmlSel: '.series-step-label', wpSel: '.series-step-label' },
        ],
      },
      {
        name: 'past', wpSelector: '.past-inner', htmlSelector: '.past-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.past-header h2', wpSel: '.past-header h2' },
          { label: 'Filter Tab', htmlSel: '.filter-tab', wpSel: '.filter-tab' },
          { label: 'Card Title', htmlSel: '.past-card h4', wpSel: '.past-card h3' },
        ],
      },
      {
        name: 'cta', wpSelector: '.news-cta-inner', htmlSelector: '.news-cta-inner',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'CTA Title', htmlSel: '.news-cta-inner h2', wpSel: '.news-cta-inner h2' },
          { label: 'Subscribe Button', htmlSel: '.cta-btn', wpSel: '.cta-btn' },
          { label: 'Secondary Link', htmlSel: '.cta-secondary-link', wpSel: '.cta-secondary-link' },
        ],
      },
    ],
  },
};
