/**
 * wms.js — wms page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 10
 *
 * Usage: node complete_website/divi5/build-page.js --page wms [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/wms-hero');
const sectionBuilder = require('./sections/wms-section');
const problemsBuilder = require('./sections/wms-problems');
const capabilitiesBuilder = require('./sections/wms-capabilities');
const mobileFunctionsBuilder = require('./sections/wms-mobile-functions');
const processFlowBuilder = require('./sections/wms-process-flow');
const transformationBuilder = require('./sections/wms-transformation');
const integrationBuilder = require('./sections/wms-integration');
const section2Builder = require('./sections/wms-section-2');
const productDetailCtaBuilder = require('./sections/wms-product-detail-cta');
const relatedBuilder = require('./sections/wms-related-solutions');

module.exports = {
  pageId: 100563, // TODO: Create WP page and set page ID
  title: 'WMS — Warehouse Management System — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Wms_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'products/wms.html'),
  protoFile: 'products/wms.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'problems', builder: problemsBuilder },
    { name: 'capabilities', builder: capabilitiesBuilder },
    { name: 'mobile-functions', builder: mobileFunctionsBuilder },
    { name: 'process-flow', builder: processFlowBuilder },
    { name: 'transformation', builder: transformationBuilder },
    { name: 'integration', builder: integrationBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'related-solutions', builder: relatedBuilder },
    { name: 'product-detail-cta', builder: productDetailCtaBuilder },
  ],

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100563', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.wms-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.wms-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_1', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'problems', wpSelector: '.et_pb_section_2', htmlSelector: '.problems-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.problems-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'capabilities', wpSelector: '.et_pb_section_3', htmlSelector: '.wms-capabilities-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.wms-capabilities-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'mobile-functions', wpSelector: '.et_pb_section_4', htmlSelector: '.mobile-functions-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.mobile-functions-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'process-flow', wpSelector: '.et_pb_section_5', htmlSelector: '.process-flow-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.process-flow-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'transformation', wpSelector: '.et_pb_section_6', htmlSelector: '.transformation-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.transformation-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'integration', wpSelector: '.et_pb_section_7', htmlSelector: '.integration-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.integration-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_8', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_9', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
      {
        name: 'product-detail-cta', wpSelector: '.et_pb_section_10', htmlSelector: '.product-detail-cta',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.product-detail-cta h2', wpSel: '.et_pb_section_10 h2' },
        ],
      },
    ],
  },
};
