/**
 * wms.js — wms page config for build-page.js
 *
 * AUTO-GENERATED by scaffold-builder.js — review before pushing.
 * Sections: 10
 *
 * Usage: node complete_website/divi5/build-page.js --page wms [--dry-run]
 */

const path = require('path');

// Section builders
const heroBuilder = require('./sections/wms-hero');
const sectionBuilder = require('./sections/wms-section');
const problemsBuilder = require('./sections/wms-problems');
const capabilitiesBuilder = require('./sections/wms-capabilities');
const mobileFunctionsBuilder = require('./sections/wms-mobile-functions');
const processFlowBuilder = require('./sections/wms-process-flow');
const transformationBuilder = require('./sections/wms-transformation');
const integrationBuilder = require('./sections/wms-integration');
const section2Builder = require('./sections/wms-section-2');
const productDetailCtaBuilder = require('./sections/wms-product-detail-cta');
const relatedBuilder = require('./sections/wms-related-solutions');
const schema = require('../lib/schema');

module.exports = {
  pageId: 100563, // TODO: Create WP page and set page ID
  title: 'WMS — Warehouse Management System — DigiWin Thailand',
  siteUrl: 'https://digiwin-thailand.local',
  specPath: path.join(__dirname, '..', '..', '..', 'docs', 'content-specs', 'ContentSpec_Wms_Divi5_2.0.md'),
  prototypePath: path.join(__dirname, '..', '..', 'products/wms.html'),
  protoFile: 'products/wms.html',

  sections: [
    { name: 'hero', builder: heroBuilder },
    { name: 'section', builder: sectionBuilder },
    { name: 'problems', builder: problemsBuilder },
    { name: 'capabilities', builder: capabilitiesBuilder },
    { name: 'mobile-functions', builder: mobileFunctionsBuilder },
    { name: 'process-flow', builder: processFlowBuilder },
    { name: 'transformation', builder: transformationBuilder },
    { name: 'integration', builder: integrationBuilder },
    { name: 'section-2', builder: section2Builder },
    { name: 'product-detail-cta', builder: productDetailCtaBuilder },
    { name: 'related-solutions', builder: relatedBuilder },
  ],


  schema() {
    return [
      schema.breadcrumbList([
        { name: 'Home', url: '/' },
        { name: 'Products', url: '/products/' },
        { name: 'WMS: sFLS', url: '/wms/' },
      ]),
      schema.softwareApplication({
        name: 'DigiWin WMS (sFLS)',
        subCategory: 'Warehouse Management System',
        description: 'Smart warehouse management for manufacturing. Barcode and RFID tracking, FIFO/FEFO automation, wave picking, and real-time inventory accuracy for Thai factories.',
        url: '/wms/',
        featureList: 'Location intelligence, Barcode & RFID tracking, FIFO/FEFO automation, Wave picking optimization, Real-time inventory accuracy, Lot & serial tracking, Putaway optimization, Cycle counting',
      }),
      schema.faqPage([
        { question: 'What is a Warehouse Management System (WMS)?', answer: 'A Warehouse Management System (WMS) is software that controls and optimizes warehouse operations \u2014 from receiving and putaway to picking, packing, and shipping. Unlike distribution-focused WMS solutions, DigiWin WMS (sFLS) is designed specifically for manufacturing warehouses, handling raw materials, WIP inventory, and finished goods with production-linked workflows.' },
        { question: 'How is DigiWin WMS different from generic WMS solutions?', answer: 'DigiWin WMS (sFLS) is built for manufacturing, not distribution. It includes production material kitting, shop floor delivery integration, WIP location tracking, and quality hold management \u2014 features that generic WMS solutions designed for e-commerce fulfillment simply don\'t offer. It also shares one database with DigiWin ERP and MES, eliminating integration complexity.' },
        { question: 'Can DigiWin WMS work with my existing ERP?', answer: 'Yes. DigiWin WMS can operate standalone or integrate with any existing ERP system via standard APIs. It works natively with DigiWin ERP (T100/iGP) through a shared database, but also connects to SAP, Oracle, and other ERP platforms for inventory synchronization and order management.' },
        { question: 'What hardware do I need for DigiWin WMS?', answer: 'DigiWin WMS works with standard Android or iOS mobile devices for barcode scanning, plus optional RFID readers for high-volume environments. You will need barcode label printers for location and item labeling. The system runs on standard server infrastructure or cloud deployment \u2014 no specialized hardware beyond mobile scanners is required.' },
        { question: 'How long does WMS implementation take?', answer: 'A typical DigiWin WMS implementation takes 2\u20134 months, depending on warehouse complexity and the number of locations. Basic implementations with core receiving, putaway, and picking can go live in as little as 6 weeks. The phased approach lets you start with high-impact areas and expand coverage over time.' },
      ]),
    ];
  },

  editabilityRules: {
    bannedBlocks: ['wp:divi/button', 'wp:divi/group'],
    maxHtmlBlocks: 15,
  },

  verify: {
    wpUrl: 'https://digiwin-thailand.local/?page_id=100563', // TODO: Set page ID
    sections: [
      {
        name: 'hero', wpSelector: '.et_pb_section_0', htmlSelector: '.wms-hero',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.wms-hero h2', wpSel: '.et_pb_section_0 h2' },
        ],
      },
      {
        name: 'section', wpSelector: '.et_pb_section_1', htmlSelector: '.dw-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.dw-section h2', wpSel: '.et_pb_section_1 h2' },
        ],
      },
      {
        name: 'problems', wpSelector: '.et_pb_section_2', htmlSelector: '.problems-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.problems-section h2', wpSel: '.et_pb_section_2 h2' },
        ],
      },
      {
        name: 'capabilities', wpSelector: '.et_pb_section_3', htmlSelector: '.wms-capabilities-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.wms-capabilities-section h2', wpSel: '.et_pb_section_3 h2' },
        ],
      },
      {
        name: 'mobile-functions', wpSelector: '.et_pb_section_4', htmlSelector: '.mobile-functions-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.mobile-functions-section h2', wpSel: '.et_pb_section_4 h2' },
        ],
      },
      {
        name: 'process-flow', wpSelector: '.et_pb_section_5', htmlSelector: '.process-flow-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.process-flow-section h2', wpSel: '.et_pb_section_5 h2' },
        ],
      },
      {
        name: 'transformation', wpSelector: '.et_pb_section_6', htmlSelector: '.transformation-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.transformation-section h2', wpSel: '.et_pb_section_6 h2' },
        ],
      },
      {
        name: 'integration', wpSelector: '.et_pb_section_7', htmlSelector: '.integration-section',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.integration-section h2', wpSel: '.et_pb_section_7 h2' },
        ],
      },
      {
        name: 'section-2', wpSelector: '.et_pb_section_8', htmlSelector: '.wms-faq',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'FAQ Title', htmlSel: '.wms-faq h2', wpSel: '.et_pb_section_8 h2' },
        ],
      },
      {
        name: 'product-detail-cta', wpSelector: '.et_pb_section_9', htmlSelector: '.product-detail-cta',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Section Title', htmlSel: '.product-detail-cta h2', wpSel: '.et_pb_section_9 h2' },
        ],
      },
      {
        name: 'related-solutions', wpSelector: '.et_pb_section_10', htmlSelector: '.related-solutions',
        pixelThreshold: 0.1,
        styleMap: [
          { label: 'Related Title', htmlSel: '.related-solutions h2', wpSel: '.et_pb_section_10 h2' },
        ],
      },
    ],
  },
};
