/**
 * about-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: about.html line 2212
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 15 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: about-hero, dw-d-bg, dw-d-bg--left, dw-d-bg--gradient, dw-d-parallax (+8 more)
 */

const base = require('../../lib/templates/_base');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="about-hero">
    <div class="dw-d-bg dw-d-bg--left dw-d-bg--gradient dw-d-parallax" style="opacity: 0.16;"></div>
            <div class="about-hero-inner">
                <div class="about-hero-content">
                    <h1><span class="dw-years">44</span> Years of Manufacturing Intelligence</h1>
                    <p>From a Taiwanese startup in 1982 to the trusted ERP partner for 50,000+ manufacturers across Asia. We have survived every economic cycle—from the Asian Financial Crisis to Covid-19—without abandoning our manufacturing focus.</p>
                    <a href="#mission" class="hero-scroll-cta">
                        Explore Our Story
                        <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M12 5v14M5 12l7 7 7-7"/></svg>
                    </a>
                </div>
                <div class="about-hero-stats">
                    <div class="hero-stat">
                        <div class="hero-stat-value">1982</div>
                        <div class="hero-stat-label">Founded in Taiwan</div>
                    </div>
                    <div class="hero-stat">
                        <div class="hero-stat-value">50K+</div>
                        <div class="hero-stat-label">Manufacturing Clients</div>
                    </div>
                    <div class="hero-stat">
                        <div class="hero-stat-value">1,600+</div>
                        <div class="hero-stat-label">R&D Engineers</div>
                    </div>
                    <div class="hero-stat">
                        <div class="hero-stat-value">300378</div>
                        <div class="hero-stat-label">Shenzhen Stock Exchange</div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */
.about-hero {
            background: linear-gradient(135deg, #000432 0%, #000864 50%, #001080 100%);
            padding: 140px 24px 100px;
            position: relative;
            overflow: hidden;
        }
.about-hero::before {
            content: '';
            position: absolute;
            inset: 0;
            background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Ccircle cx='30' cy='30' r='1.5'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
            pointer-events: none;
        }
.about-hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            position: relative;
            z-index: 1;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 80px;
            align-items: center;
        }
.about-hero-content h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: clamp(36px, 5vw, 52px);
            font-weight: 700;
            color: #fff;
            line-height: 1.15;
            margin-bottom: 24px;
        }
.about-hero-content h1 span {
            color: #00AFF0;
        }
.about-hero-content p {
            font-size: 18px;
            color: rgba(255,255,255,0.85);
            line-height: 1.7;
            margin-bottom: 24px;
        }
.hero-scroll-cta {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            color: #00AFF0;
            font-weight: 600;
            font-size: 15px;
            text-decoration: none;
            transition: all 0.3s ease;
        }
.hero-scroll-cta:hover {
            gap: 12px;
        }
.hero-scroll-cta svg {
            width: 20px;
            height: 20px;
            stroke: currentColor;
            animation: bounce-down 2s ease-in-out infinite;
        }
@keyframes bounce-down {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(6px); }
        }
.about-hero-stats {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 24px;
        }
.hero-stat {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 16px;
            padding: 32px;
            text-align: center;
        }
.hero-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 48px;
            font-weight: 700;
            color: #00AFF0;
            line-height: 1;
            margin-bottom: 8px;
        }
.hero-stat-label {
            font-size: 14px;
            color: rgba(255,255,255,0.75);
        }
@media (max-width: 1024px) {
            .about-hero-inner, .story-grid, .thailand-content, .mission-inner, .outcomes-inner {
                grid-template-columns: 1fr;
                gap: 48px;
            }
            .beliefs-grid {
                grid-template-columns: 1fr;
            }
            .stats-banner-inner {
                grid-template-columns: repeat(3, 1fr);
            }
            .about-hero-stats {
                max-width: 400px;
                margin: 0 auto;
            }
            .why-cards {
                grid-template-columns: repeat(2, 1fr);
            }
            .global-stats {
                grid-template-columns: repeat(2, 1fr);
            }
            .asean-timeline {
                flex-direction: column;
            }
            .asean-arrow {
                transform: rotate(90deg);
            }
        }
@media (max-width: 640px) {
            .about-hero {
                padding: 120px 20px 80px;
            }
            .about-hero-content h1 {
                font-size: 28px;
            }
            .about-hero-stats {
                grid-template-columns: 1fr;
            }
            .why-cards {
                grid-template-columns: 1fr;
            }
            .global-stats {
                grid-template-columns: 1fr;
            }
            .thailand-proof-grid {
                grid-template-columns: 1fr;
            }
            .stats-banner-inner {
                grid-template-columns: repeat(2, 1fr);
                gap: 24px;
            }
            .stat-number {
                font-size: 40px;
            }
            .mission-image {
                height: 280px;
            }
            .outcomes-image {
                height: 320px;
            }
            .mission-content h2, .outcomes-content h2 {
                font-size: 28px;
            }
            .asia-map-visual {
                display: none;
            }
            .asia-map-mobile {
                display: block;
            }
            .region-grid {
                grid-template-columns: 1fr;
            }
        }
@media (prefers-reduced-motion: reduce) {
            .hero-scroll-cta svg,
            .milestone-card,
            .region-block,
            .belief-card,
            .why-card,
            .award-card,
            .contact-cta,
            .asean-year,
            .region-cities span.more,
            .region-cities span.less,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
        }

/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-d-parallax{will-change:transform} */
/* @media (prefers-reduced-motion:reduce){.products-hero-content,.hero-stack-visual,.products-hero::before,.products-hero-badge::before,.stack-layer,.stack-layer::before,.data-particle,.ecosystem-node,.ecosystem-line,.ecosystem-ring,.data-flow-line,.data-flow-dot,.integration-hub::before,.integration-hub::after,.pp-card,.why-card,.why-card-icon,.pp-card-icon,.products-cta-glow,.dw-d-parallax,.dw-wave-flow,.dw-d-bg{animation:none !important;transition:none !important}.pp-card.visible{opacity:1;transform:none}} */

\${base.reducedMotion(\`\`)}
`.trim();
}

module.exports = { blocks, css };
