/**
 * about-beliefs.js — Beliefs Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: about.html line 2469
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 2 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: beliefs-section, dw-section-scene, beliefs-inner, beliefs-header, section-label (+3 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'bel'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="beliefs-section">
    <div class="dw-section-scene">
                <svg aria-hidden="true" viewBox="0 0 1400 900" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice">
                    <path d="M250 200 L250 420 Q250 520 350 570 Q450 520 450 420 L450 200 L350 160Z" stroke="#000864" stroke-width="2" fill="none" opacity="0.1"/>
                    <path d="M320 330 L345 355 L400 300" stroke="#00AFF0" stroke-width="2.5" fill="none" opacity="0.15"/>
                    <circle cx="800" cy="200" r="60" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.08"/>
                    <ellipse cx="800" cy="200" rx="30" ry="60" stroke="#000864" stroke-width="1" fill="none" opacity="0.06"/>
                    <line x1="740" y1="200" x2="860" y2="200" stroke="#000864" stroke-width="1" opacity="0.06"/>
                    <circle cx="780" cy="185" r="3" fill="#00AFF0" opacity="0.15"/>
                    <circle cx="820" cy="210" r="3" fill="#00AFF0" opacity="0.12"/>
                    <circle cx="795" cy="225" r="2.5" fill="#00AFF0" opacity="0.1"/>
                    <line x1="100" y1="700" x2="600" y2="700" stroke="#000864" stroke-width="1" opacity="0.08"/>
                    <line x1="100" y1="690" x2="100" y2="710" stroke="#000864" stroke-width="1" opacity="0.08"/>
                    <line x1="350" y1="690" x2="350" y2="710" stroke="#000864" stroke-width="1" opacity="0.08"/>
                    <line x1="600" y1="690" x2="600" y2="710" stroke="#000864" stroke-width="1" opacity="0.08"/>
                    <text x="100" y="730" font-family="'Noto Sans',sans-serif" font-size="10" fill="#000864" opacity="0.06" text-anchor="middle">1982</text>
                    <text x="350" y="730" font-family="'Noto Sans',sans-serif" font-size="10" fill="#000864" opacity="0.06" text-anchor="middle">2006</text>
                    <text x="600" y="730" font-family="'Noto Sans',sans-serif" font-size="10" fill="#000864" opacity="0.06" text-anchor="middle">2026</text>
                    <rect x="1050" y="400" width="200" height="120" rx="8" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.08"/>
                    <line x1="1070" y1="440" x2="1230" y2="440" stroke="#000864" stroke-width="0.5" opacity="0.06"/>
                    <line x1="1070" y1="460" x2="1200" y2="460" stroke="#000864" stroke-width="0.5" opacity="0.06"/>
                    <line x1="1070" y1="480" x2="1210" y2="480" stroke="#000864" stroke-width="0.5" opacity="0.06"/>
                    <text x="1150" y="420" font-family="'Noto Sans',sans-serif" font-size="9" font-weight="700" fill="#000864" opacity="0.06" text-anchor="middle">VALUES</text>
                    <circle cx="650" cy="450" r="3" fill="#000864" opacity="0.06"/>
                    <circle cx="1300" cy="300" r="4" fill="#000864" opacity="0.05"/>
                    <circle cx="150" cy="500" r="3" fill="#00AFF0" opacity="0.08"/>
                </svg>
            </div>
            <div class="beliefs-inner">
                <div class="beliefs-header">
                    <span class="section-label">OUR PHILOSOPHY</span>
                    <h2>What We Believe</h2>
                </div>
                <div class="beliefs-grid">
                    <div class="belief-card">
                        <div class="belief-number">BELIEF 01</div>
                        <h3>"Manufacturing Is Not Generic"</h3>
                        <p>We don't sell to banks, retailers, or hospitals. We are manufacturing-only because the factory floor demands it. BOMs, routings, work orders, OEE—these aren't features we added; they're why we exist.</p>
                    </div>
                    <div class="belief-card">
                        <div class="belief-number">BELIEF 02</div>
                        <h3>"Grow Together, Not Apart"</h3>
                        <p>Our product suite—iGP → T100 → MES → WMS → AIoT—means your ERP partner doesn't change as your business scales. Your investment compounds, never resets. From 20-person workshop to multi-site enterprise group.</p>
                    </div>
                    <div class="belief-card">
                        <div class="belief-number">BELIEF 03</div>
                        <h3>"Local Roots, Global Standards"</h3>
                        <p>Our Thailand team speaks Thai, understands Thai business culture, and is backed by 44 years of global manufacturing expertise. We're not a remote vendor sending consultants from overseas—we're here.</p>
                    </div>
                    <div class="belief-card">
                        <div class="belief-number">BELIEF 04</div>
                        <h3>"Data Should Liberate, Not Complicate"</h3>
                        <p>We turn factory chaos—shadow Excel, ghost inventory, disconnected systems—into clear, actionable intelligence. Your production manager shouldn't need 3 spreadsheets to answer a simple question.</p>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Beliefs', html, 'Beliefs: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === BELIEFS (S6) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .beliefs-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.beliefs-section {
            padding: 100px 24px;
            background: #fff;
        }
.beliefs-inner {
            max-width: 1100px;
            margin: 0 auto;
            position: relative;
            z-index: 2;
        }
.beliefs-header {
            text-align: center;
            margin-bottom: 60px;
        }
.beliefs-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 16px;
        }
.beliefs-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 32px;
        }
.belief-card {
            background: linear-gradient(135deg, #f8fafc, #fff);
            border: 1px solid #e2e8f0;
            border-radius: 20px;
            padding: 40px;
            transition: all 0.3s ease;
        }
.belief-card:hover {
            border-color: #00AFF0;
            box-shadow: 0 12px 40px rgba(0, 175, 240, 0.1);
        }
.belief-number {
            font-family: 'JetBrains Mono', monospace;
            font-size: 12px;
            font-weight: 600;
            color: #0369a1;
            letter-spacing: 1px;
            margin-bottom: 16px;
        }
.belief-card h3 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 22px;
            font-weight: 600;
            color: #000864;
            margin-bottom: 16px;
            line-height: 1.3;
        }
.belief-card p {
            font-size: 15px;
            color: #5b6b80;
            line-height: 1.7;
        }
@media(max-width:1024px){.beliefs-grid{grid-template-columns:1fr}}

/* SVG scene positioning */
.dw-section-scene{position:relative}
.dw-section-scene svg{position:absolute;top:0;left:0;width:100%;height:100%;pointer-events:none}

/* Divi overrides */
.et_pb_section .beliefs-header h2{font-weight:700 !important;line-height:1.2 !important}
.et_pb_section .belief-card h3{line-height:1.3 !important}
.et_pb_section .belief-card p{padding-bottom:0 !important;line-height:25.5px !important}
.beliefs-section .section-label{color:#0369a1}

${base.reducedMotion('')}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'outline', position: 'right' })}
`.trim();
}

module.exports = { blocks, css };
