/**
 * about-mission.js — Mission Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: about.html line 2246
 *
 * styles.css: 14 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: mission-section, dw-d-bg, dw-d-bg--center, mission-inner, mission-content (+6 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'mis'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="mission-section">
    <div class="dw-d-bg dw-d-bg--center" style="opacity: 0.06;"></div>
            <div class="mission-inner" style="position: relative; z-index: 2;">
                <div class="mission-content">
                    <h2>We Power Manufacturing's <span>Digital Future</span></h2>
                    <p>DigiWin exists to help manufacturers see clearly, act decisively, and grow confidently. For over four decades, we've been singularly focused on one thing: making factory operations visible, predictable, and profitable.</p>
                    <p>We don't serve banks, retailers, or hospitals. We serve the shop floor—the engineers tracking BOMs, the planners scheduling production runs, the operators monitoring OEE in real time. This focus isn't a marketing position. It's our DNA.</p>
                    <p>Every line of code we write, every consultant we train, every implementation we deliver is designed for one outcome: helping manufacturers compete and win.</p>
                    <p>Today, we're transforming from a software vendor into an AI infrastructure provider. Backed by 1,600+ R&D engineers and 1,800+ implementation consultants, DigiWin has developed 168 AI Agents and 68 operational SOPs to standardize and accelerate digital transformation. DigiWin is pioneering the Zhuge Platform — where AI doesn't just report on your factory, it helps run it.</p>
                    <div class="mission-origin">
                        <div class="mission-origin-chinese">鼎新</div>
                        <div class="mission-origin-pinyin">Dǐng Xīn</div>
                        <div class="mission-origin-meaning">"To innovate, to renew" — This is the meaning behind our name. Founded by Sun Ai-bin and Gu Feng-yong in 1982, this philosophy has driven us for over four decades.</div>
                    </div>
                </div>
                <div class="mission-visual">
                    <div class="mission-image">
                        <img src="images/about-mission.jpg" alt="Smart factory floor with digital manufacturing technology" loading="lazy">
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Mission', html, 'Mission: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === MISSION (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .mission-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
@keyframes bounce-down {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(6px); }
        }
.mission-section {
            padding: 100px 24px;
            background: #fff;
        }
.mission-inner {
            max-width: 1100px;
            margin: 0 auto;
            display: grid;
            grid-template-columns: 1.2fr 1fr;
            gap: 80px;
            align-items: center;
        }
.mission-content h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 36px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 32px;
            line-height: 1.2;
        }
.mission-content h2 span {
            color: #0369a1;
        }
.mission-content p {
            font-size: 17px;
            color: #475569;
            line-height: 1.8;
            margin-bottom: 24px;
        }
.mission-origin {
            background: linear-gradient(135deg, #eff6ff, #dbeafe);
            border-left: 4px solid #00AFF0;
            padding: 24px 28px;
            border-radius: 0 12px 12px 0;
            margin-top: 32px;
        }
.mission-origin-chinese {
            font-family: 'Noto Sans TC', sans-serif;
            font-size: 32px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 8px;
        }
.mission-origin-pinyin {
            font-family: 'JetBrains Mono', monospace;
            font-size: 14px;
            color: #5b6b80;
            margin-bottom: 12px;
        }
.mission-origin-meaning {
            font-size: 15px;
            color: #475569;
            font-style: italic;
        }
.mission-visual {
            position: relative;
        }
.mission-image {
            width: 100%;
            height: 400px;
            border-radius: 24px;
            overflow: hidden;
            position: relative;
        }
.mission-image img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }
@media (max-width: 1024px) {
            .about-hero-inner, .story-grid, .thailand-content, .mission-inner, .outcomes-inner {
                grid-template-columns: 1fr;
                gap: 48px;
            }
            .beliefs-grid {
                grid-template-columns: 1fr;
            }
            .stats-banner-inner {
                grid-template-columns: repeat(3, 1fr);
            }
            .about-hero-stats {
                max-width: 400px;
                margin: 0 auto;
            }
            .why-cards {
                grid-template-columns: repeat(2, 1fr);
            }
            .global-stats {
                grid-template-columns: repeat(2, 1fr);
            }
            .asean-timeline {
                flex-direction: column;
            }
            .asean-arrow {
                transform: rotate(90deg);
            }
        }
@media (max-width: 640px) {
            .about-hero {
                padding: 120px 20px 80px;
            }
            .about-hero-content h1 {
                font-size: 28px;
            }
            .about-hero-stats {
                grid-template-columns: 1fr;
            }
            .why-cards {
                grid-template-columns: 1fr;
            }
            .global-stats {
                grid-template-columns: 1fr;
            }
            .thailand-proof-grid {
                grid-template-columns: 1fr;
            }
            .stats-banner-inner {
                grid-template-columns: repeat(2, 1fr);
                gap: 24px;
            }
            .stat-number {
                font-size: 40px;
            }
            .mission-image {
                height: 280px;
            }
            .outcomes-image {
                height: 320px;
            }
            .mission-content h2, .outcomes-content h2 {
                font-size: 28px;
            }
            .asia-map-visual {
                display: none;
            }
            .asia-map-mobile {
                display: block;
            }
            .region-grid {
                grid-template-columns: 1fr;
            }
        }
@media (prefers-reduced-motion: reduce) {
            .hero-scroll-cta svg,
            .milestone-card,
            .region-block,
            .belief-card,
            .why-card,
            .award-card,
            .contact-cta,
            .asean-year,
            .region-cities span.more,
            .region-cities span.less,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
        }

${base.reducedMotion('')}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'outline', position: 'right' })}
`.trim();
}

module.exports = { blocks, css };
