/**
 * about-cta.js — Cta Section (S11)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: about.html line 3248
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 25 base, 5 hover, 0 pseudo, 1 hidden
 * Original classes: about-cta, dw-d-bg, dw-d-bg--gradient, dw-d-parallax, dw-wave-flow (+8 more)
 */

const base = require('../../lib/templates/_base');

const P = 'cta'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="about-cta">
    <div class="dw-d-bg dw-d-bg--gradient dw-d-parallax" style="opacity: 0.12;"></div>
            
            <div class="dw-wave-flow" style="height: 160px; opacity: 0.3; z-index: 1;"></div>
            <div class="about-cta-inner" style="position: relative; z-index: 3;">
                <h2>Ready to Work with a Team That Understands Manufacturing?</h2>
                <p>See how <span class="dw-years">44</span> years of manufacturing expertise—backed by Foxconn FII—can help you compete on the global stage.</p>
                <div class="about-cta-buttons">
                    <a href="demo.html" class="dw-btn dw-btn-white">Let's Talk</a>
                    <a href="partner-program.html" class="dw-btn dw-btn-outline-white">Become a Partner</a>
                </div>
                <div class="cta-contact-info">
                    <div class="cta-contact-item">
                        <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z"/><circle cx="12" cy="10" r="3"/></svg>
                        <span>No. 2/117-118, Bangna Complex Office Tower, 22F, Theparat Rd, Bangna, Bangkok 10260</span>
                    </div>
                    <div class="cta-contact-item">
                        <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
                        <a href="mailto:info@digiwin.co.th">info@digiwin.co.th</a>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Cta', html, 'Cta: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CTA (S11) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
@keyframes bounce-down {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(6px); }
        }
.about-cta {
            padding: 100px 24px;
            background: linear-gradient(135deg, #00AFF0 0%, #003CC8 50%, #001080 100%);
            position: relative;
            overflow: hidden;
        }
.about-cta::before {
            content: '';
            position: absolute;
            inset: 0;
            background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.07'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
            pointer-events: none;
        }
.about-cta-inner {
            max-width: 800px;
            margin: 0 auto;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.about-cta h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #fff;
            margin-bottom: 16px;
        }
.about-cta p {
            font-size: 18px;
            color: rgba(255,255,255,0.9);
            margin-bottom: 40px;
        }
.about-cta-buttons {
            display: flex;
            gap: 16px;
            justify-content: center;
            flex-wrap: wrap;
            margin-bottom: 40px;
        }
.cta-contact-info {
            display: flex;
            gap: 40px;
            justify-content: center;
            flex-wrap: wrap;
        }
.cta-contact-item {
            display: flex;
            align-items: center;
            gap: 10px;
            font-size: 15px;
            color: rgba(255,255,255,0.85);
        }
.cta-contact-item svg {
            width: 18px;
            height: 18px;
            flex-shrink: 0;
        }
.cta-contact-item a {
            color: #fff;
            text-decoration: none;
        }
.cta-contact-item a:hover {
            text-decoration: underline;
        }
@media (prefers-reduced-motion: reduce) {
            .hero-scroll-cta svg,
            .milestone-card,
            .region-block,
            .belief-card,
            .why-card,
            .award-card,
            .contact-cta,
            .asean-year,
            .region-cities span.more,
            .region-cities span.less,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
        }

/* Buttons */
.dw-btn{font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;padding:16px 32px;border-radius:8px;cursor:pointer;transition:all 0.3s ease;text-decoration:none;display:inline-flex;align-items:center;gap:8px;border:none}
.dw-btn-white{background:#ffffff;color:#00AFF0 !important;box-shadow:0 4px 14px rgba(0,0,0,0.15)}
.dw-btn-white:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,0.2)}
.dw-btn-outline-white{background:transparent;color:#ffffff;padding:16px 32px;border-radius:8px;border:2px solid rgba(255, 255, 255, 0.5);font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.3s ease;display:inline-flex;align-items:center;gap:8px}
.dw-btn-outline-white:hover{background:rgba(255, 255, 255, 0.15);border-color:#ffffff}
/* WARNING: HIDDEN in styles.css (display:none) — DO NOT include in builder HTML */
/* .dw-wave-flow,
 * .dw-wave-flow--top {
 *     display: none;
 * } */
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
