/**
 * aiot-problem.js — Problem Section (S3)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: aiot.html line 1250
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 2 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: problem-section, dw-section-scene, problem-header, problem-grid, problem-card (+1 more)
 */

const base = require('../../lib/templates/_base');

const P = 'pro'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="problem-section">
    <div class="dw-section-scene">
                <svg aria-hidden="true" viewBox="0 0 1400 900" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice">
                    <rect x="100" y="300" width="100" height="80" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <circle cx="150" cy="340" r="15" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.12"/>
                    <path d="M200 340 L300 340" stroke="#000864" stroke-width="1.5" opacity="0.1" stroke-dasharray="6 4"/>
                    <g opacity="0.4"><line x1="290" y1="330" x2="310" y2="350" stroke="#00AFF0" stroke-width="2"/><line x1="310" y1="330" x2="290" y2="350" stroke="#00AFF0" stroke-width="2"/></g>
                    <rect x="400" y="300" width="100" height="80" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <circle cx="450" cy="340" r="15" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.12"/>
                    <path d="M500 340 L600 340" stroke="#000864" stroke-width="1.5" opacity="0.1" stroke-dasharray="6 4"/>
                    <g opacity="0.35"><line x1="590" y1="330" x2="610" y2="350" stroke="#00AFF0" stroke-width="2"/><line x1="610" y1="330" x2="590" y2="350" stroke="#00AFF0" stroke-width="2"/></g>
                    <rect x="700" y="300" width="100" height="80" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <circle cx="750" cy="340" r="15" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.12"/>
                    <path d="M800 340 L900 340" stroke="#000864" stroke-width="1.5" opacity="0.1" stroke-dasharray="6 4"/>
                    <g opacity="0.3"><line x1="890" y1="330" x2="910" y2="350" stroke="#00AFF0" stroke-width="2"/><line x1="910" y1="330" x2="890" y2="350" stroke="#00AFF0" stroke-width="2"/></g>
                    <path d="M150 250 Q150 230 160 230" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.15"/>
                    <path d="M150 245 Q150 220 165 220" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.12"/>
                    <path d="M150 240 Q150 210 170 210" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.1"/>
                    <path d="M450 250 Q450 230 460 230" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.15"/>
                    <path d="M450 245 Q450 220 465 220" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.12"/>
                    <path d="M750 250 Q750 230 760 230" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.15"/>
                    <path d="M750 245 Q750 220 765 220" stroke="#00AFF0" stroke-width="1" fill="none" opacity="0.12"/>
                    <rect x="1050" y="200" width="200" height="120" rx="8" stroke="#000864" stroke-width="2" fill="none" opacity="0.1"/>
                    <line x1="1070" y1="250" x2="1130" y2="250" stroke="#000864" stroke-width="0.5" opacity="0.1"/>
                    <line x1="1070" y1="265" x2="1200" y2="265" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="1070" y1="280" x2="1180" y2="280" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <text x="1090" y="230" font-family="'Noto Sans',sans-serif" font-size="9" font-weight="700" fill="#000864" opacity="0.08">NO DATA</text>
                    <circle cx="300" cy="600" r="3" fill="#000864" opacity="0.1"/>
                    <circle cx="600" cy="550" r="4" fill="#000864" opacity="0.08"/>
                    <circle cx="900" cy="600" r="3" fill="#00AFF0" opacity="0.1"/>
                    <circle cx="1200" cy="500" r="3" fill="#000864" opacity="0.08"/>
                    <text x="500" y="700" font-family="'Noto Sans',sans-serif" font-size="28" font-weight="800" fill="#000864" opacity="0.05">?</text>
                </svg>
            </div>
            <div class="problem-header" style="position: relative; z-index: 2;">
                <h2>Most Factories Are Flying Blind</h2>
                <p>Your machines talk. But without the right ears, you're missing critical intelligence.</p>
            </div>
            <div class="problem-grid" style="position: relative; z-index: 2;">
                <div class="problem-card">
                    <div class="problem-icon">
                        <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M11 5L6 9H2v6h4l5 4V5z"/><line x1="23" y1="9" x2="17" y2="15"/><line x1="17" y1="9" x2="23" y2="15"/></svg>
                    </div>
                    <h3>Silent Machines</h3>
                    <p>Machines run without reporting. Problems only surface after breakdowns.</p>
                </div>
                <div class="problem-card">
                    <div class="problem-icon">
                        <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>
                    </div>
                    <h3>Reactive Maintenance</h3>
                    <p>Fix it when it breaks. Unplanned downtime costs 10x more than scheduled maintenance.</p>
                </div>
                <div class="problem-card">
                    <div class="problem-icon">
                        <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1" ry="1"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="9" y1="16" x2="15" y2="16"/></svg>
                    </div>
                    <h3>Manual OEE</h3>
                    <p>Staff tracking production on clipboards. Data is late, inaccurate, or simply not collected.</p>
                </div>
                <div class="problem-card">
                    <div class="problem-icon">
                        <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>
                    </div>
                    <h3>Hidden Energy Waste</h3>
                    <p>No visibility into which machines consume what. Energy costs spike unexplained.</p>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Problem', html, 'Problem: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === PROBLEM (S3) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.problem-section {
            padding: 100px 0;
            background: #fff;
        }
.problem-header {
            text-align: center;
            max-width: 800px;
            margin: 0 auto 60px;
        }
.problem-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 36px;
            color: #000864;
            margin-bottom: 16px;
        }
.problem-header p {
            font-size: 18px;
            color: #5b6b80;
        }
.problem-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 24px;
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
        }
.problem-card {
            background: linear-gradient(145deg, #fef2f2 0%, #fee2e2 100%);
            border: 1px solid #fecaca;
            border-radius: 16px;
            padding: 32px 24px;
            text-align: center;
            transition: all 0.4s ease;
        }
.problem-card:hover {
            box-shadow: 0 12px 32px rgba(185, 28, 28, 0.1);
        }
.problem-icon {
            width: 56px;
            height: 56px;
            background: linear-gradient(135deg, #fee2e2, #fecaca);
            border-radius: 14px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 16px;
            transition: all 0.4s ease;
        }
.problem-icon svg {
            width: 28px;
            height: 28px;
            stroke: #b91c1c;
            stroke-width: 1.5;
            fill: none;
        }
.problem-card:hover .problem-icon {
            background: linear-gradient(135deg, #00AFF0, #003CC8);
        }
.problem-card:hover .problem-icon svg {
            stroke: #fff;
        }
.problem-card h3 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 18px;
            color: #991b1b;
            margin-bottom: 12px;
        }
.problem-card p {
            font-size: 14px;
            color: #b91c1c;
            line-height: 1.6;
        }
@media (max-width: 1024px) {
            .aiot-hero-grid { grid-template-columns: 1fr; gap: 40px; }
            .aiot-hero-content { text-align: center; }
            .aiot-sensor-dashboard { max-width: 400px; margin: 0 auto; }
            .aiot-hero h1 { font-size: 40px; }
            .aiot-hero-stats { gap: 40px; justify-content: center; }
            .problem-grid { grid-template-columns: repeat(2, 1fr); }
            .dataflow-stages { flex-wrap: wrap; }
            .dataflow-stage:not(:last-child)::after { display: none; }
            .capabilities-grid { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: repeat(2, 1fr); }
        }
@media (max-width: 640px) {
            .aiot-hero { padding: 120px 0 80px; }
            .aiot-hero h1 { font-size: 32px; }
            .aiot-hero-subtitle { font-size: 17px; }
            .aiot-hero-stats { flex-direction: column; gap: 24px; }
            .aiot-hero-stat-value { font-size: 36px; }
            .problem-grid { grid-template-columns: 1fr; }
            .dataflow-stages { flex-direction: column; }
            .capability-features { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: 1fr; }
            .integration-diagram { flex-direction: column; }
            .integration-arrow { transform: rotate(90deg); }
        }
@media (prefers-reduced-motion: reduce) {
            .aiot-live-dot,
            .problem-card,
            .problem-icon,
            .capability-card,
            .capability-icon,
            .integration-node,
            .integration-link,
            .dw-d-bg,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-d-glow {
                animation: none !important;
                transition: none !important;
            }
        }

\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
