/**
 * aiot-metrics.js — Metrics Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: aiot.html line 1487
 *
 * Original classes: metrics-section, metrics-header, metrics-grid, metric-card, metric-value (+1 more)
 */

const base = require('../../lib/templates/_base');

const P = 'met'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="metrics-section">
    <div class="metrics-header">
                <h2>Measured Impact</h2>
                <p>What our customers achieve with AIoT implementation</p>
            </div>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">+15%</div>
                    <div class="metric-label">OEE Improvement</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">-40%</div>
                    <div class="metric-label">Unplanned Downtime</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">-12%</div>
                    <div class="metric-label">Energy Costs</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">100%</div>
                    <div class="metric-label">Data Accuracy</div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Metrics', html, 'Metrics: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === METRICS (S6) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.metrics-section {
            padding: 100px 0;
            background: linear-gradient(135deg, #000864 0%, #000432 100%);
        }
.metrics-header {
            text-align: center;
            max-width: 700px;
            margin: 0 auto 60px;
            padding: 0 24px;
        }
.metrics-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 36px;
            color: #fff;
            margin-bottom: 16px;
        }
.metrics-header p {
            font-size: 18px;
            color: rgba(255,255,255,0.75);
        }
.metrics-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 24px;
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }
.metric-card {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 16px;
            padding: 32px 24px;
            text-align: center;
        }
.metric-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 48px;
            font-weight: 700;
            color: #00AFF0;
            line-height: 1;
        }
.metric-label {
            font-size: 15px;
            color: rgba(255,255,255,0.8);
            margin-top: 12px;
            line-height: 1.4;
        }
@media (max-width: 1024px) {
            .aiot-hero-grid { grid-template-columns: 1fr; gap: 40px; }
            .aiot-hero-content { text-align: center; }
            .aiot-sensor-dashboard { max-width: 400px; margin: 0 auto; }
            .aiot-hero h1 { font-size: 40px; }
            .aiot-hero-stats { gap: 40px; justify-content: center; }
            .problem-grid { grid-template-columns: repeat(2, 1fr); }
            .dataflow-stages { flex-wrap: wrap; }
            .dataflow-stage:not(:last-child)::after { display: none; }
            .capabilities-grid { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: repeat(2, 1fr); }
        }
@media (max-width: 640px) {
            .aiot-hero { padding: 120px 0 80px; }
            .aiot-hero h1 { font-size: 32px; }
            .aiot-hero-subtitle { font-size: 17px; }
            .aiot-hero-stats { flex-direction: column; gap: 24px; }
            .aiot-hero-stat-value { font-size: 36px; }
            .problem-grid { grid-template-columns: 1fr; }
            .dataflow-stages { flex-direction: column; }
            .capability-features { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: 1fr; }
            .integration-diagram { flex-direction: column; }
            .integration-arrow { transform: rotate(90deg); }
        }



`.trim();
}

module.exports = { blocks, css };
