/**
 * aiot-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: aiot.html line 1163
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 15 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: aiot-hero, dw-d-bg, dw-d-bg--center, dw-d-bg--particle, dw-d-parallax (+28 more)
 */

const base = require('../../lib/templates/_base');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="aiot-hero">
    <div class="dw-d-bg dw-d-bg--center dw-d-bg--particle dw-d-parallax" style="opacity: 0.12;"></div>
            <div class="aiot-hero-inner">
                <div class="aiot-hero-grid">
                    <div class="aiot-hero-content">
                        <div class="aiot-hero-badge">
                            <span>Industrial Intelligence Platform</span>
                        </div>
                        <h1>Your Machines <span>Know Everything.</span><br>But Can You Hear Them?</h1>
                        <p class="aiot-hero-subtitle">Every machine generates thousands of data points daily. DigiWin AIoT captures, analyzes, and transforms this data into competitive advantage.</p>
                        <div class="aiot-hero-stats">
                            <div class="aiot-hero-stat">
                                <div class="aiot-hero-stat-value">50+</div>
                                <div class="aiot-hero-stat-label">Protocols Supported</div>
                            </div>
                            <div class="aiot-hero-stat">
                                <div class="aiot-hero-stat-value">1M+</div>
                                <div class="aiot-hero-stat-label">Data Points/Day</div>
                            </div>
                            <div class="aiot-hero-stat">
                                <div class="aiot-hero-stat-value">< 1s</div>
                                <div class="aiot-hero-stat-label">Real-Time Response</div>
                            </div>
                        </div>
                    </div>
                    <div class="aiot-hero-visual">
                        <div class="aiot-sensor-dashboard">
                            <div class="aiot-dashboard-header">
                                <span class="aiot-dashboard-title">Live Sensor Data</span>
                                <span class="aiot-live-badge"><span class="aiot-live-dot"></span> Live</span>
                            </div>
                            <div class="aiot-sensor-grid">
                                <div class="aiot-sensor-tile">
                                    <div class="aiot-sensor-icon"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 2v20M2 12h20M4.93 4.93l14.14 14.14M4.93 19.07l14.14-14.14"/></svg></div>
                                    <div class="aiot-sensor-value">78.4°C</div>
                                    <div class="aiot-sensor-label">Temperature</div>
                                </div>
                                <div class="aiot-sensor-tile warning">
                                    <div class="aiot-sensor-icon"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20"/><path d="M12 6v6l4 2"/></svg></div>
                                    <div class="aiot-sensor-value">2.4 mm/s</div>
                                    <div class="aiot-sensor-label">Vibration</div>
                                </div>
                                <div class="aiot-sensor-tile">
                                    <div class="aiot-sensor-icon"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg></div>
                                    <div class="aiot-sensor-value">47.2 kW</div>
                                    <div class="aiot-sensor-label">Power Draw</div>
                                </div>
                                <div class="aiot-sensor-tile">
                                    <div class="aiot-sensor-icon"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg></div>
                                    <div class="aiot-sensor-value">1,847</div>
                                    <div class="aiot-sensor-label">RPM</div>
                                </div>
                            </div>
                            <div class="aiot-machine-list">
                                <div class="aiot-machine-row">
                                    <span class="aiot-machine-name">CNC-M01</span>
                                    <span class="aiot-machine-status running"><span class="aiot-status-dot"></span> Running</span>
                                </div>
                                <div class="aiot-machine-row">
                                    <span class="aiot-machine-name">CNC-M02</span>
                                    <span class="aiot-machine-status idle"><span class="aiot-status-dot"></span> Idle</span>
                                </div>
                                <div class="aiot-machine-row">
                                    <span class="aiot-machine-name">CNC-M03</span>
                                    <span class="aiot-machine-status running"><span class="aiot-status-dot"></span> Running</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */
.aiot-hero {
            background: linear-gradient(135deg, #000432 0%, #000864 50%, #001080 100%);
            padding: 140px 0 100px;
            position: relative;
            overflow: hidden;
        }
.aiot-hero::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%233798E4' fill-opacity='0.08'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
            opacity: 0.5;
        }
.aiot-hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
            position: relative;
            z-index: 1;
        }
.aiot-hero-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 60px;
            align-items: center;
        }
.aiot-hero-content {
            text-align: left;
        }
.aiot-hero-visual {
            display: flex;
            justify-content: center;
        }
.aiot-sensor-dashboard {
            background: rgba(255,255,255,0.08);
            border: 1px solid rgba(255,255,255,0.15);
            border-radius: 16px;
            padding: 24px;
            width: 100%;
            max-width: 480px;
            backdrop-filter: blur(8px);
        }
.aiot-dashboard-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
            padding-bottom: 12px;
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }
.aiot-dashboard-title {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            color: #7EC8F2;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }
.aiot-live-badge {
            display: flex;
            align-items: center;
            gap: 6px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
            color: #22c55e;
            text-transform: uppercase;
        }
.aiot-live-dot {
            width: 6px;
            height: 6px;
            background: #22c55e;
            border-radius: 50%;
            animation: pulse-dot 1.5s infinite;
        }
.aiot-sensor-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px;
            margin-bottom: 20px;
        }
.aiot-sensor-tile {
            background: rgba(0, 175, 240, 0.15);
            border: 1px solid rgba(0, 175, 240, 0.25);
            border-radius: 10px;
            padding: 16px;
            text-align: center;
        }
.aiot-sensor-tile.warning {
            background: rgba(251, 191, 36, 0.15);
            border-color: rgba(251, 191, 36, 0.3);
        }
.aiot-sensor-tile.alert {
            background: rgba(239, 68, 68, 0.15);
            border-color: rgba(239, 68, 68, 0.3);
        }
.aiot-sensor-icon {
            width: 28px;
            height: 28px;
            margin: 0 auto 8px;
        }
.aiot-sensor-icon svg {
            width: 100%;
            height: 100%;
            stroke: #7EC8F2;
            stroke-width: 1.5;
            fill: none;
        }
.aiot-sensor-tile.warning .aiot-sensor-icon svg {
            stroke: #fbbf24;
        }
.aiot-sensor-tile.alert .aiot-sensor-icon svg {
            stroke: #ef4444;
        }
.aiot-sensor-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 22px;
            font-weight: 600;
            color: #fff;
            margin-bottom: 2px;
        }
.aiot-sensor-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 9px;
            color: rgba(255,255,255,0.75);
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
.aiot-machine-list {
            display: flex;
            flex-direction: column;
            gap: 8px;
        }
.aiot-machine-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background: rgba(255,255,255,0.05);
            border-radius: 8px;
            padding: 10px 14px;
        }
.aiot-machine-name {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            color: rgba(255,255,255,0.8);
        }
.aiot-machine-status {
            display: flex;
            align-items: center;
            gap: 6px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
        }
.aiot-machine-status.running { color: #22c55e; }
.aiot-machine-status.idle { color: #fbbf24; }
.aiot-machine-status.offline { color: #ef4444; }
.aiot-status-dot {
            width: 6px;
            height: 6px;
            border-radius: 50%;
        }
.aiot-machine-status.running .aiot-status-dot { background: #22c55e; }
.aiot-machine-status.idle .aiot-status-dot { background: #fbbf24; }
.aiot-machine-status.offline .aiot-status-dot { background: #ef4444; }
.aiot-hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(0, 175, 240, 0.2);
            border: 1px solid rgba(0, 175, 240, 0.3);
            padding: 8px 20px;
            border-radius: 50px;
            color: #7EC8F2;
            font-size: 11px;
            font-weight: 500;
            margin-bottom: 24px;
            font-family: 'JetBrains Mono', monospace;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }
.aiot-hero h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 52px;
            font-weight: 700;
            color: #fff;
            margin-bottom: 20px;
            line-height: 1.15;
        }
.aiot-hero h1 span {
            color: #00AFF0;
        }
.aiot-hero-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 20px;
            color: rgba(255,255,255,0.85);
            max-width: 700px;
            margin: 0 auto 40px;
            line-height: 1.6;
        }
.aiot-hero-stats {
            display: flex;
            justify-content: center;
            gap: 60px;
            margin-top: 50px;
        }
.aiot-hero-stat {
            text-align: center;
        }
.aiot-hero-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 42px;
            font-weight: 700;
            color: #00AFF0;
        }
.aiot-hero-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
            color: rgba(255,255,255,0.75);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-top: 4px;
        }
@media (max-width: 1024px) {
            .aiot-hero-grid { grid-template-columns: 1fr; gap: 40px; }
            .aiot-hero-content { text-align: center; }
            .aiot-sensor-dashboard { max-width: 400px; margin: 0 auto; }
            .aiot-hero h1 { font-size: 40px; }
            .aiot-hero-stats { gap: 40px; justify-content: center; }
            .problem-grid { grid-template-columns: repeat(2, 1fr); }
            .dataflow-stages { flex-wrap: wrap; }
            .dataflow-stage:not(:last-child)::after { display: none; }
            .capabilities-grid { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: repeat(2, 1fr); }
        }
@media (max-width: 640px) {
            .aiot-hero { padding: 120px 0 80px; }
            .aiot-hero h1 { font-size: 32px; }
            .aiot-hero-subtitle { font-size: 17px; }
            .aiot-hero-stats { flex-direction: column; gap: 24px; }
            .aiot-hero-stat-value { font-size: 36px; }
            .problem-grid { grid-template-columns: 1fr; }
            .dataflow-stages { flex-direction: column; }
            .capability-features { grid-template-columns: 1fr; }
            .metrics-grid { grid-template-columns: 1fr; }
            .integration-diagram { flex-direction: column; }
            .integration-arrow { transform: rotate(90deg); }
        }
@media (prefers-reduced-motion: reduce) {
            .aiot-live-dot,
            .problem-card,
            .problem-icon,
            .capability-card,
            .capability-icon,
            .integration-node,
            .integration-link,
            .dw-d-bg,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-d-glow {
                animation: none !important;
                transition: none !important;
            }
        }

/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-d-parallax{will-change:transform} */
/* @media (prefers-reduced-motion:reduce){.products-hero-content,.hero-stack-visual,.products-hero::before,.products-hero-badge::before,.stack-layer,.stack-layer::before,.data-particle,.ecosystem-node,.ecosystem-line,.ecosystem-ring,.data-flow-line,.data-flow-dot,.integration-hub::before,.integration-hub::after,.pp-card,.why-card,.why-card-icon,.pp-card-icon,.products-cta-glow,.dw-d-parallax,.dw-wave-flow,.dw-d-bg{animation:none !important;transition:none !important}.pp-card.visible{opacity:1;transform:none}} */

\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
