/**
 * aiot-section.js — Section Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: aiot.html line 1237
 *
 * styles.css: 17 base, 0 hover, 1 pseudo, 0 hidden
 * Original classes: dw-section
 */

const base = require('../../lib/templates/_base');

const P = 'sec'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-section" style="padding: 40px 0 0; text-align: center;">
    <div style="max-width: 800px; margin: 0 auto; padding: 0 24px;">
        <h2 style="font-family: 'Noto Sans', sans-serif; font-size: 22px; font-weight: 700; color: #000864; margin: 0 0 12px 0;">What is AIoT (Artificial Intelligence + Internet of Things)?</h2>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333; margin: 0 0 24px 0;">
          AIoT is technology that connects factory machines and sensors to collect real-time production data, then applies AI analytics to predict maintenance needs and optimize efficiency. It turns raw machine signals into actionable intelligence — letting you prevent breakdowns before they happen instead of reacting after the fact.
        </p>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333;">
          <strong>DigiWin AIoT</strong> is an industrial IoT platform that connects any machine, any protocol, to a unified data layer. Supporting 50+ industrial protocols — including OPC-UA, Modbus, MQTT, Fanuc, Siemens, and Mitsubishi — it captures over 1 million data points per day from CNC machines, PLCs, sensors, and energy meters. The platform enables real-time OEE monitoring, predictive maintenance, energy management, and environmental tracking, delivering an average 15% OEE improvement and 40% reduction in unplanned downtime for Thai factories.
        </p>
      </div>    </div>`;

  return base.wrapInDiviSection('Section', html, 'Section: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === SECTION (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .dw-section{...;${base.fontSmoothingReset(P)}font-size:16px} */


/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-section--blue::before{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:radial-gradient(ellipse at 20% 30%, rgba(255,255,255,0.15) 0%, transparent 50%);pointer-events:none} */
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
