/**
 * aiot-metrics.js — Metrics Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: aiot.html line 1487
 *
 * Original classes: metrics-section, metrics-header, metrics-grid, metric-card, metric-value (+1 more)
 */

const base = require('../../lib/templates/_base');
const statsBanner = require('../../lib/templates/stats-banner');

const P = 'met'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="metrics-section" data-particles="bold">
    <div class="metrics-header" style="position:relative;z-index:2;">
                <h2>Measured Impact</h2>
                <p>What our customers achieve with AIoT implementation</p>
            </div>
            <div class="metrics-grid" style="position:relative;z-index:2;">
                <div class="metric-card">
                    <div class="metric-value">+15%</div>
                    <div class="metric-label">OEE Improvement</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">-40%</div>
                    <div class="metric-label">Unplanned Downtime</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">-12%</div>
                    <div class="metric-label">Energy Costs</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">100%</div>
                    <div class="metric-label">Data Accuracy</div>
                </div>
            </div>
    ${statsBanner.DEFAULT_PARTICLE_SCRIPT}
    </div>
    `;

  return base.wrapInDiviSection('Metrics', html, 'Metrics: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === METRICS (S6) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .metrics-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.metrics-section {
            padding: 100px 0;
            background: linear-gradient(135deg, #000864 0%, #000432 100%);
        }
.metrics-header {
            text-align: center;
            max-width: 700px;
            margin: 0 auto 60px;
            padding: 0 24px;
        }
.metrics-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 36px;
            color: #fff;
            margin-bottom: 16px;
        }
.metrics-header p {
            font-size: 18px;
            color: rgba(255,255,255,0.75);
        }
.metrics-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 24px;
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }
.metric-card {
            background: rgba(255,255,255,0.05);
            border: 1px solid rgba(255,255,255,0.1);
            border-radius: 16px;
            padding: 32px 24px;
            text-align: center;
        }
.metric-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 48px;
            font-weight: 700;
            color: #00AFF0;
            line-height: 1;
        }
.metric-label {
            font-size: 15px;
            color: rgba(255,255,255,0.8);
            margin-top: 12px;
            line-height: 1.4;
        }
@media (max-width: 1024px) {
            .metrics-grid { grid-template-columns: repeat(2, 1fr); }
        }
@media (max-width: 640px) {
            .metrics-grid { grid-template-columns: 1fr; }
        }
/* Divi overrides */
.et_pb_section .metrics-header h2{font-weight:700 !important;line-height:1.3 !important;font-size:36px !important;color:#fff !important}
.et_pb_section .metrics-header p{font-weight:400 !important;padding-bottom:0 !important}
.et_pb_section .metric-value{font-weight:700 !important;font-size:48px !important;line-height:1 !important}
.et_pb_section .metric-label{padding-bottom:0 !important;line-height:1.4 !important}
`.trim();
}

module.exports = { blocks, css };
