/**
 * automotive-stakes.js — Stakes Section (S3)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: automotive.html line 443
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 15 base, 2 hover, 0 pseudo, 0 hidden
 * Original classes: stakes-section, dw-section-scene, stakes-inner, stakes-header, stakes-grid (+2 more)
 */

const base = require('../../lib/templates/_base');

const P = 'stakes'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="stakes-section">
    <div class="dw-section-scene">
                <svg aria-hidden="true" viewBox="0 0 1400 900" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice">
                    <line x1="0" y1="450" x2="1400" y2="450" stroke="#000864" stroke-width="1.5" opacity="0.1"/>
                    <rect x="100" y="400" width="90" height="100" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <text x="145" y="460" font-family="'Noto Sans',sans-serif" font-size="8" font-weight="600" fill="#000864" opacity="0.1" text-anchor="middle">STAMP</text>
                    <path d="M190 450 L320 450" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="315,445 330,450 315,455" fill="#000864" opacity="0.12"/>
                    <rect x="330" y="400" width="90" height="100" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <text x="375" y="460" font-family="'Noto Sans',sans-serif" font-size="8" font-weight="600" fill="#000864" opacity="0.1" text-anchor="middle">WELD</text>
                    <path d="M420 450 L550 450" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="545,445 560,450 545,455" fill="#000864" opacity="0.12"/>
                    <rect x="560" y="400" width="90" height="100" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <text x="605" y="460" font-family="'Noto Sans',sans-serif" font-size="8" font-weight="600" fill="#000864" opacity="0.1" text-anchor="middle">PAINT</text>
                    <path d="M650 450 L780 450" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="775,445 790,450 775,455" fill="#000864" opacity="0.12"/>
                    <rect x="790" y="400" width="90" height="100" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <text x="835" y="460" font-family="'Noto Sans',sans-serif" font-size="8" font-weight="600" fill="#000864" opacity="0.1" text-anchor="middle">ASSEM</text>
                    <path d="M880 450 L1010 450" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="1005,445 1020,450 1005,455" fill="#000864" opacity="0.12"/>
                    <rect x="1020" y="400" width="90" height="100" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.15"/>
                    <text x="1065" y="460" font-family="'Noto Sans',sans-serif" font-size="8" font-weight="600" fill="#000864" opacity="0.1" text-anchor="middle">QC</text>
                    <text x="1200" y="300" font-family="'Noto Sans',sans-serif" font-size="16" font-weight="700" fill="#00AFF0" opacity="0.1">JIT</text>
                    <rect x="1150" y="310" width="120" height="40" rx="4" stroke="#00AFF0" stroke-width="1.5" fill="none" opacity="0.1"/>
                    <text x="1210" y="335" font-family="'Noto Sans',sans-serif" font-size="9" font-weight="600" fill="#00AFF0" opacity="0.08" text-anchor="middle">EDI LINK</text>
                    <circle cx="300" cy="250" r="3" fill="#000864" opacity="0.08"/>
                    <circle cx="700" cy="650" r="4" fill="#00AFF0" opacity="0.08"/>
                    <circle cx="1100" cy="700" r="3" fill="#000864" opacity="0.06"/>
                </svg>
            </div>
            <div class="stakes-inner" style="position: relative; z-index: 2;">
                <div class="stakes-header">
                    <h2>The Automotive Stakes Are High</h2>
                    <p>In automotive, there's no room for "good enough"</p>
                </div>
                <div class="stakes-grid">
                    <div class="stake-card">
                        <div class="stake-icon">
                            <svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                        </div>
                        <h3>JIT or Else</h3>
                        <p>Miss one delivery window and the OEM stops the line. The penalty isn't a warning—it's the cost of that downtime, plus losing the contract entirely.</p>
                    </div>
                    <div class="stake-card">
                        <div class="stake-icon">
                            <svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
                        </div>
                        <h3>Trace or Lose</h3>
                        <p>A quality issue surfaces. OEM asks: which lot? Which raw materials? Which operator? If you can't answer in hours, you're not a tier-1 supplier anymore.</p>
                    </div>
                    <div class="stake-card">
                        <div class="stake-icon">
                            <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1" ry="1"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="9" y1="16" x2="15" y2="16"/></svg>
                        </div>
                        <h3>Audit Anxiety</h3>
                        <p>IATF 16949. Customer audits quarterly. Documentation requirements that keep growing. Manual systems simply can't keep up.</p>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Stakes', html, 'Stakes: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === STAKES (S3) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */


/* TODO: HOVER STATES using global classes (port manually) */
/* .stake-card:hover .stake-icon, .challenge-card:hover .challenge-icon{background:linear-gradient(135deg, #00AFF0, #003CC8)} */
/* .stake-card:hover .stake-icon svg, .challenge-card:hover .challenge-icon svg{stroke:#fff} */
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-section-scene{position:absolute;inset:0;pointer-events:none;z-index:1;overflow:hidden} */
/* .dw-section-scene svg{width:100%;height:100%;opacity:0.20} */
.stakes-section, .challenges-section{padding:100px 0;background:#F5F7FA}
.stakes-inner, .challenges-inner{max-width:1100px;margin:0 auto;padding:0 24px}
.stakes-header, .challenges-header{text-align:center;margin-bottom:60px}
.stakes-header h2, .challenges-header h2{font-family:'Noto Sans', sans-serif;font-size:36px;color:#000864;margin-bottom:16px}
.stakes-header p, .challenges-header p{font-size:18px;color:#5b6b80}
.stakes-grid, .challenges-grid{display:grid;grid-template-columns:repeat(3, 1fr);gap:32px}
/* .stake-card, .challenge-card{background:linear-gradient(145deg, #fef2f2 0%, #fee2e2 100%);border:1px solid #fecaca;border-radius:20px;padding:40px 32px;text-align:center} */
/* .stake-icon, .challenge-icon{width:72px;height:72px;background:linear-gradient(135deg, #fee2e2, #fecaca);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 24px;transition:all 0.4s ease} */
/* .stake-icon svg, .challenge-icon svg{width:32px;height:32px;stroke:#b91c1c;stroke-width:1.5;fill:none} */
/* .stake-card h3, .challenge-card h3{font-family:'Noto Sans', sans-serif;font-size:22px;color:#991b1b;margin-bottom:16px} */
/* .stake-card p, .challenge-card p{font-size:15px;color:#b91c1c;line-height:1.7} */
@media (max-width:1024px){.auto-hero h1, .elec-hero h1, .metal-hero h1{font-size:40px}.auto-hero-stats, .elec-hero-stats, .metal-hero-stats{gap:40px}.stakes-grid, .challenges-grid{grid-template-columns:1fr}.solutions-grid{grid-template-columns:1fr}.products-grid{grid-template-columns:1fr}}
/* @media (max-width:640px){.auto-hero, .elec-hero, .metal-hero{padding:120px 0 80px}.auto-hero h1, .elec-hero h1, .metal-hero h1{font-size:32px}.auto-hero-subtitle, .elec-hero-subtitle, .metal-hero-subtitle{font-size:17px}.auto-hero-stats, .elec-hero-stats, .metal-hero-stats{flex-direction:column;gap:24px}.auto-hero-stat-value, .elec-hero-stat-value, .metal-hero-stat-value{font-size:36px}.stake-card, .challenge-card{padding:32px 24px}.solution-card{padding:32px}.cta-section h2{font-size:28px}.cta-buttons{flex-direction:column}} */

\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
