/**
 * automotive-context.js — Context Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: automotive.html line 435
 *
 * styles.css: 5 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: context-section, context-inner
 */

const base = require('../../lib/templates/_base');

const P = 'con'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="context-section">
    <div class="context-inner">
                <h2>Thailand: ASEAN's Detroit</h2>
                <p>Thailand produces <strong>1.9 million vehicles annually</strong>, making it the largest automotive manufacturing hub in Southeast Asia. Behind every vehicle are <strong>2,500+ tier 1-3 suppliers</strong> facing relentless demands: perfect quality, complete traceability, and JIT delivery windows measured in hours, not days. DigiWin has spent 20+ years helping these suppliers meet—and exceed—OEM expectations.</p>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Context', html, 'Context: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CONTEXT (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .context-section{...;${base.fontSmoothingReset(P)}font-size:16px} */


.context-section{padding:100px 0;background:#fff}
.context-inner{max-width:900px;margin:0 auto;padding:0 24px;text-align:center}
.context-inner h2{font-family:'Noto Sans', sans-serif;font-size:36px;color:#000864;margin-bottom:24px}
.context-inner p{font-size:18px;color:#5b6b80;line-height:1.8}
.context-inner p strong{color:#000864}


`.trim();
}

module.exports = { blocks, css };
