/**
 * blog-library.js — Library Section (S4)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: blog.html line 651
 *
 * styles.css: 36 base, 3 hover, 0 pseudo, 0 hidden
 * Original classes: library-section, dw-d-bg, dw-d-bg--corner-tl, library-inner, library-header (+15 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'lib'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="${P}-section" data-particles>
    <div class="dw-d-bg dw-d-bg--corner-tl" style="opacity: 0.06;"></div>
            <div class="${P}-inner" style="position: relative; z-index: 2;">
                <div class="${P}-header">
                    <span class="blog-hub-label">Deep Dive Library</span>
                    <h2>Structured Knowledge by Topic</h2>
                </div>
    
                <div class="${P}-groups">
                    
                    <div class="${P}-group">
                        <div class="${P}-group-header">
                            <div class="${P}-group-indicator ${P}-group-indicator--boi"></div>
                            <h3>BOI & Compliance</h3>
                        </div>
                        <a href="/blog/boi-compliance-jin-hai/" class="${P}-item">
                            <span class="${P}-item-title">How One Factory Saved 10M THB/Year in BOI Supplementary Taxes</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">8 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                    </div>
    
                    
                    <div class="${P}-group">
                        <div class="${P}-group-header">
                            <div class="${P}-group-indicator ${P}-group-indicator--production"></div>
                            <h3>Production Planning</h3>
                        </div>
                        <a href="/blog/lrp-vs-mrp/" class="${P}-item">
                            <span class="${P}-item-title">LRP vs MRP: Why Your Production Planning Takes Hours Instead of Minutes</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">6 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                        <a href="/blog/feature-codes/" class="${P}-item">
                            <span class="${P}-item-title">Feature Codes: How to Turn 27 SKUs Into 1 Product</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">6 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                        <a href="/blog/amrp-capacity-planning/" class="${P}-item">
                            <span class="${P}-item-title">AMRP: Why You Don't Need a Separate APS System</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">5 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                    </div>
    
                    
                    <div class="${P}-group">
                        <div class="${P}-group-header">
                            <div class="${P}-group-indicator ${P}-group-indicator--cost"></div>
                            <h3>Cost Management</h3>
                        </div>
                        <a href="/blog/co-product-cost-accounting/" class="${P}-item">
                            <span class="${P}-item-title">Co-Product Cost Accounting: The Problem Most ERPs Cannot Solve</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">7 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                        <a href="/blog/dual-units/" class="${P}-item">
                            <span class="${P}-item-title">Dual Units: Why Your ERP Should Show Both Kilograms AND Pieces</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">5 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                    </div>
    
                    
                    <div class="${P}-group">
                        <div class="${P}-group-header">
                            <div class="${P}-group-indicator ${P}-group-indicator--smart"></div>
                            <h3>Smart Factory</h3>
                        </div>
                        <a href="/blog/shop-floor-scheduling/" class="${P}-item">
                            <span class="${P}-item-title">Shop Floor Mini-Scheduling: When Plans Meet Reality</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">5 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                        <a href="/blog/production-transparency/" class="${P}-item">
                            <span class="${P}-item-title">From Paper Reports to Production Transparency: A Practical Guide</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">6 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                    </div>
    
                    
                    <div class="${P}-group">
                        <div class="${P}-group-header">
                            <div class="${P}-group-indicator ${P}-group-indicator--industry"></div>
                            <h3>Industry Insights</h3>
                        </div>
                        <a href="/blog/five-pain-points/" class="${P}-item">
                            <span class="${P}-item-title">The 5 Universal Pain Points Every Thai Factory Owner Faces</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">5 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                        <a href="/blog/sap-ecc-end-of-life/" class="${P}-item">
                            <span class="${P}-item-title">SAP ECC End-of-Life 2027: What Thai Manufacturers Need to Know</span>
                            <div class="${P}-item-meta">
                                <span class="${P}-item-time">5 min</span>
                                <span class="${P}-item-arrow">&rarr;</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
    </div>
    ${base.particleOceanScript()}`;

  return base.wrapInDiviSection('Library', html, 'Library: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === LIBRARY (S4) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}


/* === HOVER STATES (auto-ported from styles.css) === */
.${P}-item:hover{padding-left:8px}
.${P}-item:hover .${P}-item-title{color:var(--dw-blue-text)}
.${P}-item:hover .${P}-item-arrow{opacity:1}
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .blog-hub-label{font-family:'JetBrains Mono', monospace;font-size:11px;font-weight:500;color:rgb(3, 105, 161) !important;text-transform:uppercase;letter-spacing:0.15em;margin-bottom:32px;display:block} */
/* .library-section{padding:100px 0;background:#ffffff} */
/* .library-inner{max-width:1200px;margin:0 auto;padding:0 24px} */
/* .library-header{text-align:center;margin-bottom:56px} */
/* .library-header h2{font-family:'Noto Sans', sans-serif;font-size:40px;font-weight:700;color:#000864;margin:8px 0 0 0;letter-spacing:-0.02em} */
/* .library-groups{display:grid;grid-template-columns:repeat(2, 1fr);gap:32px} */
/* .library-group{background:#F5F7FA;border-radius:16px;padding:32px;border:1px solid #e8eef3} */
/* .library-group-header{display:flex;align-items:center;gap:12px;padding-bottom:20px;margin-bottom:20px;border-bottom:2px solid #e8eef3} */
/* .library-group-indicator{width:4px;height:32px;border-radius:2px} */
/* .library-group-indicator--boi{background:#DC2626} */
/* .library-group-indicator--production{background:#00AFF0} */
/* .library-group-indicator--cost{background:#02D28C} */
/* .library-group-indicator--smart{background:#644CE6} */
/* .library-group-indicator--industry{background:#FFD700} */
/* .library-group-header h3{font-family:'Noto Sans', sans-serif;font-size:18px;font-weight:600;color:#000864;margin:0} */
/* .library-item{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-bottom:1px solid #e8eef3;text-decoration:none;transition:all 0.3s ease} */
/* .library-item:last-child{border-bottom:none;padding-bottom:0} */
/* .library-item-title{font-family:'Noto Sans', sans-serif;font-size:15px;font-weight:500;color:#333333;transition:color 0.3s ease;flex:1;margin-right:16px} */
/* .library-item-meta{display:flex;align-items:center;gap:12px;flex-shrink:0} */
/* .library-item-time{font-family:'Noto Sans', sans-serif;font-size:13px;color:#666666;white-space:nowrap} */
/* .library-item-arrow{font-size:16px;color:var(--dw-blue-text);opacity:0;transition:opacity 0.3s ease} */
/* @media (max-width:1024px){.library-groups{grid-template-columns:1fr}} */
/* @media (max-width:640px){.articles-header h2,.library-header h2{font-size:28px}.library-group{padding:24px}} */
${superD.css('dw-d-bg', { variant: 'outline', position: 'corner-tl' })}

${base.reducedMotion('*{animation:none !important;transition:none !important}')}

/* Divi section-level overrides */
.et_pb_section:has(.${P}-inner) {
  background: #ffffff !important; padding: 0 !important; min-height: auto !important;
  margin-top: 0 !important; margin-bottom: 0 !important; text-align: start !important;
}
.${P}-section {
  padding: 100px 24px !important; position: relative !important; overflow: hidden !important;
}
.${P}-section canvas {
  position: absolute !important; top: 0 !important; left: 0 !important;
  width: 100% !important; height: 100% !important; pointer-events: none !important; z-index: 1 !important;
}
.et_pb_section:has(.${P}-inner) .et_pb_row {
  max-width: 100% !important; width: 100% !important; padding: 0 !important; margin: 0 auto !important;
}
.et_pb_section:has(.${P}-inner) .et_pb_column { padding: 0 !important; }
.et_pb_section .${P}-inner {
  max-width: 1200px !important; margin: 0 auto !important; padding: 0 24px !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-header { text-align: center !important; margin-bottom: 56px !important; }
.et_pb_section .${P}-header h2 {
  font-family: 'Noto Sans', sans-serif !important; font-size: 40px !important;
  font-weight: 700 !important; color: #000864 !important; margin: 8px 0 0 !important;
  letter-spacing: -0.02em !important; line-height: 64px !important; padding: 0 !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .blog-hub-label {
  font-family: 'JetBrains Mono', monospace !important; font-size: 11px !important;
  font-weight: 500 !important; color: #0369a1 !important; text-transform: uppercase !important;
  letter-spacing: 0.15em !important; margin-bottom: 32px !important; display: block !important;
  line-height: 17.6px !important; -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-groups {
  display: grid !important; grid-template-columns: repeat(2, 1fr) !important; gap: 32px !important;
}
.et_pb_section .${P}-group {
  background: #F5F7FA !important; border-radius: 16px !important; padding: 32px !important;
  border: 1px solid #e8eef3 !important;
}
.et_pb_section .${P}-group-header {
  display: flex !important; align-items: center !important; gap: 12px !important;
  padding-bottom: 20px !important; margin-bottom: 20px !important;
  border-bottom: 2px solid #e8eef3 !important;
}
.et_pb_section .${P}-group-indicator {
  width: 4px !important; height: 32px !important; border-radius: 2px !important;
}
.et_pb_section .${P}-group-indicator--boi { background: #DC2626 !important; }
.et_pb_section .${P}-group-indicator--production { background: #00AFF0 !important; }
.et_pb_section .${P}-group-indicator--cost { background: #02D28C !important; }
.et_pb_section .${P}-group-indicator--smart { background: #644CE6 !important; }
.et_pb_section .${P}-group-indicator--industry { background: #FFD700 !important; }
.et_pb_section .${P}-group-header h3 {
  font-family: 'Noto Sans', sans-serif !important; font-size: 18px !important;
  font-weight: 600 !important; color: #000864 !important; margin: 0 !important;
  padding: 0 !important; -webkit-font-smoothing: auto !important;
  line-height: 28.8px !important; text-align: start !important;
}
.et_pb_section .${P}-item {
  display: flex !important; align-items: center !important; justify-content: space-between !important;
  padding: 14px 0 !important; border-bottom: 1px solid #e8eef3 !important;
  text-decoration: none !important; line-height: 25.6px !important;
  -webkit-font-smoothing: auto !important; color: #333 !important; text-align: start !important;
}
.et_pb_section .${P}-item:last-child { border-bottom: none !important; padding-bottom: 0 !important; }
.et_pb_section .${P}-item-title {
  font-size: 15px !important; font-weight: 500 !important; color: #333 !important;
  flex: 1 !important; margin-right: 16px !important;
  -webkit-font-smoothing: auto !important; line-height: 24px !important; text-align: start !important;
}
.et_pb_section .${P}-item-meta {
  display: flex !important; align-items: center !important; gap: 12px !important; flex-shrink: 0 !important;
}
.et_pb_section .${P}-item-time {
  font-size: 13px !important; color: #666 !important; white-space: nowrap !important;
  line-height: 20.8px !important; -webkit-font-smoothing: auto !important; text-align: start !important;
}
.et_pb_section .${P}-item-arrow {
  font-size: 16px !important; color: #0369a1 !important; opacity: 0 !important;
  line-height: 25.6px !important; -webkit-font-smoothing: auto !important; text-align: start !important;
}
.et_pb_section .dw-d-bg {
  position: absolute !important; pointer-events: none !important; z-index: 0 !important;
  left: -5% !important; top: -5% !important; right: auto !important; bottom: auto !important;
  width: 30% !important; min-height: 30vh !important;
  background-size: contain !important; background-repeat: no-repeat !important;
  background-position: center left !important;
  background-image: url("data:image/svg+xml;base64,${superD.getSvgBase64('outline')}") !important;
  transform: none !important;
}
`.trim();
}

module.exports = { blocks, css };
