/**
 * blog-hub-cta.js — Hub Cta Section (S5)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: blog.html line 777
 *
 * styles.css: 22 base, 2 hover, 2 pseudo, 1 hidden
 * Original classes: blog-hub-cta, dw-d-bg, dw-d-bg--left, dw-wave-flow, blog-hub-cta-inner (+3 more)
 */

// TEMPLATE HINT: matches "cta-gradient". See home-cta.js for example.
const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'hubc'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-d-bg dw-d-bg--left" style="opacity: 0.10;"></div>
            
            <div class="dw-wave-flow" style="height: 140px; opacity: 0.25; z-index: 1;"></div>
            <div class="${P}-cta-inner" style="position: relative; z-index: 2;">
                <h2>Have a Manufacturing Challenge?</h2>
                <p>Our team has helped 100+ Thai factories solve production, compliance, and cost challenges. Let's talk about yours.</p>
                <div class="${P}-cta-buttons">
                    <a href="demo.html" class="${P}-btn-white">Let's Talk</a>
                    <a href="products.html" class="${P}-btn-outline">Explore Products</a>
                </div>
            </div>`;

  return base.wrapInDiviSection('Hub Cta', html, 'Hub Cta: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HUB CTA (S5) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}


/* === HOVER STATES (auto-ported from styles.css) === */
.${P}-btn-white:hover{transform:translateY(-2px);box-shadow:0 8px 32px rgba(0, 0, 0, 0.2)}
.${P}-btn-outline:hover{border-color:#fff;background:rgba(255, 255, 255, 0.1)}
/* === PSEUDO-ELEMENTS (auto-ported from styles.css) === */
.${P}-cta::before{content:'';position:absolute;inset:0;background-image:url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Ccircle cx='30' cy='30' r='1.5'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");pointer-events:none}
.${P}-cta::after{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:radial-gradient(ellipse at 50% 50%, rgba(0, 175, 240, 0.1) 0%, transparent 60%);pointer-events:none}
/* WARNING: HIDDEN in styles.css (display:none) — DO NOT include in builder HTML */
/* .dw-wave-flow,
 * .dw-wave-flow--top {
 *     display: none;
 * } */
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-wave-flow--top{bottom:auto;top:0;transform:scaleY(-1)} */
/* .blog-hub-cta{padding:120px 0;background:linear-gradient(135deg, #000432 0%, #000864 50%, #001080 100%);position:relative;overflow:hidden;text-align:center} */
/* .blog-hub-cta-inner{max-width:700px;margin:0 auto;padding:0 24px;position:relative;z-index:1} */
/* .blog-hub-cta h2{font-family:'Noto Sans', sans-serif;font-size:clamp(32px, 4vw, 44px);font-weight:700;color:#fff;margin:0 0 20px 0;line-height:1.15;letter-spacing:-0.02em} */
/* .blog-hub-cta p{font-family:'Noto Sans', sans-serif;font-size:18px;color:rgba(255, 255, 255, 0.8);line-height:1.6;margin:0 0 40px 0} */
/* .blog-hub-cta-buttons{display:flex;justify-content:center;gap:16px;flex-wrap:wrap} */
/* .blog-hub-btn-white{background:#fff;color:#000864;padding:16px 36px;border-radius:12px;font-family:'Noto Sans', sans-serif;font-weight:600;font-size:16px;text-decoration:none;transition:all 0.3s ease;box-shadow:0 4px 16px rgba(0, 0, 0, 0.15)} */
/* .blog-hub-btn-outline{background:transparent;color:#fff;padding:16px 36px;border:2px solid rgba(255, 255, 255, 0.4);border-radius:12px;font-family:'Noto Sans', sans-serif;font-weight:600;font-size:16px;text-decoration:none;transition:all 0.3s ease} */
/* @media (max-width:640px){.blog-hub-cta h2{font-size:28px}.blog-hub-cta-buttons{flex-direction:column}.blog-hub-btn-white,.blog-hub-btn-outline{width:100%;text-align:center}} */
${superD.css('dw-d-bg', { variant: 'outline', position: 'left' })}

${base.reducedMotion('*{animation:none !important;transition:none !important}')}

/* Divi section-level overrides */
.et_pb_section:has(.${P}-cta-inner) {
  background: linear-gradient(135deg, #000432 0%, #000864 50%, #001080 100%) !important;
  padding: 120px 24px !important;
  position: relative !important; overflow: hidden !important; text-align: center !important;
  min-height: auto !important;
  margin-top: 0 !important; margin-bottom: 0 !important;
}
.et_pb_section:has(.${P}-cta-inner)::before {
  content: '' !important; position: absolute !important; inset: 0 !important;
  background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Ccircle cx='30' cy='30' r='1.5'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E") !important;
  pointer-events: none !important;
}
.et_pb_section:has(.${P}-cta-inner)::after {
  content: '' !important; position: absolute !important; inset: 0 !important;
  background: radial-gradient(ellipse at 50% 50%, rgba(0,175,240,0.1) 0%, transparent 60%) !important;
  pointer-events: none !important;
}
.et_pb_section:has(.${P}-cta-inner) .et_pb_row {
  max-width: 100% !important; width: 100% !important; padding: 0 !important; margin: 0 auto !important;
}
.et_pb_section:has(.${P}-cta-inner) .et_pb_column { padding: 0 !important; }
.et_pb_section .${P}-cta-inner {
  max-width: 700px !important; margin: 0 auto !important; padding: 0 24px !important;
  position: relative !important; z-index: 1 !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-cta-inner h2 {
  font-family: 'Noto Sans', sans-serif !important; font-size: 44px !important;
  font-weight: 700 !important; color: #fff !important; margin: 0 0 20px !important;
  line-height: 1.15 !important; letter-spacing: -0.02em !important; padding: 0 !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-cta-inner p {
  font-size: 18px !important; color: rgba(255,255,255,0.8) !important;
  line-height: 1.6 !important; margin: 0 0 40px !important; padding-bottom: 0 !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-cta-buttons {
  display: flex !important; justify-content: center !important; gap: 16px !important; flex-wrap: wrap !important;
}
.et_pb_section .${P}-btn-white {
  background: #fff !important; color: #000864 !important;
  padding: 16px 36px !important; border-radius: 12px !important;
  font-family: 'Noto Sans', sans-serif !important; font-weight: 600 !important;
  font-size: 16px !important; text-decoration: none !important; line-height: 25.6px !important;
  box-shadow: 0 4px 16px rgba(0,0,0,0.15) !important;
  -webkit-font-smoothing: auto !important;
}
.et_pb_section .${P}-btn-outline {
  background: transparent !important; color: #fff !important;
  padding: 16px 36px !important; border: 2px solid rgba(255,255,255,0.4) !important;
  border-radius: 12px !important; font-family: 'Noto Sans', sans-serif !important;
  font-weight: 600 !important; font-size: 16px !important; text-decoration: none !important;
  line-height: 25.6px !important; -webkit-font-smoothing: auto !important;
}
.et_pb_section .dw-d-bg {
  position: absolute !important; pointer-events: none !important; z-index: 0 !important;
  left: -15% !important; top: 50% !important; right: auto !important;
  width: 60% !important; min-height: 60vh !important;
  background-size: contain !important; background-repeat: no-repeat !important;
  background-position: center left !important;
  background-image: url("data:image/svg+xml;base64,${superD.getSvgBase64('outline')}") !important;
  transform: translateY(-50%) !important;
}
.et_pb_section .dw-wave-flow { display: none !important; }
`.trim();
}

module.exports = { blocks, css };
