/**
 * electronics-context.js — Context Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: electronics.html line 435
 *
 * styles.css: 9 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: context-section, fade-in, context-inner
 */

const base = require('../../lib/templates/_base');

const P = 'con'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="context-section">
    <div class="context-inner">
                <h2>Thailand's Electronics Ecosystem</h2>
                <p>Thailand exports <strong>\$40+ billion in electronics annually</strong>, from hard disk drives to automotive electronics to consumer devices. Electronics manufacturers face unique complexity: <strong>hundreds of unique parts per product</strong>, constant changeovers for high-mix production, and moisture-sensitive components that require precise handling. DigiWin's MES was built specifically for this challenge.</p>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Context', html, 'Context: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CONTEXT (S2) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */


/* REF: BASE RULES from styles.css (check against inline CSS above) */
.fade-in{opacity:1;transform:none}
.fade-in.visible{opacity:1;transform:translateY(0)}
.fade-in.no-delay{opacity:1;transform:none;transition:none}
@media (prefers-reduced-motion:reduce){.fade-in{opacity:1;transform:none;transition:none}}
.context-section{padding:100px 0;background:#fff}
.context-inner{max-width:900px;margin:0 auto;padding:0 24px;text-align:center}
.context-inner h2{font-family:'Noto Sans', sans-serif;font-size:36px;color:#000864;margin-bottom:24px}
.context-inner p{font-size:18px;color:#5b6b80;line-height:1.8}
.context-inner p strong{color:#000864}

\${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
