/**
 * electronics-fade-in.js — Fade In Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: electronics.html line 662
 *
 * styles.css: 4 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: fade-in
 */

const base = require('../../lib/templates/_base');

const P = 'fadi'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="fade-in">
    <div style="max-width: 800px; margin: 0 auto; padding: 0 24px;">
                <div style="background: linear-gradient(135deg, rgba(0,175,240,0.04), rgba(0,8,100,0.04)); border: 1px solid rgba(0,175,240,0.2); border-left: 4px solid #00AFF0; border-radius: 12px; padding: 40px 40px 36px;">
                    <span style="font-family: 'JetBrains Mono', monospace; font-size: 11px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.1em; color: #00AFF0; display: block; margin-bottom: 8px;">DigiWin in Thai Electronics</span>
                    <h3 style="font-family: 'Noto Sans', sans-serif; font-size: 24px; font-weight: 700; color: #000864; margin: 0 0 16px;">Hoo Chin Electronics (Thailand)</h3>
                    <p style="font-family: 'Noto Sans', sans-serif; font-size: 16px; line-height: 1.7; color: #333; margin: 0 0 20px;">Hoo Chin Electronics, a Thai electronics manufacturer and one of DigiWin's local clients, chose DigiWin ERP to manage the complexity of high-mix production, BOI compliance, and multi-material component tracking — the same challenges your factory faces every day.</p>
                    <p style="font-family: 'Noto Sans', sans-serif; font-size: 14px; line-height: 1.6; color: #666; margin: 0;">This is not just an Asia-wide reference. Hoo Chin operates in Thailand, navigates Thai regulations, and works with Thai supply chains — proof that DigiWin delivers results in your market.</p>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Fade In', html, 'Fade In: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === FADE IN / CASE STUDY CALLOUT (S6) === */
.fade-in{opacity:1;transform:none;padding:60px 0;${base.fontSmoothingReset('fadi')}font-size:16px}
/* Divi overrides for inline-styled elements */
.et_pb_section .fade-in h3{line-height:38.4px !important;margin-bottom:16px !important}
.et_pb_section .fade-in p{line-height:27.2px !important;padding-bottom:0 !important}
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
