/**
 * erp-pain.js — Pain Section (S3)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: erp.html line 1738
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 9 base, 3 hover, 0 pseudo, 0 hidden
 * Original classes: pain-section, pain-inner, pain-header, pain-label, pain-title (+12 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'pain'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="pain-section">
    <div class="pain-inner">
                <div class="pain-header">
                    <p class="pain-label">Sound Familiar?</p>
                    <h2 class="pain-title">Manufacturing Challenges, Solved</h2>
                    <p class="pain-subtitle">Generic ERP wasn't built for factories. These problems disappear when your system understands manufacturing.</p>
                </div>
    
                <div class="pain-grid">
                    <div class="pain-card">
                        <div class="pain-card-icon">
                            
                            <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg>
                        </div>
                        <div class="pain-card-problem">
                            <p class="pain-card-label problem">The Problem</p>
                            <h3 class="pain-card-title">"We don't know our true costs until month-end"</h3>
                            <p class="pain-card-desc">Standard cost variance buried in accounting entries. Material waste discovered weeks after production. No visibility into real-time margin.</p>
                        </div>
                        <div class="pain-card-solution">
                            <p class="pain-card-label solution">DigiWin Solution</p>
                            <h4 class="pain-card-solution-title">Real-Time Cost Visibility</h4>
                            <p class="pain-card-desc">Actual cost calculated at each production stage. Margin visibility before you ship, not after you invoice.</p>
                        </div>
                    </div>
    
                    <div class="pain-card">
                        <div class="pain-card-icon">
                            
                            <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
                        </div>
                        <div class="pain-card-problem">
                            <p class="pain-card-label problem">The Problem</p>
                            <h3 class="pain-card-title">"MRP gives us garbage because our BOMs are outdated"</h3>
                            <p class="pain-card-desc">Engineering changes happen on the floor, not in the system. BOM versions scattered across spreadsheets.</p>
                        </div>
                        <div class="pain-card-solution">
                            <p class="pain-card-label solution">DigiWin Solution</p>
                            <h4 class="pain-card-solution-title">Engineering Change Control</h4>
                            <p class="pain-card-desc">Engineering Change Notice (ECN) workflow ensures changes are captured before production. MRP always runs against current, approved BOMs.</p>
                        </div>
                    </div>
    
                    <div class="pain-card">
                        <div class="pain-card-icon">
                            
                            <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>
                        </div>
                        <div class="pain-card-problem">
                            <p class="pain-card-label problem">The Problem</p>
                            <h3 class="pain-card-title">"Inventory count never matches the system"</h3>
                            <p class="pain-card-desc">Ghost inventory haunts every audit. Production consumes materials that don't exist. Purchasing reorders what you already have.</p>
                        </div>
                        <div class="pain-card-solution">
                            <p class="pain-card-label solution">DigiWin Solution</p>
                            <h4 class="pain-card-solution-title">Transaction-Level Accuracy</h4>
                            <p class="pain-card-desc">Every material movement captured at source. Barcode scanning enforced at key points. Cycle counting built in.</p>
                        </div>
                    </div>
    
                    <div class="pain-card">
                        <div class="pain-card-icon">
                            
                            <svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><path d="M11 8v6M8 11h6"/></svg>
                        </div>
                        <div class="pain-card-problem">
                            <p class="pain-card-label problem">The Problem</p>
                            <h3 class="pain-card-title">"We can't trace quality issues back to their source"</h3>
                            <p class="pain-card-desc">Customer complaints trigger panic investigations. Lot numbers exist somewhere, maybe. Root cause analysis takes weeks.</p>
                        </div>
                        <div class="pain-card-solution">
                            <p class="pain-card-label solution">DigiWin Solution</p>
                            <h4 class="pain-card-solution-title">Complete Traceability</h4>
                            <p class="pain-card-desc">Lot tracking from receiving to shipping. One click shows full genealogy. Quality data linked to batches, machines, operators.</p>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Pain', html, 'Pain: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === PAIN (S3) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.pain-section {
            padding: 100px 0;
            background: #ffffff;
            -webkit-font-smoothing: auto;
        }
.pain-section p { padding-bottom: 0 !important; }
.pain-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
        }
.pain-header {
            text-align: center;
            margin-bottom: 64px;
        }
.pain-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            color: #DC2626;
            text-transform: uppercase;
            letter-spacing: 0.15em;
            margin-bottom: 16px;
        
            line-height: 17.6px;

            -webkit-font-smoothing: auto;
}
.pain-title {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin: 0 0 16px 0;
            letter-spacing: -0.02em;
            line-height: 64px;
            -webkit-font-smoothing: auto;
        }
.pain-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 18px;
            color: #5b6b80;
            max-width: 600px;
            margin: 0 auto;
        
            line-height: 28.8px;

            -webkit-font-smoothing: auto;
}
.pain-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 28px;
        }
.pain-card {
            background: #ffffff;
            border-radius: 20px;
            padding: 36px;
            border: 1px solid #e8eef3;
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.04);
            transition: all 0.4s ease;
            position: relative;
        }
.pain-card:hover {
            border-color: #0369a1;
            box-shadow: 0 12px 48px rgba(3, 105, 161, 0.12);
        }
.pain-card:hover .pain-card-icon {
            background: linear-gradient(135deg, #0369a1, #003CC8);
        }
.pain-card:hover .pain-card-icon svg {
            stroke: #ffffff;
        }
.pain-card-icon {
            width: 56px;
            height: 56px;
            background: linear-gradient(135deg, #fee2e2, #fecaca);
            border-radius: 14px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 20px;
            transition: all 0.4s ease;
        }
.pain-card-icon svg {
            width: 28px;
            height: 28px;
            stroke: #DC2626;
            stroke-width: 1.5;
            fill: none;
            transition: all 0.4s ease;
        }
.pain-card-problem {
            margin-bottom: 24px;
            padding-bottom: 24px;
            border-bottom: 1px dashed #e8eef3;
        }
.pain-card-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-bottom: 10px;
        
            line-height: 16px !important;

            -webkit-font-smoothing: auto !important;
}
.pain-card-label.problem { color: #DC2626; }
.pain-card-label.solution { color: rgb(4, 120, 87); }
.pain-card-title {
            font-family: 'Noto Sans', sans-serif;
            font-size: 18px;
            font-weight: 600;
            color: #000864;
            margin-bottom: 10px;
            line-height: 1.4;
        
            -webkit-font-smoothing: auto !important;
}
.pain-card-desc {
            font-family: 'Noto Sans', sans-serif;
            font-size: 15px;
            color: #5b6b80;
            line-height: 1.65;
        
            -webkit-font-smoothing: auto !important;
}
.pain-card-solution-title {
            font-family: 'Noto Sans', sans-serif;
            font-size: 16px;
            font-weight: 600;
            color: #000864;
            margin-bottom: 8px;
            line-height: 25.6px;
            -webkit-font-smoothing: auto !important;
}
@media (max-width: 1024px) {
            .erp-hero-inner {
                grid-template-columns: 1fr;
                text-align: center;
            }

            .erp-hero-content {
                max-width: 100%;
            }

            .erp-hero-stats {
                justify-content: center;
            }

            .erp-hero-visual {
                display: none;
            }

            .erp-hero-bg svg {
                opacity: 0.06;
                width: 80%;
                right: -20%;
            }

            .pain-grid, .products-comparison {
                grid-template-columns: 1fr;
                max-width: 600px;
                margin-left: auto;
                margin-right: auto;
            }

            .integration-visual {
                flex-direction: column;
            }

            .integration-node {
                width: auto;
                height: auto;
            }

            .integration-arrow {
                transform: rotate(90deg);
            }

            .boi-callout-grid {
                grid-template-columns: 1fr !important;
                text-align: center;
            }

            .boi-callout-grid > div:first-child {
                text-align: center;
            }

            .erpii-modules-grid {
                grid-template-columns: repeat(2, 1fr);
            }

            .erp-trust-callout {
                flex-direction: column;
            }
        }
@media (prefers-reduced-motion: reduce) {
            .erp-hero-content,
            .erp-hero::before,
            .erp-hero-badge::before,
            .erp-dashboard-mockup,
            .pain-card,
            .pain-card-icon,
            .product-card,
            .weapon-card,
            .challenge-icon,
            .integration-link,
            .erp-use-case-pill,
            .erp-erpii-accordion summary,
            .boi-enforcement-cta,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
        }

/* TODO: HOVER STATES using global classes (port manually) */
/* .solution-card:hover{border-color:#0369a1;box-shadow:0 12px 40px rgba(3, 105, 161, 0.12)} */
/* .solution-card:hover .solution-icon{background:linear-gradient(135deg, #0369a1, #003CC8)} */
/* .solution-card:hover .solution-icon svg{stroke:#fff} */
.solution-icon{width:64px;height:64px;background:linear-gradient(135deg, rgba(3, 105, 161, 0.15), rgba(3, 105, 161, 0.05));border-radius:16px;display:flex;align-items:center;justify-content:center;margin-bottom:24px;transition:all 0.4s ease}
.solution-icon svg{width:28px;height:28px;stroke:#0369a1;stroke-width:1.5;fill:none}
/* .solution-card h3{font-family:'Noto Sans', sans-serif;font-size:22px;color:#000864;margin-bottom:12px} */
/* .solution-card > p{font-size:15px;color:#5b6b80;line-height:1.7;margin-bottom:20px} */
/* .solution-features{display:flex;flex-direction:column;gap:10px} */
/* .solution-feature{display:flex;align-items:center;gap:10px;font-size:14px;color:#475569} */
.solution-feature svg{width:18px;height:18px;color:#0369a1;flex-shrink:0}
/* @media (max-width:640px){.auto-hero, .elec-hero, .metal-hero{padding:120px 0 80px}.auto-hero h1, .elec-hero h1, .metal-hero h1{font-size:32px}.auto-hero-subtitle, .elec-hero-subtitle, .metal-hero-subtitle{font-size:17px}.auto-hero-stats, .elec-hero-stats, .metal-hero-stats{flex-direction:column;gap:24px}.auto-hero-stat-value, .elec-hero-stat-value, .metal-hero-stat-value{font-size:36px}.stake-card, .challenge-card{padding:32px 24px}.solution-card{padding:32px}.cta-section h2{font-size:28px}.cta-buttons{flex-direction:column}} */

${base.reducedMotion('')}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'outline', position: 'right' })}
`.trim();
}

module.exports = { blocks, css };
