/**
 * erp-cta.js — Cta Section (S9)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: erp.html line 2319
 *
 * styles.css: 21 base, 2 hover, 0 pseudo, 1 hidden
 * Original classes: erp-cta, dw-d-bg, dw-d-bg--corner-tl, dw-d-bg--medium, dw-wave-flow (+6 more)
 */

const base = require('../../lib/templates/_base');

const P = 'cta'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="erp-cta">
    <div class="dw-d-bg dw-d-bg--corner-tl dw-d-bg--medium"></div>
            
            <div class="dw-wave-flow" style="height: 180px; opacity: 0.35; z-index: 1;"></div>
            <div class="erp-cta-inner" style="position: relative; z-index: 3;">
                <h2 class="erp-cta-title">Ready to See What's Possible?</h2>
                <p class="erp-cta-subtitle">Fill out the form and our team will reach out to discuss your specific manufacturing challenges.</p>
                <div class="erp-cta-buttons">
                    <a href="../demo.html" class="btn-white">Get in Touch</a>
                    <a href="../industries.html" class="btn-outline-white">View by Industry</a>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Cta', html, 'Cta: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CTA (S9) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.erp-cta {
            padding: 120px 0;
            background: linear-gradient(135deg, #0369a1 0%, #003CC8 50%, #001080 100%);
            position: relative;
            overflow: hidden;
            -webkit-font-smoothing: auto;
            -moz-osx-font-smoothing: auto;
        }
.erp-cta::before {
            content: '';
            position: absolute;
            inset: 0;
            background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
            opacity: 0.02;
            pointer-events: none;
        }
.erp-cta-inner {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 24px;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.erp-cta-title {
            font-family: 'Noto Sans', sans-serif;
            font-size: clamp(32px, 4vw, 44px);
            font-weight: 700;
            color: #ffffff;
            margin: 0 0 20px 0;
            line-height: 1.2;
        }
.erp-cta-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 19px;
            color: rgba(255, 255, 255, 0.9);
            margin: 0 0 40px 0;
            line-height: 1.6;
        
            -webkit-font-smoothing: auto;
}
.erp-cta-buttons {
            display: flex;
            gap: 20px;
            justify-content: center;
            flex-wrap: wrap;
        }
@media (prefers-reduced-motion: reduce) {
            .erp-hero-content,
            .erp-hero::before,
            .erp-hero-badge::before,
            .erp-dashboard-mockup,
            .pain-card,
            .pain-card-icon,
            .product-card,
            .weapon-card,
            .challenge-icon,
            .integration-link,
            .erp-use-case-pill,
            .erp-erpii-accordion summary,
            .boi-enforcement-cta,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
        }
@media (max-width: 640px) {
            .erp-hero {
                padding: 120px 0 80px;
            }

            .erp-hero-stats {
                flex-direction: column;
                gap: 24px;
                align-items: center;
            }

            .erp-hero-stat {
                text-align: center;
            }

            .erp-cta-buttons {
                flex-direction: column;
            }
        }

/* Buttons */
.btn-white{background:#ffffff;color:#003CC8;padding:20px 40px;border-radius:14px;font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.4s cubic-bezier(0.4, 0, 0.2, 1);box-shadow:0 4px 20px rgba(0, 0, 0, 0.15);display:inline-flex;align-items:center;gap:10px;line-height:25.6px !important;-webkit-font-smoothing:auto !important}
.btn-white:hover{transform:translateY(-4px);box-shadow:0 16px 48px rgba(0, 0, 0, 0.2)}
.btn-outline-white{background:transparent;color:#ffffff;padding:20px 40px;border-radius:14px;border:2px solid rgba(255, 255, 255, 0.5);font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.3s ease;line-height:25.6px !important;-webkit-font-smoothing:auto !important}
.btn-outline-white:hover{background:rgba(255, 255, 255, 0.15);border-color:#ffffff}
.dw-wave-flow{position:absolute;bottom:0;left:0;width:100%;pointer-events:none;overflow:hidden}
.dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MDAgNTA0IiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwNCIgZmlsbD0ibm9uZSI+CiAgPCEtLSBEaWdpV2luIFN1cGVyIEQgLSBPdXRsaW5lIHZhcmlhbnQgKHN0cm9rZS1vbmx5LCBmb3IgZGFyayBoZXJvIGJhY2tncm91bmRzKSAtLT4KICA8IS0tIFNjYWxlZCBmcm9tIGQtbWFyayAoMTYuNzPDlzE2Ljg5KSBieSB+MzB4IGZvciBiYWNrZ3JvdW5kIHVzZSAtLT4KICA8IS0tIEFyYyBzaGFwZSAtLT4KICA8cGF0aCBzdHJva2U9IiNGRkZGRkYiIHN0cm9rZS13aWR0aD0iMiIgZmlsbD0ibm9uZSIgZD0iTSAwIDUwNCBDIDAgNDUzLjggNDAuNyA0MTMuMyA5MC43IDQxMy4zIEwgMjQ3IDQxMy4zIEMgMzM2LjEgNDEzLjMgNDA4LjUgMzQxLjEgNDA4LjUgMjUyIEMgNDA4LjUgMTYyLjkgMzM2LjEgOTAuNyAyNDcgOTAuNyBMIDkwLjcgOTAuNyBDIDQwLjcgOTAuNyAwIDUwIDAgMCBMIDI0NyAwIEMgMzg2LjIgMCA0OTkgMTEyLjggNDk5IDI1MiBDIDQ5OSAzOTEuMiAzODYuMiA1MDQgMjQ3IDUwNCBaIi8+CiAgPCEtLSBDaXJjbGUvZG90IC0tPgogIDxwYXRoIHN0cm9rZT0iI0ZGRkZGRiIgc3Ryb2tlLXdpZHRoPSIyIiBmaWxsPSJub25lIiBkPSJNIDI2LjcgMjUyIEMgMjYuNyAyMTYuMSA1NS45IDE4Ni45IDkxLjggMTg2LjkgQyAxMjcuNiAxODYuOSAxNTYuOCAyMTYuMSAxNTYuOCAyNTIgQyAxNTYuOCAyODcuOCAxMjcuNiAzMTcgOTEuOCAzMTcgQyA1NS45IDMxNyAyNi43IDI4Ny44IDI2LjcgMjUyIi8+Cjwvc3ZnPgo=") no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12}
.dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none}
.dw-d-bg--medium{opacity:0.14 !important}

${base.reducedMotion('')}

.btn-white {
            line-height: 25.6px !important;
        }

.btn-outline-white {
            line-height: 25.6px !important;
        }
`.trim();
}

module.exports = { blocks, css };
