/**
 * industries-cta.js — Cta Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: industries.html line 1245
 *
 * styles.css: 26 base, 2 hover, 0 pseudo, 1 hidden
 * Original classes: cta-section, dw-d-bg, dw-d-bg--bottom, dw-d-bg--gradient, dw-d-parallax (+5 more)
 */

const base = require('../../lib/templates/_base');

const P = 'cta'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="cta-section">
    <div class="dw-d-bg dw-d-bg--bottom dw-d-bg--gradient dw-d-parallax" style="opacity: 0.10;"></div>
            
            <div class="dw-wave-flow" style="height: 160px; opacity: 0.3; z-index: 1;"></div>
            <div class="cta-inner" style="position: relative; z-index: 3;">
                <h2>Let's Talk About Your Factory</h2>
                <p>Every factory is different. Let us understand yours.</p>
                <div class="cta-buttons">
                    <a href="demo.html" class="cta-btn-primary">Get in Touch</a>
                    <a href="products.html" class="cta-btn-secondary">View Products</a>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Cta', html, 'Cta: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CTA (S6) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */
@media (prefers-reduced-motion: reduce) {
            .industries-hero-inner,
            .industries-hero::before,
            .industries-hero-badge::before,
            .context-stat,
            .industry-card,
            .industry-card-link,
            .challenge-card,
            .challenge-icon,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
            .industry-card.visible {
                opacity: 1;
                transform: none;
            }
        }

/* === HOVER STATES (auto-ported from styles.css) === */
.\${P}-btn-primary:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,0.2)}
.\${P}-btn-secondary:hover{border-color:#fff;background:rgba(255,255,255,0.1)}
/* WARNING: HIDDEN in styles.css (display:none) — DO NOT include in builder HTML */
/* .dw-wave-flow,
 * .dw-wave-flow--top {
 *     display: none;
 * } */
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-wave-flow--top{bottom:auto;top:0;transform:scaleY(-1)} */
/* .dw-d-parallax{will-change:transform} */
/* @media (prefers-reduced-motion:reduce){.dw-wave-flow{animation:none;width:100%;background-size:100% 100%}.dw-d-glow{animation:none}.dw-d-draw path{stroke-dashoffset:0}.dw-wave-reveal circle{transform:scale(1)}} */
@media (max-width:640px){.auto-hero, .elec-hero, .metal-hero{padding:120px 0 80px}.auto-hero h1, .elec-hero h1, .metal-hero h1{font-size:32px}.auto-hero-subtitle, .elec-hero-subtitle, .metal-hero-subtitle{font-size:17px}.auto-hero-stats, .elec-hero-stats, .metal-hero-stats{flex-direction:column;gap:24px}.auto-hero-stat-value, .elec-hero-stat-value, .metal-hero-stat-value{font-size:36px}.stake-card, .challenge-card{padding:32px 24px}.solution-card{padding:32px}.cta-section h2{font-size:28px}.cta-buttons{flex-direction:column}}
.cta-section{padding:100px 0;background:linear-gradient(135deg, #00AFF0 0%, #003CC8 100%);text-align:center}
/* .cta-inner{max-width:700px;margin:0 auto;padding:0 24px} */
.cta-section h2{font-family:'Noto Sans', sans-serif;font-size:40px;color:#fff;margin-bottom:16px}
.cta-section p{font-size:20px;color:rgba(255,255,255,0.9);margin-bottom:40px}
.cta-buttons{display:flex;gap:16px;justify-content:center} 
.cta-btn-primary{background:#fff;color:#00AFF0;padding:16px 32px;border-radius:8px;font-family:'Noto Sans', sans-serif;font-weight:600;font-size:16px;text-decoration:none;transition:all 0.3s ease} 
.cta-btn-secondary{background:transparent;color:#fff;padding:16px 32px;border:2px solid rgba(255,255,255,0.4);border-radius:8px;font-family:'Noto Sans', sans-serif;font-weight:600;font-size:16px;text-decoration:none;transition:all 0.3s ease} 
/* @media (max-width:640px){.dw-hero-panel{min-height:80vh;padding:48px 24px}.dw-hero-title{font-size:32px}.dw-section{padding:48px 24px}.dw-grid-2,.dw-grid-3,.dw-grid-4{grid-template-columns:1fr}.dw-stats-grid{grid-template-columns:1fr 1fr;gap:24px}.dw-cta-buttons{flex-direction:column;align-items:center}.dw-footer-grid{grid-template-columns:1fr}.dw-footer-bottom{flex-direction:column;text-align:center;gap:16px}.cta-section h2{font-size:28px}.cta-buttons{flex-direction:column}} */
/* @media (prefers-reduced-motion:reduce){.products-hero-content,.hero-stack-visual,.products-hero::before,.products-hero-badge::before,.stack-layer,.stack-layer::before,.data-particle,.ecosystem-node,.ecosystem-line,.ecosystem-ring,.data-flow-line,.data-flow-dot,.integration-hub::before,.integration-hub::after,.pp-card,.why-card,.why-card-icon,.pp-card-icon,.products-cta-glow,.dw-d-parallax,.dw-wave-flow,.dw-d-bg{animation:none !important;transition:none !important}.pp-card.visible{opacity:1;transform:none}} */

\${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
