/**
 * industries-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: industries.html line 946
 *
 * styles.css: 15 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: industries-hero, dw-d-bg, dw-d-bg--center, dw-d-bg--particle, dw-d-parallax (+8 more)
 */

const base = require('../../lib/templates/_base');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="industries-hero">
    <div class="dw-d-bg dw-d-bg--center dw-d-bg--particle dw-d-parallax" style="opacity: 0.10;"></div>
            <div class="industries-hero-inner">
                <div class="industries-hero-badge">
                    <span>Industry-Specific Manufacturing ERP</span>
                </div>
                <h1>Built for Your Industry.<br><span>Proven by Experience.</span></h1>
                <p class="industries-hero-subtitle">Your factory isn't generic — your ERP shouldn't be either. From automotive JIT scheduling to electronics component traceability to metal processing yield optimization, we've spent <span class="dw-years">44</span> years solving industry-specific challenges on the shop floor.</p>
                <div class="industries-hero-stats">
                    <div class="industries-hero-stat">
                        <div class="industries-hero-stat-number">3</div>
                        <div class="industries-hero-stat-label">Core Verticals</div>
                    </div>
                    <div class="industries-hero-stat">
                        <div class="industries-hero-stat-number">100+</div>
                        <div class="industries-hero-stat-label">Thai Implementations</div>
                    </div>
                    <div class="industries-hero-stat">
                        <div class="industries-hero-stat-number dw-years">44</div>
                        <div class="industries-hero-stat-label">Years Manufacturing-Only</div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */
.industries-hero {
            background: linear-gradient(165deg, #0f1419 0%, #1a2632 40%, #000864 100%);
            padding: 160px 0 120px;
            position: relative;
            overflow: hidden;
            min-height: 60vh;
            display: flex;
            align-items: center;
        }
.industries-hero::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
            opacity: 0.03;
            pointer-events: none;
            animation: grain 8s steps(10) infinite;
        }
.industries-hero::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: radial-gradient(ellipse at 70% 30%, rgba(0, 175, 240, 0.12) 0%, transparent 50%),
                        radial-gradient(ellipse at 30% 80%, rgba(0, 175, 240, 0.08) 0%, transparent 40%);
            pointer-events: none;
        }
.industries-hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
            position: relative;
            z-index: 2;
            text-align: center;
            animation: slide-up 0.8s ease-out;
        }
.industries-hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 10px;
            background: rgba(0, 175, 240, 0.1);
            border: 1px solid rgba(0, 175, 240, 0.3);
            padding: 10px 20px;
            border-radius: 50px;
            color: #00AFF0;
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-bottom: 28px;
        }
.industries-hero-badge::before {
            content: '';
            width: 8px;
            height: 8px;
            background: #00AFF0;
            border-radius: 50%;
            animation: pulse-dot 2s ease-in-out infinite;
        }
.industries-hero h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: clamp(40px, 5vw, 56px);
            font-weight: 700;
            color: #fff;
            margin: 0 0 24px 0;
            line-height: 1.1;
            letter-spacing: -0.03em;
        }
.industries-hero h1 span {
            color: #00AFF0;
        }
.industries-hero-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 19px;
            color: rgba(255,255,255,0.75);
            max-width: 680px;
            margin: 0 auto 40px;
            line-height: 1.7;
        }
.industries-hero-stats {
            display: flex;
            gap: 48px;
            justify-content: center;
            padding-top: 40px;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
        }
.industries-hero-stat {
            text-align: center;
        }
.industries-hero-stat-number {
            font-family: 'Noto Sans', sans-serif;
            font-size: 36px;
            font-weight: 800;
            color: #00AFF0;
            letter-spacing: -0.02em;
        }
.industries-hero-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-top: 6px;
        }
@media (max-width: 1024px) {
            .industries-hero h1 { font-size: 40px; }
            .context-stats { grid-template-columns: repeat(2, 1fr); }
            .industry-card { grid-template-columns: 1fr; }
            .industry-card:nth-child(even) { direction: ltr; }
            .challenges-grid { grid-template-columns: repeat(2, 1fr); }
            .approach-steps { grid-template-columns: 1fr; gap: 40px; }
        }
@media (prefers-reduced-motion: reduce) {
            .industries-hero-inner,
            .industries-hero::before,
            .industries-hero-badge::before,
            .context-stat,
            .industry-card,
            .industry-card-link,
            .challenge-card,
            .challenge-icon,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
            .industry-card.visible {
                opacity: 1;
                transform: none;
            }
        }
@media (max-width: 640px) {
            .industries-hero { padding: 120px 0 80px; }
            .industries-hero h1 { font-size: 32px; }
            .industries-hero-subtitle { font-size: 17px; }
            .industries-hero-stats { flex-wrap: wrap; gap: 32px; }
            .context-stats { grid-template-columns: 1fr; }
            .context-stat-value { font-size: 32px; }
            .industry-card-visual { padding: 40px; }
            .industry-card-content { padding: 32px; }
            .industry-card-title { font-size: 24px; }
            .industry-features { grid-template-columns: 1fr; }
            .challenges-grid { grid-template-columns: 1fr; }
        }

/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-d-parallax{will-change:transform} */
/* @media (prefers-reduced-motion:reduce){.products-hero-content,.hero-stack-visual,.products-hero::before,.products-hero-badge::before,.stack-layer,.stack-layer::before,.data-particle,.ecosystem-node,.ecosystem-line,.ecosystem-ring,.data-flow-line,.data-flow-dot,.integration-hub::before,.integration-hub::after,.pp-card,.why-card,.why-card-icon,.pp-card-icon,.products-cta-glow,.dw-d-parallax,.dw-wave-flow,.dw-d-bg{animation:none !important;transition:none !important}.pp-card.visible{opacity:1;transform:none}} */

\${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
