/**
 * industries-section.js — Section Section (S3)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: industries.html line 1005
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 2 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: industries-section, dw-section-scene, industries-inner, industries-label, industries-header (+13 more)
 */

const base = require('../../lib/templates/_base');

const P = 'sec'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="industries-section">
    <div class="dw-section-scene">
                <svg aria-hidden="true" viewBox="0 0 1400 900" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice">
                    <line x1="0" y1="150" x2="1400" y2="150" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="0" y1="300" x2="1400" y2="300" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="0" y1="450" x2="1400" y2="450" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="0" y1="600" x2="1400" y2="600" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="0" y1="750" x2="1400" y2="750" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="200" y1="0" x2="200" y2="900" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="500" y1="0" x2="500" y2="900" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="800" y1="0" x2="800" y2="900" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <line x1="1100" y1="0" x2="1100" y2="900" stroke="#000864" stroke-width="0.5" opacity="0.08"/>
                    <circle cx="350" cy="300" r="70" stroke="#000864" stroke-width="2" fill="none" opacity="0.12"/>
                    <circle cx="350" cy="300" r="30" stroke="#000864" stroke-width="1.5" fill="none" opacity="0.15"/>
                    <rect x="340" y="225" width="20" height="15" rx="2" fill="#000864" opacity="0.1"/>
                    <rect x="340" y="360" width="20" height="15" rx="2" fill="#000864" opacity="0.1"/>
                    <rect x="275" y="290" width="15" height="20" rx="2" fill="#000864" opacity="0.1"/>
                    <rect x="410" y="290" width="15" height="20" rx="2" fill="#000864" opacity="0.1"/>
                    <line x1="600" y1="200" x2="900" y2="200" stroke="#000864" stroke-width="1" opacity="0.12"/>
                    <line x1="600" y1="190" x2="600" y2="210" stroke="#000864" stroke-width="1" opacity="0.12"/>
                    <line x1="900" y1="190" x2="900" y2="210" stroke="#000864" stroke-width="1" opacity="0.12"/>
                    <text x="750" y="195" font-family="'Noto Sans',sans-serif" font-size="11" fill="#000864" opacity="0.08" text-anchor="middle">300mm</text>
                    <rect x="1000" y="350" width="200" height="120" rx="6" stroke="#000864" stroke-width="2" fill="none" opacity="0.12"/>
                    <circle cx="1100" cy="430" r="20" stroke="#000864" stroke-width="1" fill="none" opacity="0.1"/>
                    <path d="M300 650 L500 650" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="495,645 510,650 495,655" fill="#000864" opacity="0.12"/>
                    <path d="M550 650 L750 650" stroke="#000864" stroke-width="1.5" opacity="0.12"/>
                    <polygon points="745,645 760,650 745,655" fill="#000864" opacity="0.12"/>
                    <circle cx="650" cy="400" r="3" fill="#00AFF0" opacity="0.12"/>
                    <circle cx="1250" cy="600" r="3" fill="#000864" opacity="0.08"/>
                </svg>
            </div>
            <div class="industries-inner" style="position: relative; z-index: 2;">
                <p class="industries-label">Specialized Solutions</p>
                <div class="industries-header">
                    <h2>Choose Your Industry</h2>
                    <p>Specialized solutions for Thailand's core manufacturing sectors</p>
                </div>
                <div class="industry-cards">
                    
                    <a href="industries/automotive.html" class="industry-card">
                        <div class="industry-card-visual">
                            <div class="industry-card-icon">
                                <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M7 17a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM17 17a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/><path d="M5 15H3V9l2-4h10l4 4v6h-2"/><path d="M9 15h6"/><path d="M5 9h14"/></svg>
                            </div>
                            <div class="industry-card-stat">
                                <div class="industry-card-stat-value">500+</div>
                                <div class="industry-card-stat-label">Tier 1-3 suppliers served</div>
                            </div>
                        </div>
                        <div class="industry-card-content">
                            <h3 class="industry-card-title">Automotive Parts Manufacturing</h3>
                            <p class="industry-card-desc">Thailand is ASEAN's Detroit. We understand what tier-1 OEMs demand: perfect lot traceability, JIT delivery schedules, and EDI integration that actually works with your customers' systems.</p>
                            <div class="industry-features">
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>OEM EDI integration</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>IATF 16949 compliance</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Lot-level traceability</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Kanban & JIT</span>
                                </div>
                            </div>
                            <span class="industry-card-link">Explore Automotive Solutions <span>→</span></span>
                        </div>
                    </a>
    
                    
                    <a href="industries/electronics.html" class="industry-card">
                        <div class="industry-card-visual">
                            <div class="industry-card-icon">
                                <svg aria-hidden="true" viewBox="0 0 24 24"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>
                            </div>
                            <div class="industry-card-stat">
                                <div class="industry-card-stat-value">1000+</div>
                                <div class="industry-card-stat-label">Component types tracked</div>
                            </div>
                        </div>
                        <div class="industry-card-content">
                            <h3 class="industry-card-title">Electronics Assembly</h3>
                            <p class="industry-card-desc">High-mix, low-volume. Fast product cycles. Thousands of components per board. Moisture-sensitive parts. We built our MES specifically for this complexity.</p>
                            <div class="industry-features">
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>SMT integration</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Component traceability</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>MSD management</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>AOI integration</span>
                                </div>
                            </div>
                            <span class="industry-card-link">Explore Electronics Solutions <span>→</span></span>
                        </div>
                    </a>
    
                    
                    <a href="industries/metal-plastics.html" class="industry-card">
                        <div class="industry-card-visual">
                            <div class="industry-card-icon">
                                <svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>
                            </div>
                            <div class="industry-card-stat">
                                <div class="industry-card-stat-value">15%</div>
                                <div class="industry-card-stat-label">Average yield improvement</div>
                            </div>
                        </div>
                        <div class="industry-card-content">
                            <h3 class="industry-card-title">Metal & Plastics Processing</h3>
                            <p class="industry-card-desc">Stamping, injection molding, die casting, CNC machining. Process manufacturing where yield optimization and scrap reduction directly drive your margins.</p>
                            <div class="industry-features">
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Process monitoring</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Mold/die tracking</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Scrap analysis</span>
                                </div>
                                <div class="industry-feature">
                                    <svg aria-hidden="true" viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"/></svg>
                                    <span>Cycle optimization</span>
                                </div>
                            </div>
                            <span class="industry-card-link">Explore Metal & Plastics Solutions <span>→</span></span>
                        </div>
                    </a>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Section', html, 'Section: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === SECTION (S3) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.industries-section {
            padding: 120px 0;
            background: #F5F7FA;
            position: relative;
        }
.industries-section::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: radial-gradient(circle, rgba(0, 175, 240, 0.03) 1px, transparent 1px);
            background-size: 30px 30px;
            pointer-events: none;
        }
.industries-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
            position: relative;
            z-index: 1;
        }
.industries-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            color: #00AFF0;
            text-transform: uppercase;
            letter-spacing: 0.15em;
            text-align: center;
            margin-bottom: 16px;
        }
.industries-header {
            text-align: center;
            margin-bottom: 72px;
        }
.industries-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 16px;
            letter-spacing: -0.02em;
        }
.industries-header p {
            font-size: 18px;
            color: #5b6b80;
            line-height: 1.6;
        }
.industry-cards {
            display: flex;
            flex-direction: column;
            gap: 36px;
        }
.industry-card {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 0;
            background: #ffffff;
            border-radius: 24px;
            overflow: hidden;
            box-shadow: 0 4px 24px rgba(0,0,0,0.06);
            transition: all 0.5s cubic-bezier(0.4, 0, 0.2, 1);
            text-decoration: none;
            border: 1px solid #e8eef3;
            opacity: 0;
            transform: translateY(40px);
        }
.industry-card.visible {
            opacity: 1;
            transform: translateY(0);
        }
.industry-card:hover {
            box-shadow: 0 24px 64px rgba(0, 175, 240, 0.18);
            transform: translateY(-8px);
            border-color: transparent;
        }
.industry-card:nth-child(even) {
            direction: rtl;
        }
.industry-card:nth-child(even) > * {
            direction: ltr;
        }
.industry-card-visual {
            background: linear-gradient(165deg, #0f1419 0%, #1a2632 50%, #000864 100%);
            padding: 60px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            position: relative;
            overflow: hidden;
        }
.industry-card-visual::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E");
            opacity: 0.03;
            pointer-events: none;
        }
.industry-card-icon {
            width: 100px;
            height: 100px;
            background: rgba(0, 175, 240, 0.15);
            border-radius: 24px;
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 28px;
            filter: drop-shadow(0 4px 16px rgba(0, 0, 0, 0.2));
        }
.industry-card-icon svg {
            width: 52px;
            height: 52px;
            stroke: #fff;
            stroke-width: 1.5;
            fill: none;
        }
.industry-card-stat {
            color: #fff;
        }
.industry-card-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 52px;
            font-weight: 800;
            color: #00AFF0;
            letter-spacing: -0.02em;
        }
.industry-card-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            color: rgba(255,255,255,0.75);
            margin-top: 8px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
.industry-card-content {
            padding: 48px;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
.industry-card-title {
            font-family: 'Noto Sans', sans-serif;
            font-size: 28px;
            color: #000864;
            margin-bottom: 16px;
        }
.industry-card-desc {
            font-size: 16px;
            color: #5b6b80;
            line-height: 1.7;
            margin-bottom: 24px;
        }
.industry-features {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 12px;
            margin-bottom: 24px;
        }
.industry-feature {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 14px;
            color: #475569;
        }
.industry-feature svg {
            width: 16px;
            height: 16px;
            color: #0369a1;
            flex-shrink: 0;
        }
.industry-card-link {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            color: #0369a1;
            font-family: 'Noto Sans', sans-serif;
            font-weight: 600;
            font-size: 15px;
            text-decoration: none;
            transition: gap 0.3s ease;
        }
.industry-card:hover .industry-card-link {
            gap: 12px;
        }
@media (max-width: 1024px) {
            .industries-hero h1 { font-size: 40px; }
            .context-stats { grid-template-columns: repeat(2, 1fr); }
            .industry-card { grid-template-columns: 1fr; }
            .industry-card:nth-child(even) { direction: ltr; }
            .challenges-grid { grid-template-columns: repeat(2, 1fr); }
            .approach-steps { grid-template-columns: 1fr; gap: 40px; }
        }
@media (prefers-reduced-motion: reduce) {
            .industries-hero-inner,
            .industries-hero::before,
            .industries-hero-badge::before,
            .context-stat,
            .industry-card,
            .industry-card-link,
            .challenge-card,
            .challenge-icon,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
            .industry-card.visible {
                opacity: 1;
                transform: none;
            }
        }
@media (max-width: 640px) {
            .industries-hero { padding: 120px 0 80px; }
            .industries-hero h1 { font-size: 32px; }
            .industries-hero-subtitle { font-size: 17px; }
            .industries-hero-stats { flex-wrap: wrap; gap: 32px; }
            .context-stats { grid-template-columns: 1fr; }
            .context-stat-value { font-size: 32px; }
            .industry-card-visual { padding: 40px; }
            .industry-card-content { padding: 32px; }
            .industry-card-title { font-size: 24px; }
            .industry-features { grid-template-columns: 1fr; }
            .challenges-grid { grid-template-columns: 1fr; }
        }

\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
