/**
 * industries-context.js — Context Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: industries.html line 976
 *
 * styles.css: 5 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: context-section, context-inner, context-label, context-header, context-stats (+3 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'con'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="context-section">
    <div class="context-inner">
                <p class="context-label">Market Context</p>
                <div class="context-header">
                    <h2>Thailand: ASEAN's Manufacturing Hub</h2>
                    <p>The region's most mature industrial ecosystem, with deep supply chains and demanding global customers</p>
                </div>
                <div class="context-stats">
                    <div class="context-stat">
                        <div class="context-stat-value">#1</div>
                        <div class="context-stat-label">ASEAN auto production</div>
                    </div>
                    <div class="context-stat">
                        <div class="context-stat-value">2,500+</div>
                        <div class="context-stat-label">Auto parts suppliers</div>
                    </div>
                    <div class="context-stat">
                        <div class="context-stat-value">\$40B</div>
                        <div class="context-stat-label">Electronics exports</div>
                    </div>
                    <div class="context-stat">
                        <div class="context-stat-value">~27%</div>
                        <div class="context-stat-label">GDP from manufacturing</div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Context', html, 'Context: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CONTEXT (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .context-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.context-section {
            padding: 120px 0;
            background: #ffffff;
            position: relative;
        }
.context-section::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 1px;
            background: linear-gradient(90deg, transparent, #00AFF0, transparent);
        }
.context-inner {
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }
.context-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            color: #00AFF0;
            text-transform: uppercase;
            letter-spacing: 0.15em;
            text-align: center;
            margin-bottom: 16px;
        }
.context-header {
            text-align: center;
            margin-bottom: 60px;
        }
.context-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 16px;
            letter-spacing: -0.02em;
        }
.context-header p {
            font-size: 18px;
            color: #5b6b80;
            max-width: 700px;
            margin: 0 auto;
            line-height: 1.6;
        }
.context-stats {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 24px;
            margin-bottom: 60px;
        }
.context-stat {
            text-align: center;
            padding: 40px 24px;
            background: #F5F7FA;
            border-radius: 20px;
            transition: all 0.4s ease;
            border: 1px solid transparent;
        }
.context-stat:hover {
            background: #ffffff;
            border-color: rgba(0, 175, 240, 0.2);
            box-shadow: 0 12px 40px rgba(0, 175, 240, 0.1);
        }
.context-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 44px;
            font-weight: 800;
            color: #00AFF0;
            line-height: 1;
            letter-spacing: -0.02em;
        }
.context-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            color: #5b6b80;
            margin-top: 12px;
            line-height: 1.4;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }
@media (max-width: 1024px) {
            .industries-hero h1 { font-size: 40px; }
            .context-stats { grid-template-columns: repeat(2, 1fr); }
            .industry-card { grid-template-columns: 1fr; }
            .industry-card:nth-child(even) { direction: ltr; }
            .challenges-grid { grid-template-columns: repeat(2, 1fr); }
            .approach-steps { grid-template-columns: 1fr; gap: 40px; }
        }
@media (prefers-reduced-motion: reduce) {
            .industries-hero-inner,
            .industries-hero::before,
            .industries-hero-badge::before,
            .context-stat,
            .industry-card,
            .industry-card-link,
            .challenge-card,
            .challenge-icon,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-wave-fade,
            .dw-d-bg {
                animation: none !important;
                transition: none !important;
            }
            .industry-card.visible {
                opacity: 1;
                transform: none;
            }
        }
@media (max-width: 640px) {
            .industries-hero { padding: 120px 0 80px; }
            .industries-hero h1 { font-size: 32px; }
            .industries-hero-subtitle { font-size: 17px; }
            .industries-hero-stats { flex-wrap: wrap; gap: 32px; }
            .context-stats { grid-template-columns: 1fr; }
            .context-stat-value { font-size: 32px; }
            .industry-card-visual { padding: 40px; }
            .industry-card-content { padding: 32px; }
            .industry-card-title { font-size: 24px; }
            .industry-features { grid-template-columns: 1fr; }
            .challenges-grid { grid-template-columns: 1fr; }
        }

.context-section{padding:100px 0;background:#fff}
.context-inner{max-width:900px;margin:0 auto;padding:0 24px;text-align:center}
.context-inner h2{font-family:'Noto Sans', sans-serif;font-size:36px;color:#000864;margin-bottom:24px}
.context-inner p{font-size:18px;color:#5b6b80;line-height:1.8}
.context-inner p strong{color:#000864}

${base.reducedMotion('')}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'outline', position: 'right' })}
`.trim();
}

module.exports = { blocks, css };
