/**
 * mes-reports.js — Reports Section (S8)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: mes.html line 1772
 *
 * styles.css: 4 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: reports-section, reports-inner, section-header, section-title, section-subtitle (+8 more)
 */

const base = require('../../lib/templates/_base');

const P = 'rep'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="reports-section">
    <div class="reports-inner">
                <div class="section-header">
                    <h2 class="section-title">Built-In Reports & Dashboards</h2>
                    <p class="section-subtitle">Pre-configured analytics ready from day one — no custom development needed</p>
                </div>
    
                <div class="reports-grid">
                    
                    <div class="reports-column">
                        <div class="reports-column-header">
                            <span class="reports-column-badge">MES</span>
                            <span class="reports-column-count">10 Reports</span>
                        </div>
                        <ol class="reports-list">
                            <li><span class="report-icon">&#9632;</span> Work Order Progress</li>
                            <li><span class="report-icon">&#9632;</span> Equipment Utilization (OEE)</li>
                            <li><span class="report-icon">&#9632;</span> Quality Inspection</li>
                            <li><span class="report-icon">&#9632;</span> Material Consumption</li>
                            <li><span class="report-icon">&#9632;</span> Shift Performance</li>
                            <li><span class="report-icon">&#9632;</span> Downtime Analysis</li>
                            <li><span class="report-icon">&#9632;</span> Yield Rate</li>
                            <li><span class="report-icon">&#9632;</span> Cycle Time</li>
                            <li><span class="report-icon">&#9632;</span> Batch Traceability</li>
                            <li><span class="report-icon">&#9632;</span> Operator Productivity</li>
                        </ol>
                    </div>
    
                    
                    <div class="reports-column">
                        <div class="reports-column-header">
                            <span class="reports-column-badge sft">SFT</span>
                            <span class="reports-column-count">6 Dashboards</span>
                        </div>
                        <ol class="reports-list">
                            <li><span class="report-icon">&#9632;</span> Production Status Board</li>
                            <li><span class="report-icon">&#9632;</span> Daily Output Summary</li>
                            <li><span class="report-icon">&#9632;</span> Machine Status Monitor</li>
                            <li><span class="report-icon">&#9632;</span> Order Completion</li>
                            <li><span class="report-icon">&#9632;</span> WIP Tracking</li>
                            <li><span class="report-icon">&#9632;</span> Delivery Schedule</li>
                        </ol>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Reports', html, 'Reports: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === REPORTS (S8) === */
/* TODO: Review and remap class selectors to use \${P} prefix */
/* TODO: Add section container: .\${P}-section{...;\${base.fontSmoothingReset(P)}font-size:16px} */
.reports-section {
            padding: 80px 0;
            background: #ffffff;
        }
.reports-inner {
            max-width: 1100px;
            margin: 0 auto;
            padding: 0 24px;
        }
.reports-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 32px;
        }
.reports-column {
            background: #F5F7FA;
            border-radius: 16px;
            padding: 32px;
            border: 1px solid #e8eef3;
        }
.reports-column-header {
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 20px;
        }
.reports-column-badge {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.1em;
            background: #000864;
            color: #ffffff;
            padding: 4px 12px;
            border-radius: 50px;
        }
.reports-column-badge.sft {
            background: linear-gradient(135deg, #00AFF0, #003CC8);
        }
.reports-column-count {
            font-family: 'Noto Sans', sans-serif;
            font-size: 14px;
            color: #5b6b80;
        }
.reports-list {
            list-style: none;
            padding: 0;
            margin: 0;
        }
.reports-list li {
            font-family: 'Noto Sans', sans-serif;
            font-size: 15px;
            color: #000864;
            padding: 10px 0;
            border-bottom: 1px solid #e2e8f0;
            display: flex;
            align-items: center;
            gap: 10px;
        }
.reports-list li:last-child {
            border-bottom: none;
        }
.reports-list .report-icon {
            color: #00AFF0;
            flex-shrink: 0;
            font-size: 14px;
        }
@media (max-width: 1024px) {
            .beforeafter-grid {
                grid-template-columns: 1fr;
                max-width: 500px;
                margin: 0 auto;
            }
            .beforeafter-arrow {
                transform: rotate(90deg);
                padding: 16px 0;
            }
            .products-grid {
                grid-template-columns: 1fr;
                max-width: 600px;
                margin: 0 auto;
            }
            .selection-guide {
                grid-template-columns: 1fr;
                max-width: 400px;
                margin: 48px auto 0;
            }
            .erp-compat-callout {
                flex-direction: column;
                align-items: center;
                text-align: center;
            }
            .integration-visual {
                flex-direction: column;
            }
            .integration-arrow {
                transform: rotate(90deg);
                padding: 8px 0;
            }
            .results-grid {
                grid-template-columns: repeat(3, 1fr);
            }
            .reports-grid {
                grid-template-columns: 1fr;
                max-width: 500px;
                margin: 0 auto;
            }
        }

/* REF: BASE RULES from styles.css (check against inline CSS above) */
.section-header{text-align:center;margin-bottom:48px}
.section-title{font-family:'Noto Sans', sans-serif;font-size:36px;font-weight:700;color:#000864;margin-bottom:16px}
.section-subtitle{font-family:'Noto Sans', sans-serif;font-size:18px;color:#5b6b80;max-width:600px;margin:0 auto}
@media (max-width:640px){.section-title{font-size:28px}.capabilities-grid{grid-template-columns:1fr;max-width:360px;margin-left:auto;margin-right:auto}.product-detail-cta-title{font-size:28px}.product-detail-cta-buttons{flex-direction:column}.product-detail-cta-buttons .btn-white,.product-detail-cta-buttons .btn-outline-white{width:100%;text-align:center}}
\${base.diviListReset(P)}

`.trim();
}

module.exports = { blocks, css };
