/**
 * mes-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: mes.html line 1262
 *
 * styles.css: 32 base, 3 hover, 1 pseudo, 0 hidden
 * Original classes: mes-hero, dw-d-bg, dw-d-bg--bottom, dw-d-bg--particle, dw-d-parallax (+27 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="mes-hero">
    <div class="dw-d-bg dw-d-bg--bottom dw-d-bg--particle dw-d-parallax" style="opacity: 0.15;"></div>
            <div class="mes-hero-inner">
                <div class="mes-hero-grid">
                    <div class="mes-hero-content">
                        <div class="mes-hero-badge">Manufacturing Execution System</div>
                        <h1>Stop Guessing. Start Seeing.</h1>
                        <p class="mes-hero-subtitle">Real-time visibility into every workstation, every work order, every minute. Know exactly what's happening on your shop floor—as it happens.</p>
                        <div class="mes-hero-ctas">
                            <a href="../demo.html" class="btn-white">Let's Talk</a>
                            <a href="#compare" class="btn-outline-white">Find Your Fit</a>
                        </div>
                        <div class="mes-hero-stats">
                            <div class="mes-hero-stat">
                                <div class="mes-hero-stat-number dw-years">44</div>
                                <div class="mes-hero-stat-label">Years in Mfg</div>
                            </div>
                            <div class="mes-hero-stat">
                                <div class="mes-hero-stat-number">50K+</div>
                                <div class="mes-hero-stat-label">Factories</div>
                            </div>
                            <div class="mes-hero-stat">
                                <div class="mes-hero-stat-number">100+</div>
                                <div class="mes-hero-stat-label">Thai Sites</div>
                            </div>
                        </div>
                    </div>
                    <div class="mes-hero-visual">
                        <div class="mes-dashboard-mockup">
                            <div class="mockup-header">
                                <div class="mockup-dot"></div>
                                <div class="mockup-dot"></div>
                                <div class="mockup-dot"></div>
                            </div>
                            <div class="mockup-content">
                                <div class="mockup-status-bar">
                                    <div class="mockup-status-item">
                                        <div class="mockup-status-value green">87%</div>
                                        <div class="mockup-status-label">OEE</div>
                                    </div>
                                    <div class="mockup-status-item">
                                        <div class="mockup-status-value">1,247</div>
                                        <div class="mockup-status-label">Units Today</div>
                                    </div>
                                    <div class="mockup-status-item">
                                        <div class="mockup-status-value yellow">3</div>
                                        <div class="mockup-status-label">Alerts</div>
                                    </div>
                                </div>
                                <div class="mockup-timeline">
                                    <div class="mockup-bar" style="height: 40%;"></div>
                                    <div class="mockup-bar" style="height: 65%;"></div>
                                    <div class="mockup-bar" style="height: 55%;"></div>
                                    <div class="mockup-bar" style="height: 80%;"></div>
                                    <div class="mockup-bar" style="height: 70%;"></div>
                                    <div class="mockup-bar active" style="height: 90%;"></div>
                                    <div class="mockup-bar" style="height: 45%;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.mes-hero {
            background: linear-gradient(135deg, #1a2d3d 0%, #000864 50%, #001080 100%);
            padding: 140px 0 100px;
            position: relative;
            overflow: hidden;
        }
.mes-hero::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('data:image/svg+xml,<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="rgba(255,255,255,0.03)" stroke-width="0.5"/></pattern></defs><rect width="100" height="100" fill="url(%23grid)"/></svg>');
            opacity: 0.5;
        }
.mes-hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.mes-hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(0, 175, 240, 0.15);
            border: 1px solid rgba(0, 175, 240, 0.3);
            padding: 8px 20px;
            border-radius: 50px;
            color: #7fc4fd;
            font-size: 11px;
            font-weight: 500;
            margin-bottom: 24px;
            font-family: 'JetBrains Mono', monospace;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        
            line-height: 17.6px;

            -webkit-font-smoothing: auto;
}
.mes-hero-stats {
            display: flex;
            justify-content: center;
            gap: 48px;
            margin-top: 40px;
            padding-top: 32px;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
        }
.mes-hero-stat-number {
            font-family: 'Noto Sans', sans-serif;
            font-size: 32px;
            font-weight: 800;
            color: #00AFF0;
        
            line-height: 51.2px !important;

            -webkit-font-smoothing: auto !important;
}
.mes-hero-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-top: 4px;
        
            line-height: 16px !important;

            -webkit-font-smoothing: auto !important;
}
.mes-hero-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 60px;
            align-items: center;
            text-align: left;
        }
.mes-hero-content {
            max-width: 560px;
        }
.mes-hero-visual {
            position: relative;
        }
.mes-dashboard-mockup {
            background: rgba(255, 255, 255, 0.03);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 20px;
            box-shadow: 0 40px 80px rgba(0, 0, 0, 0.3);
        }
.mockup-content {
            background: rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            padding: 16px;
        }
.mockup-status-bar {
            display: flex;
            gap: 12px;
            margin-bottom: 16px;
        }
.mockup-status-item {
            flex: 1;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 8px;
            padding: 12px;
            text-align: center;
        }
.mockup-status-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 20px;
            font-weight: 700;
            color: #00AFF0;
        
            line-height: 32px !important;

            -webkit-font-smoothing: auto !important;
}
.mockup-status-value.green { color: #047857; }
.mockup-status-value.yellow { color: #f59e0b; }
.mockup-status-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 9px;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            margin-top: 4px;
        
            line-height: 14.4px !important;

            -webkit-font-smoothing: auto !important;
}
.mockup-timeline {
            display: flex;
            gap: 8px;
            align-items: flex-end;
            height: 60px;
            padding: 8px;
            background: rgba(255, 255, 255, 0.03);
            border-radius: 6px;
        }
.mes-hero h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 48px;
            font-weight: 700;
            color: #ffffff;
            margin-bottom: 20px;
            line-height: 1.15;
        }
.mes-hero-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 20px;
            color: rgba(255, 255, 255, 0.85);
            max-width: 700px;
            margin: 0 auto 32px;
            line-height: 1.6;
        
            -webkit-font-smoothing: auto;
}
.mes-hero-ctas {
            display: flex;
            gap: 16px;
            justify-content: center;
            flex-wrap: wrap;
        }
.integration-node.active {
            border-color: #00AFF0;
            background: linear-gradient(135deg, #f0f7ff 0%, #ffffff 100%);
            box-shadow: 0 8px 24px rgba(0, 175, 240, 0.15);
        }
@media (max-width: 1024px) {
            .mes-hero-grid {
                grid-template-columns: 1fr;
                text-align: center;
            }
            .mes-hero-content {
                max-width: 100%;
            }
            .mes-hero-visual {
                display: none;
            }
            .mes-hero-stats {
                justify-content: center;
            }
        }
@media (max-width: 640px) {
            .mes-hero {
                padding: 120px 0 60px;
            }
            .mes-hero h1 {
                font-size: 32px;
            }
            .results-grid {
                grid-template-columns: 1fr;
                max-width: 280px;
                margin: 0 auto 32px;
            }
        }
@media (prefers-reduced-motion: reduce) {
            .product-box,
            .integration-node,
            .integration-link,
            .dw-d-bg,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-d-glow {
                animation: none !important;
                transition: none !important;
            }
        }

/* TODO: HOVER STATES using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link svg,.dw-nav-item:hover .dw-nav-link svg{transform:rotate(180deg)} */
/* Buttons */
.btn-white{background:#ffffff;color:#003CC8;padding:20px 40px;border-radius:14px;font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.4s cubic-bezier(0.4, 0, 0.2, 1);box-shadow:0 4px 20px rgba(0, 0, 0, 0.15);display:inline-flex;align-items:center;gap:10px
            line-height: 25.6px!important;

            -webkit-font-smoothing: auto;
}
.btn-white:hover{transform:translateY(-4px);box-shadow:0 16px 48px rgba(0, 0, 0, 0.2)}
.btn-outline-white{background:transparent;color:#ffffff;padding:20px 40px;border-radius:14px;border:2px solid rgba(255, 255, 255, 0.5);font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.3s ease
            line-height: 25.6px!important;

            -webkit-font-smoothing: auto;
}
.btn-outline-white:hover{background:rgba(255, 255, 255, 0.15);border-color:#ffffff}
/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link::after{transform:scaleX(1)} */
\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}

.mes-hero-stat-label {
            line-height: 16px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mes-hero-stat-number {
            line-height: 51.2px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mes-hero-stat-label {
            line-height: 16px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mockup-status-value {
            line-height: 32px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mockup-status-label {
            line-height: 14.4px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mockup-status-label {
            line-height: 14.4px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mes-hero-stat-number {
            line-height: 51.2px !important;
        
            -webkit-font-smoothing: auto !important;
}

.mockup-status-value {
            line-height: 32px !important;
        
            -webkit-font-smoothing: auto !important;
}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'particle', position: 'bottom', modifiers: ['glow'] })}

.et_pb_section .btn-white {
            line-height: 25.6px !important;
        }

.et_pb_section .btn-outline-white {
            line-height: 25.6px !important;
        }
`.trim();
}

module.exports = { blocks, css };
