/**
 * mes-section.js — Section Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: mes.html line 1327
 *
 * styles.css: 17 base, 0 hover, 1 pseudo, 0 hidden
 * Original classes: dw-section
 */

const base = require('../../lib/templates/_base');

const P = 'sec'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-section" style="padding: 40px 0 0; text-align: center;">
    <div style="max-width: 800px; margin: 0 auto; padding: 0 24px;">
        <h2 style="font-family: 'Noto Sans', sans-serif; font-size: 22px; font-weight: 700; color: #000864; margin: 0 0 12px 0;">What is MES (Manufacturing Execution System)?</h2>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333; margin: 0 0 24px 0;">
          A Manufacturing Execution System (MES) is software that monitors, tracks, and controls production on the factory floor in real time, bridging the gap between ERP planning and shop floor execution. It gives manufacturers instant visibility into what is happening at every workstation and work order — replacing paper logs and delayed reports with live data.
        </p>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333;">
          <strong>DigiWin MES</strong> provides this real-time visibility for factories in Thailand. Through three tiers — <strong>MES</strong> for full production execution, <strong>SFT</strong> (Shop Floor Tracking) for mid-tier tracking, and <strong>AIoT Cloud</strong> for entry-level monitoring — it tracks work orders, calculates OEE in real time, captures quality data at every station, and maintains complete lot-level traceability. Start anywhere and upgrade as your factory matures.
        </p>
      </div>    </div>`;

  return base.wrapInDiviSection('Section', html, 'Section: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === SECTION (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .dw-section{...;${base.fontSmoothingReset(P)}font-size:16px} */


/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-section--blue::before{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:radial-gradient(ellipse at 20% 30%, rgba(255,255,255,0.15) 0%, transparent 50%);pointer-events:none} */
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
