/**
 * news-past.js — Past Section (S5)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: news.html line 1461
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 29 base, 2 hover, 1 pseudo, 0 hidden
 * Original classes: past-section, dw-d-bg, dw-d-bg--corner-br, past-inner, past-header (+13 more)
 */

// TEMPLATE HINT: matches "card-grid-dark". See home-trust-anchors.js for example.
const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'past'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-d-bg dw-d-bg--corner-br" style="opacity: 0.06;"></div>
            <div class="${P}-inner" style="position: relative; z-index: 2;">
                <div class="${P}-header fade-in-section">
                    <span class="section-label">Past Events</span>
                    <h2>What We've Done</h2>
                </div>
                <div class="filter-bar fade-in-section">
                    <button class="filter-tab active" data-filter="all">All</button>
                    <button class="filter-tab" data-filter="seminar">Seminars</button>
                    <button class="filter-tab" data-filter="workshop">Workshops</button>
                    <button class="filter-tab" data-filter="factory-visit">Factory Visits</button>
                    <button class="filter-tab" data-filter="trade-show">Trade Shows</button>
                </div>
                <div class="${P}-grid" id="${P}-events-grid">
                    
                    <div class="${P}-card fade-in-section" data-type="seminar">
                        <span class="event-type-badge seminar">Seminar</span>
                        <h3>ERP for Thai Manufacturing: What to Look For in 2026</h3>
                        <span class="event-date">January 18, 2026</span>
                        <a href="#" class="event-link">View Recap <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></a>
                    </div>
                    
                    <div class="${P}-card fade-in-section" data-type="workshop">
                        <span class="event-type-badge workshop">Workshop</span>
                        <h3>Warehouse Efficiency: WMS Basics for Factory Operations</h3>
                        <span class="event-date">December 12, 2025</span>
                        <a href="#" class="event-link">View Recap <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></a>
                    </div>
                    
                    <div class="${P}-card fade-in-section" data-type="trade-show">
                        <span class="event-type-badge trade-show">Trade Show</span>
                        <h3>Manufacturing Expo Thailand 2025 Recap</h3>
                        <span class="event-date">November 15-17, 2025</span>
                        <a href="#" class="event-link">View Recap <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></a>
                    </div>
                </div>
            </div>`;

  return base.wrapInDiviSection('Past', html, 'Past: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === PAST (S5) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}
.event-type-badge {
            display: inline-flex;
            align-items: center;
            padding: 6px 14px;
            border-radius: 50px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            letter-spacing: 1px;
            text-transform: uppercase;
            margin-bottom: 16px;
            width: fit-content;
        }
.event-type-badge.seminar {
            background: rgba(0, 175, 240, 0.12);
            color: #0369a1;
        }
.event-type-badge.workshop {
            background: rgba(34, 197, 94, 0.12);
            color: #15803d;
        }
.event-type-badge.factory-visit {
            background: rgba(245, 158, 11, 0.12);
            color: #b45309;
        }
.event-type-badge.trade-show {
            background: rgba(139, 92, 246, 0.12);
            color: #7c3aed;
        }
.section-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 12px;
            font-weight: 500;
            color: #0369a1;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin-bottom: 16px;
            display: block;
        }
.upcoming-card-border.seminar { background: #00AFF0; }
.upcoming-card-border.workshop { background: #22C55E; }
.upcoming-card-border.trade-show { background: #8B5CF6; }
.upcoming-card-body .event-type-badge {
            margin-bottom: 16px;
        }
.event-link {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            color: #0369a1;
            font-weight: 600;
            font-size: 14px;
            text-decoration: none;
            transition: all 0.3s ease;
        }
.event-link:hover {
            gap: 10px;
        }
.past-section {
            padding: 100px 24px;
            background: #F5F7FA;
        }
.past-inner {
            max-width: 1200px;
            margin: 0 auto;
        }
.past-header {
            text-align: center;
            margin-bottom: 40px;
        }
.past-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 0;
        }
.filter-bar {
            display: flex;
            justify-content: center;
            margin-bottom: 48px;
            background: #fff;
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 6px;
            max-width: 700px;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 48px;
        }
.filter-tab {
            flex: 1;
            padding: 12px 16px;
            text-align: center;
            font-family: 'Noto Sans', sans-serif;
            font-size: 14px;
            font-weight: 600;
            color: #5b6b80;
            background: transparent;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: all 0.3s ease;
            white-space: nowrap;
        }
.filter-tab:hover {
            color: #000864;
            background: #f8fafc;
        }
.filter-tab.active {
            background: #00AFF0;
            color: #fff;
            box-shadow: 0 2px 8px rgba(0, 175, 240, 0.25);
        }
.past-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 24px;
        }
.past-card {
            background: #fff;
            border: 1px solid #e2e8f0;
            border-radius: 16px;
            padding: 28px;
            transition: all 0.3s ease;
        }
.past-card:hover {
            border-color: #00AFF0;
            box-shadow: 0 8px 32px rgba(0, 175, 240, 0.1);
        }
.past-card .event-type-badge {
            margin-bottom: 12px;
        }
.past-card h4 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 17px;
            font-weight: 600;
            color: #000864;
            margin-bottom: 8px;
            line-height: 1.4;
        }
.past-card .event-date {
            font-size: 13px;
            color: #5b6b80;
            margin-bottom: 16px;
            display: block;
        }
.past-card .event-link {
            font-size: 13px;
        }
.fade-in-section {
            opacity: 0;
            transform: translateY(30px);
            transition: opacity 0.4s ease, transform 0.4s ease;
        }
.fade-in-section.is-visible {
            opacity: 1;
            transform: translateY(0);
        }
@media (max-width: 1024px) {
.past-grid {
                grid-template-columns: repeat(2, 1fr);
            }
.filter-bar {
                flex-wrap: wrap;
            }
}
@media (max-width: 640px) {
.past-grid {
                grid-template-columns: 1fr;
            }
.filter-bar {
                flex-direction: column;
                gap: 4px;
            }
.filter-tab {
                padding: 10px 16px;
            }
.upcoming-header h2,
            .series-header h2,
            .past-header h2 {
                font-size: 28px;
            }
}

/* TODO: HOVER STATES using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link svg,.dw-nav-item:hover .dw-nav-link svg{transform:rotate(180deg)} */
/* .event-link:hover{gap:10px} */
/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link::after{transform:scaleX(1)} */
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-mega-menu.active{opacity:1;visibility:visible;transform:translateY(0)} */
/* .blog-hub-filter-tab.active{background:#006dac;color:#ffffff;box-shadow:0 2px 8px rgba(0, 175, 240, 0.3)} */
/* @media (max-width:1024px){.dw-nav-item.active .dw-nav-link svg{transform:rotate(180deg)}.dw-mega-menu.active{display:block}.dw-menu-toggle.active span:nth-child(1){transform:rotate(45deg) translate(5px, 5px)}.dw-menu-toggle.active span:nth-child(2){opacity:0}.dw-menu-toggle.active span:nth-child(3){transform:rotate(-45deg) translate(5px, -5px)}} */
/* .event-register-success.active{display:block} */
/* .event-type-badge{display:inline-flex;align-items:center;padding:6px 14px;border-radius:50px;font-family:'JetBrains Mono', monospace;font-size:11px;font-weight:500;letter-spacing:1px;text-transform:uppercase;margin-bottom:16px;width:fit-content} */
/* .event-type-badge.seminar{background:rgba(0, 175, 240, 0.12);color:var(--dw-blue-text)} */
/* .event-type-badge.workshop{background:rgba(34, 197, 94, 0.12);color:#15803d} */
/* .event-type-badge.factory-visit{background:rgba(245, 158, 11, 0.12);color:#b45309} */
/* .event-type-badge.trade-show{background:rgba(139, 92, 246, 0.12);color:#7c3aed} */
/* .upcoming-card-border.seminar{background:#00AFF0} */
/* .upcoming-card-border.workshop{background:#22C55E} */
/* .upcoming-card-border.trade-show{background:#8B5CF6} */
/* .upcoming-card-body .event-type-badge{margin-bottom:16px} */
/* .event-link{display:inline-flex;align-items:center;gap:6px;color:var(--dw-blue-text);font-family:'Noto Sans', sans-serif;font-weight:600;font-size:14px;text-decoration:none;transition:all 0.3s ease} */
/* .mockup-nav-item.active{color:var(--dw-blue)} */
/* .mockup-bar.active{opacity:1;background:#10b981} */
${superD.css('dw-d-bg', { variant: 'outline', position: 'corner-br' })}

${base.reducedMotion('*{animation:none !important;transition:none !important}')}

.et_pb_section .section-label {
            line-height: 19.2px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .filter-tab {
            -webkit-font-smoothing: auto !important;
        }

.et_pb_section .event-type-badge {
            line-height: 17.6px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .event-date {
            line-height: 20.8px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .event-link {
            line-height: 20.8px !important;
        
            -webkit-font-smoothing: auto !important;
}

/* Divi section-level overrides */
.et_pb_section:has(.past-inner) {
  background: #F5F7FA !important;
  padding: 100px 24px !important;
}

.et_pb_section:has(.past-inner) .et_pb_row {
  max-width: 100% !important;
  width: 100% !important;
  padding: 0 !important;
}

.et_pb_section:has(.past-inner) .et_pb_column {
  padding: 0 !important;
}

.et_pb_section .past-inner {
  width: 100% !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .past-inner h2 {
  padding: 0 !important;
  line-height: 64px !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .past-inner h3 {
  padding: 0 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .past-card h3 {
  font-size: 18.72px !important;
  font-weight: 700 !important;
  line-height: 29.952px !important;
}

.et_pb_section .past-inner p {
  padding-bottom: 0 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .filter-tab {
  -webkit-font-smoothing: auto !important;
}

`.trim();
}

module.exports = { blocks, css };
