/**
 * news-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: news.html line 1205
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 13 base, 0 hover, 0 pseudo, 0 hidden
 * Original classes: news-hero, dw-d-bg, dw-d-bg--corner-tl, news-hero-illustration, news-hero-inner (+6 more)
 */

// TEMPLATE HINT: matches "hero-gradient". See home-hero.js for example.
const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-d-bg dw-d-bg--corner-tl" style="opacity: 0.10;"></div>
            <div class="${P}-illustration">
                <svg aria-hidden="true" viewBox="0 0 560 480" fill="none" xmlns="http://www.w3.org/2000/svg">
                    
                    <rect x="320" y="60" width="200" height="180" rx="12" stroke="#00AFF0" stroke-width="1.2"/>
                    <line x1="320" y1="100" x2="520" y2="100" stroke="#00AFF0" stroke-width="0.8"/>
                    <line x1="370" y1="100" x2="370" y2="240" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    <line x1="420" y1="100" x2="420" y2="240" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    <line x1="470" y1="100" x2="470" y2="240" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    <line x1="320" y1="140" x2="520" y2="140" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    <line x1="320" y1="180" x2="520" y2="180" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    <line x1="320" y1="220" x2="520" y2="220" stroke="#00AFF0" stroke-width="0.5" stroke-dasharray="4 4"/>
                    
                    <line x1="380" y1="45" x2="380" y2="75" stroke="#00AFF0" stroke-width="1.5" stroke-linecap="round"/>
                    <line x1="460" y1="45" x2="460" y2="75" stroke="#00AFF0" stroke-width="1.5" stroke-linecap="round"/>
                    
                    <rect x="371" y="141" width="48" height="38" rx="4" fill="#00AFF0" fill-opacity="0.15"/>
                    
                    <circle cx="200" cy="160" r="6" stroke="#00AFF0" stroke-width="1.2"/>
                    <circle cx="280" cy="120" r="4" stroke="#00AFF0" stroke-width="1"/>
                    <circle cx="260" cy="220" r="5" stroke="#00AFF0" stroke-width="1"/>
                    <circle cx="160" cy="280" r="4" stroke="#00AFF0" stroke-width="1"/>
                    <circle cx="300" cy="300" r="6" stroke="#00AFF0" stroke-width="1.2"/>
                    <circle cx="400" cy="320" r="5" stroke="#00AFF0" stroke-width="1"/>
                    
                    <line x1="206" y1="158" x2="276" y2="122" stroke="#00AFF0" stroke-width="0.8" stroke-dasharray="6 4"/>
                    <line x1="198" y1="166" x2="262" y2="216" stroke="#00AFF0" stroke-width="0.8" stroke-dasharray="6 4"/>
                    <line x1="264" y1="224" x2="296" y2="296" stroke="#00AFF0" stroke-width="0.8" stroke-dasharray="6 4"/>
                    <line x1="306" y1="300" x2="396" y2="320" stroke="#00AFF0" stroke-width="0.8" stroke-dasharray="6 4"/>
                    <line x1="164" y1="278" x2="294" y2="302" stroke="#00AFF0" stroke-width="0.8" stroke-dasharray="6 4"/>
                    
                    <circle cx="140" cy="380" r="40" stroke="#00AFF0" stroke-width="1" stroke-dasharray="8 4"/>
                    <line x1="140" y1="380" x2="140" y2="352" stroke="#00AFF0" stroke-width="1.2" stroke-linecap="round"/>
                    <line x1="140" y1="380" x2="160" y2="390" stroke="#00AFF0" stroke-width="1.2" stroke-linecap="round"/>
                    
                    <line x1="140" y1="342" x2="140" y2="346" stroke="#00AFF0" stroke-width="0.8"/>
                    <line x1="178" y1="380" x2="174" y2="380" stroke="#00AFF0" stroke-width="0.8"/>
                    <line x1="140" y1="418" x2="140" y2="414" stroke="#00AFF0" stroke-width="0.8"/>
                    <line x1="102" y1="380" x2="106" y2="380" stroke="#00AFF0" stroke-width="0.8"/>
                    
                    <circle cx="450" cy="380" r="2" fill="#00AFF0" fill-opacity="0.3"/>
                    <circle cx="480" cy="400" r="1.5" fill="#00AFF0" fill-opacity="0.2"/>
                    <circle cx="350" cy="420" r="2" fill="#00AFF0" fill-opacity="0.25"/>
                    <circle cx="240" cy="350" r="1.5" fill="#00AFF0" fill-opacity="0.2"/>
                    <circle cx="100" cy="100" r="2" fill="#00AFF0" fill-opacity="0.2"/>
                    <circle cx="140" cy="140" r="1.5" fill="#00AFF0" fill-opacity="0.15"/>
                </svg>
            </div>
            <div class="${P}-inner">
                <div class="${P}-badge">
                    <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
                    News & Events
                </div>
                <h1>Where Manufacturing Intelligence <span>Meets Action</span></h1>
                <p class="${P}-subtitle">Industry workshops, compliance seminars, factory visits, and trade exhibitions designed for Thai manufacturers ready to transform their operations.</p>
                <div class="${P}-stats">
                    <div class="${P}-stat">
                        <div class="${P}-stat-value">4+</div>
                        <div class="${P}-stat-label">Events per Quarter</div>
                    </div>
                    <div class="${P}-stat">
                        <div class="${P}-stat-value">100+</div>
                        <div class="${P}-stat-label">Thai Factories Served</div>
                    </div>
                    <div class="${P}-stat">
                        <div class="${P}-stat-value">Free</div>
                        <div class="${P}-stat-label">Most Events</div>
                    </div>
                </div>
            </div>`;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}
/* .news-hero bg/pseudo handled by section-level :has() overrides below */
.hero-illustration {
            position: absolute;
            bottom: 0;
            right: 0;
            width: 600px;
            height: 100%;
            pointer-events: none;
            overflow: hidden;
        }
.hero-illustration svg {
            position: absolute;
            bottom: -20px;
            right: -40px;
            width: 560px;
            height: 480px;
            opacity: 0.12;
        }
.hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(0, 175, 240, 0.2);
            border: 1px solid rgba(0, 175, 240, 0.3);
            padding: 8px 20px;
            border-radius: 50px;
            font-family: 'JetBrains Mono', monospace;
            font-size: 13px;
            font-weight: 500;
            color: #7EC8F2;
            letter-spacing: 1.5px;
            text-transform: uppercase;
            margin-bottom: 24px;
        }
.hero-inner h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: clamp(32px, 5vw, 52px);
            font-weight: 700;
            color: #fff;
            line-height: 1.15;
            margin-bottom: 20px;
            max-width: 800px;
            margin-left: auto;
            margin-right: auto;
        }
.hero-inner h1 span {
            color: #00AFF0;
        }
.hero-subtitle {
            font-size: 18px;
            color: rgba(255,255,255,0.85);
            line-height: 1.7;
            max-width: 680px;
            margin: 0 auto 48px;
        }
.hero-stats {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 32px;
            max-width: 700px;
            margin: 0 auto;
            padding-top: 40px;
            border-top: 1px solid rgba(255,255,255,0.1);
        }
.hero-stat {
            text-align: center;
        }
.hero-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 42px;
            font-weight: 700;
            color: #00AFF0;
            line-height: 1;
            margin-bottom: 8px;
        }
.hero-stat-label {
            font-size: 14px;
            color: rgba(255,255,255,0.75);
            line-height: 1.4;
        }
@media (max-width: 1024px) {
.hero-illustration {
                width: 400px;
                opacity: 0.7;
            }
}
@media (max-width: 640px) {
/* responsive padding handled by section-level :has() */
.hero-illustration {
                display: none;
            }
.hero-inner h1 {
                font-size: 28px;
            }
.hero-stats {
                grid-template-columns: repeat(3, 1fr);
                gap: 16px;
            }
.hero-stat-value {
                font-size: 32px;
            }
}

/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
${superD.css('dw-d-bg', { variant: 'outline', position: 'corner-tl' })}



.et_pb_section .hero-badge {
            line-height: 20.8px !important;
        
            padding-top: 8px;

            padding-bottom: 8px;

            -webkit-font-smoothing: auto !important;
}

.et_pb_section .hero-stat-label {
            line-height: 19.6px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .hero-stat-value {
            line-height: 42px !important;
        
            color: rgb(0, 175, 240) !important;

            margin-bottom: 8px !important;

            -webkit-font-smoothing: auto !important;
}

/* Divi section-level overrides */
.et_pb_section:has(.hero-inner) {
  background: linear-gradient(165deg, #0f1419 0%, #1a2632 40%, #000864 100%) !important;
  padding: 140px 24px 100px !important;
  position: relative !important;
  overflow: hidden !important;
}

.et_pb_section:has(.hero-inner)::before {
  content: '' !important;
  position: absolute !important;
  inset: 0 !important;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E") !important;
  opacity: 0.03 !important;
  pointer-events: none !important;
  animation: grain 8s steps(10) infinite !important;
}

.et_pb_section:has(.hero-inner)::after {
  content: '' !important;
  position: absolute !important;
  inset: 0 !important;
  background: radial-gradient(ellipse at 30% 50%, rgba(0,175,240,0.08), transparent 70%) !important;
  pointer-events: none !important;
}

.et_pb_section:has(.hero-inner) .et_pb_row {
  max-width: 100% !important;
  width: 100% !important;
  padding: 0 !important;
}

.et_pb_section:has(.hero-inner) .et_pb_column {
  padding: 0 !important;
}

.et_pb_section .hero-inner {
  width: 100% !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .dw-d-bg {
  position: absolute !important;
  pointer-events: none !important;
  z-index: 0 !important;
}

.et_pb_section .hero-illustration {
  position: absolute !important;
  bottom: 0 !important;
  right: 0 !important;
  width: 600px !important;
  height: 100% !important;
  pointer-events: none !important;
  overflow: hidden !important;
  z-index: 0 !important;
}

.et_pb_section .hero-illustration svg {
  position: absolute !important;
  bottom: -20px !important;
  right: -40px !important;
  width: 560px !important;
  height: 480px !important;
  opacity: 0.12 !important;
}

.et_pb_section .hero-inner h1 {
  color: #fff !important;
  -webkit-font-smoothing: auto !important;
  padding: 0 !important;
  margin-bottom: 20px !important;
}

.et_pb_section .hero-inner h1 span {
  color: #00AFF0 !important;
}

.et_pb_section .hero-subtitle {
  color: rgba(255,255,255,0.85) !important;
  -webkit-font-smoothing: auto !important;
  padding-bottom: 0 !important;
}

.et_pb_section .hero-stat-value {
  color: #00AFF0 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .hero-stat-label {
  color: rgba(255,255,255,0.75) !important;
  -webkit-font-smoothing: auto !important;
}
`.trim();
}

module.exports = { blocks, css };
