/**
 * news-cta.js — Cta Section (S6)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: news.html line 1503
 *
// NOTE: Contains inline SVGs — may need Base64 JS injection if wp_kses strips elements.
 * styles.css: 15 base, 0 hover, 0 pseudo, 1 hidden
 * Original classes: news-cta, dw-d-bg, dw-d-bg--left, dw-wave-flow, news-cta-inner (+6 more)
 */

// TEMPLATE HINT: matches "cta-gradient". See home-cta.js for example.
const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'cta'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-d-bg dw-d-bg--left" style="opacity: 0.12;"></div>
            
            <div class="dw-wave-flow" style="height: 160px; opacity: 0.3; z-index: 1;"></div>
            <div class="news-cta-inner fade-in-section" style="position: relative; z-index: 3;">
                <h2>Don't Miss the Next Event</h2>
                <p>Join 500+ Thai manufacturing professionals who stay informed about industry trends, compliance updates, and technology opportunities.</p>
                <form class="${P}-form" onsubmit="event.preventDefault();">
                    <label for="subscribe-email" class="sr-only">Email address</label>
                    <input type="email" id="${P}-email" class="${P}-input" placeholder="Enter your email address" required>
                    <button type="submit" class="${P}-btn">Subscribe</button>
                </form>
                <a href="demo.html" class="cta-secondary-link">Or Let's Talk Directly <svg aria-hidden="true" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></a>
            </div>`;

  return base.wrapInDiviSection('Cta', html, 'Cta: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === CTA (S6) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}
/* .news-cta bg/pseudo handled by section-level :has() overrides below */
.news-cta-inner {
            width: 100%;
            max-width: 700px;
            margin: 0 auto;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.news-cta-inner h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #fff;
            margin-bottom: 16px;
        }
.news-cta-inner p {
            font-size: 18px;
            color: rgba(255,255,255,0.85);
            margin-bottom: 40px;
            line-height: 1.7;
        }
.cta-form {
            display: flex;
            gap: 12px;
            max-width: 520px;
            margin: 0 auto 24px;
        }
.cta-input {
            flex: 1;
            padding: 16px 20px;
            background: rgba(255,255,255,0.1);
            border: 1px solid rgba(255,255,255,0.2);
            border-radius: 12px;
            color: #fff;
            font-size: 16px;
            font-family: 'Noto Sans', sans-serif;
            outline: none;
            transition: all 0.3s ease;
        }
.cta-input::placeholder {
            color: rgba(255,255,255,0.75);
        }
.cta-input:focus {
            border-color: #00AFF0;
            background: rgba(255,255,255,0.15);
            box-shadow: 0 0 0 3px rgba(0, 175, 240, 0.2);
        }
.cta-btn {
            padding: 16px 32px;
            background: linear-gradient(135deg, #00AFF0, #003CC8);
            color: #fff;
            border: none;
            border-radius: 12px;
            font-family: 'Noto Sans', sans-serif;
            font-size: 15px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s ease;
            white-space: nowrap;
        }
.cta-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 24px rgba(0, 175, 240, 0.3);
        }
.cta-secondary-link {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            color: rgba(255,255,255,0.75);
            font-size: 14px;
            text-decoration: none;
            transition: all 0.3s ease;
        }
.cta-secondary-link:hover {
            color: #0369a1;
            gap: 10px;
        }
.fade-in-section {
            opacity: 0;
            transform: translateY(30px);
            transition: opacity 0.4s ease, transform 0.4s ease;
        }
.fade-in-section.is-visible {
            opacity: 1;
            transform: translateY(0);
        }
@media (max-width: 640px) {
.cta-form {
                flex-direction: column;
            }
.cta-btn {
                width: 100%;
            }
.news-cta-inner h2 {
                font-size: 28px;
            }
}

/* WARNING: HIDDEN in styles.css (display:none) — DO NOT include in builder HTML */
/* .dw-wave-flow,
 * .dw-wave-flow--top {
 *     display: none;
 * } */
/* REF: BASE RULES from styles.css (check against inline CSS above) */
/* .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border:0} */
/* .dw-d-bg{position:absolute;right:-10%;top:50%;transform:translateY(-50%);width:60%;min-height:60vh;background:url('assets/digiwin-d-outline.svg') no-repeat center right;background-size:contain;pointer-events:none;z-index:0;opacity:0.12} */
/* .dw-d-bg--gradient{background-image:url('assets/digiwin-d-gradient.svg');opacity:0.15} */
/* .dw-d-bg--particle{background-image:url('assets/digiwin-d-particle.svg');opacity:0.2} */
/* .dw-d-bg--left{right:auto;left:-15%;background-position:center left} */
/* .dw-d-bg--bottom{top:auto;bottom:-20%;transform:none;background-position:center bottom} */
/* .dw-d-bg--top{top:-20%;transform:none;background-position:center top} */
/* .dw-d-bg--center{right:auto;left:50%;transform:translate(-50%, -50%);width:80%;min-height:80vh;background-position:center center} */
/* .dw-d-bg--corner{width:30%;min-height:30vh} */
/* .dw-d-bg--corner-tl{right:auto;left:-5%;top:-5%;transform:none} */
/* .dw-d-bg--corner-br{top:auto;bottom:-5%;right:-5%;transform:none} */
/* .dw-d-bg--bold{opacity:0.22 !important} */
/* .dw-d-bg--medium{opacity:0.14 !important} */
/* .dw-d-bg--subtle{opacity:0.06 !important} */
/* .dw-wave-flow--top{bottom:auto;top:0;transform:scaleY(-1)} */
${superD.css('dw-d-bg', { variant: 'outline', position: 'left' })}

${base.reducedMotion('*{animation:none !important;transition:none !important}')}

.et_pb_section .cta-secondary-link {
            line-height: 22.4px !important;
        
            -webkit-font-smoothing: auto !important;
}

/* Divi section-level overrides */
.et_pb_section:has(.news-cta-inner) {
  background: linear-gradient(165deg, #0f1419 0%, #1a2632 40%, #000864 100%) !important;
  padding: 100px 24px !important;
  position: relative !important;
  overflow: hidden !important;
}

.et_pb_section:has(.news-cta-inner)::before {
  content: '' !important;
  position: absolute !important;
  inset: 0 !important;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E") !important;
  opacity: 0.03 !important;
  pointer-events: none !important;
}

.et_pb_section:has(.news-cta-inner) .et_pb_row {
  max-width: 100% !important;
  width: 100% !important;
  padding: 0 !important;
}

.et_pb_section:has(.news-cta-inner) .et_pb_column {
  padding: 0 !important;
}

/* Force fade-in-section visible (no JS scroll observer in WP) */
.et_pb_section .fade-in-section {
  opacity: 1 !important;
  transform: none !important;
}

.et_pb_section .news-cta-inner {
  width: 100% !important;
  max-width: 700px !important;
  margin: 0 auto !important;
  text-align: center !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .news-cta-inner h2 {
  font-family: 'Noto Sans', sans-serif !important;
  font-size: 40px !important;
  font-weight: 700 !important;
  color: #fff !important;
  margin-bottom: 16px !important;
  -webkit-font-smoothing: auto !important;
  padding: 0 !important;
  line-height: 1.6 !important;
}

.et_pb_section .news-cta-inner p {
  font-size: 18px !important;
  color: rgba(255,255,255,0.85) !important;
  margin-bottom: 40px !important;
  line-height: 1.7 !important;
  -webkit-font-smoothing: auto !important;
  padding-bottom: 0 !important;
}

.et_pb_section .cta-form {
  display: flex !important;
  gap: 12px !important;
  max-width: 520px !important;
  margin: 0 auto 24px !important;
}

.et_pb_section .cta-input {
  background: rgba(255,255,255,0.1) !important;
  border: 1px solid rgba(255,255,255,0.2) !important;
  border-radius: 12px !important;
  color: #fff !important;
  font-size: 16px !important;
  padding: 16px 20px !important;
  flex: 1 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .cta-input::placeholder {
  color: rgba(255,255,255,0.75) !important;
}

.et_pb_section .cta-btn {
  padding: 16px 32px !important;
  background: linear-gradient(135deg, #00AFF0, #003CC8) !important;
  color: #fff !important;
  border: none !important;
  border-radius: 12px !important;
  font-size: 15px !important;
  font-weight: 600 !important;
  white-space: nowrap !important;
  cursor: pointer !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .cta-secondary-link {
  display: inline-flex !important;
  align-items: center !important;
  gap: 6px !important;
  color: rgba(255,255,255,0.75) !important;
  font-size: 14px !important;
  text-decoration: none !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .dw-d-bg {
  position: absolute !important;
  pointer-events: none !important;
  z-index: 0 !important;
}
`.trim();
}

module.exports = { blocks, css };
