/**
 * news-series.js — Series Section (S4)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: news.html line 1424
 *
 * Original classes: series-section, series-inner, series-header, fade-in-section, section-label (+4 more)
 */

const base = require('../../lib/templates/_base');

const P = 'series'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="${P}-inner" style="position: relative; z-index: 2;">
                <div class="${P}-header fade-in-section">
                    <span class="section-label">Recurring Campaign</span>
                    <h2>Manufacturing Competitiveness Series</h2>
                    <p>A monthly deep-dive into the challenges Thai manufacturers face -- and the tools that solve them.</p>
                </div>
                <div class="${P}-timeline fade-in-section">
                    <div class="${P}-step">
                        <div class="${P}-step-number">1</div>
                        <span class="${P}-step-label">Month 1</span>
                        <h3>BOI Compliance</h3>
                        <p>Eliminate supplementary taxes through production-level reconciliation</p>
                    </div>
                    <div class="${P}-step">
                        <div class="${P}-step-number">2</div>
                        <span class="${P}-step-label">Month 2</span>
                        <h3>Production Transparency</h3>
                        <p>Replace paper reports with real-time shop floor visibility</p>
                    </div>
                    <div class="${P}-step">
                        <div class="${P}-step-number">3</div>
                        <span class="${P}-step-label">Month 3</span>
                        <h3>Cash Flow Management</h3>
                        <p>Connect production costs to financial planning in real-time</p>
                    </div>
                    <div class="${P}-step">
                        <div class="${P}-step-number">4</div>
                        <span class="${P}-step-label">Month 4</span>
                        <h3>ERP Migration Options</h3>
                        <p>What to do when your current ERP reaches end of life</p>
                    </div>
                </div>
            </div>`;

  return base.wrapInDiviSection('Series', html, 'Series: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === SERIES (S4) === */
/* Divi 5 section boilerplate (font-smoothing, p padding, heading resets) */
.${P}-section{position:relative;overflow:hidden;${base.fontSmoothingReset(P)}font-size:16px}
.${P}-section p{padding-bottom:0;line-height:1.6}
.${P}-section h2,.${P}-section h3,.${P}-section h4{margin:0;padding:0;line-height:1.6}
.section-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 12px;
            font-weight: 500;
            color: #0369a1;
            letter-spacing: 2px;
            text-transform: uppercase;
            margin-bottom: 16px;
            display: block;
        }
.series-section {
            padding: 100px 24px;
            background: #fff;
        }
.series-inner {
            max-width: 1200px;
            margin: 0 auto;
        }
.series-header {
            text-align: center;
            margin-bottom: 64px;
        }
.series-header h2 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 40px;
            font-weight: 700;
            color: #000864;
            margin-bottom: 16px;
        }
.series-header p {
            font-size: 18px;
            color: #5b6b80;
            max-width: 650px;
            margin: 0 auto;
            line-height: 1.7;
        }
.series-timeline {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 0;
            position: relative;
        }
.series-timeline::before {
            content: '';
            position: absolute;
            top: 32px;
            left: 12.5%;
            right: 12.5%;
            height: 3px;
            background: linear-gradient(90deg, #00AFF0, #22C55E, #F59E0B, #8B5CF6);
            border-radius: 2px;
            z-index: 0;
        }
.series-step {
            text-align: center;
            position: relative;
            z-index: 1;
            padding: 0 16px;
        }
.series-step-number {
            width: 64px;
            height: 64px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 20px;
            font-family: 'Noto Sans', sans-serif;
            font-size: 22px;
            font-weight: 700;
            color: #fff;
            position: relative;
        }
.series-step:nth-child(1) .series-step-number { background: linear-gradient(135deg, #00AFF0, #003CC8); }
.series-step:nth-child(2) .series-step-number { background: linear-gradient(135deg, #22C55E, #16a34a); }
.series-step:nth-child(3) .series-step-number { background: linear-gradient(135deg, #F59E0B, #d97706); }
.series-step:nth-child(4) .series-step-number { background: linear-gradient(135deg, #8B5CF6, #7c3aed); }
.series-step-number::after {
            content: '';
            position: absolute;
            inset: -4px;
            border-radius: 50%;
            border: 2px solid rgba(255,255,255,0.3);
        }
.series-step:nth-child(1) .series-step-number::after { border-color: rgba(0, 175, 240, 0.3); }
.series-step:nth-child(2) .series-step-number::after { border-color: rgba(34, 197, 94, 0.3); }
.series-step:nth-child(3) .series-step-number::after { border-color: rgba(245, 158, 11, 0.3); }
.series-step:nth-child(4) .series-step-number::after { border-color: rgba(139, 92, 246, 0.3); }
.series-step-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 11px;
            font-weight: 500;
            color: #5b6b80;
            letter-spacing: 1px;
            text-transform: uppercase;
            margin-bottom: 8px;
            display: block;
        }
.series-step h3 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 18px;
            font-weight: 600;
            color: #000864;
            margin-bottom: 12px;
            line-height: 1.3;
        }
.series-step p {
            font-size: 14px;
            color: #5b6b80;
            line-height: 1.6;
        }
.fade-in-section {
            opacity: 0;
            transform: translateY(30px);
            transition: opacity 0.4s ease, transform 0.4s ease;
        }
.fade-in-section.is-visible {
            opacity: 1;
            transform: translateY(0);
        }
@media (max-width: 1024px) {
.series-timeline {
                grid-template-columns: repeat(2, 1fr);
                gap: 40px;
            }
.series-timeline::before {
                display: none;
            }
}
@media (max-width: 640px) {
.series-timeline {
                grid-template-columns: 1fr;
                gap: 32px;
            }
.upcoming-header h2,
            .series-header h2,
            .past-header h2 {
                font-size: 28px;
            }
}



${base.reducedMotion('*{animation:none !important;transition:none !important}')}

.et_pb_section .section-label {
            line-height: 19.2px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-step-label {
            line-height: 17.6px !important;
        
            -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-step-number {
            line-height: 35.2px !important;
        
            -webkit-font-smoothing: auto !important;
}

/* Divi section-level overrides */
.et_pb_section:has(.series-inner) {
  background: #fff !important;
  padding: 100px 24px !important;
}

.et_pb_section:has(.series-inner) .et_pb_row {
  max-width: 100% !important;
  width: 100% !important;
  padding: 0 !important;
}

.et_pb_section:has(.series-inner) .et_pb_column {
  padding: 0 !important;
}

.et_pb_section .series-inner {
  width: 100% !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-inner h2 {
  font-family: 'Noto Sans', sans-serif !important;
  font-size: 40px !important;
  font-weight: 700 !important;
  color: #000864 !important;
  padding: 0 !important;
  margin-bottom: 16px !important;
  line-height: 1.6 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-inner h3 {
  padding: 0 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-step-number {
  margin: 0 auto 20px !important;
}

.et_pb_section .series-step h3 {
  font-size: 18px !important;
  font-weight: 600 !important;
  color: #000864 !important;
  margin-bottom: 12px !important;
  line-height: 1.3 !important;
  -webkit-font-smoothing: auto !important;
}

.et_pb_section .series-timeline {
  display: grid !important;
  grid-template-columns: repeat(4, 1fr) !important;
  gap: 0 !important;
  position: relative !important;
}

.et_pb_section .series-header {
  text-align: center !important;
  margin-bottom: 64px !important;
}

.et_pb_section .series-header p {
  font-size: 18px !important;
  color: #5b6b80 !important;
  max-width: 650px !important;
  margin: 0 auto !important;
  line-height: 1.7 !important;
}

.et_pb_section .series-step p {
  font-size: 14px !important;
  color: #5b6b80 !important;
  line-height: 1.6 !important;
}

.et_pb_section .series-inner p {
  padding-bottom: 0 !important;
  -webkit-font-smoothing: auto !important;
}

/* Force fade-in-section visible (no JS scroll observer in WP) */
.et_pb_section .fade-in-section {
  opacity: 1 !important;
  transform: none !important;
}
`.trim();
}

module.exports = { blocks, css };
