/**
 * wms-section.js — Section Section (S2)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: wms.html line 1338
 *
 * styles.css: 17 base, 0 hover, 1 pseudo, 0 hidden
 * Original classes: dw-section
 */

const base = require('../../lib/templates/_base');

const P = 'sec'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="dw-section" style="padding: 40px 0 0; text-align: center;">
    <div style="max-width: 800px; margin: 0 auto; padding: 0 24px;">
        <h2 style="font-family: 'Noto Sans', sans-serif; font-size: 22px; font-weight: 700; color: #000864; margin: 0 0 12px 0;">What is WMS (Warehouse Management System)?</h2>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333; margin: 0 0 24px 0;">
          A Warehouse Management System (WMS) is software that manages warehouse operations including receiving, storage, picking, packing, and shipping. With barcode and RFID tracking, a WMS provides real-time inventory accuracy — so you always know exactly what you have and where it is.
        </p>
        <p style="font-family: 'Noto Sans', sans-serif; font-size: 17px; line-height: 1.7; color: #333;">
          <strong>DigiWin WMS</strong>, powered by the <strong>sFLS</strong> platform, brings smart inventory management to manufacturing warehouses in Thailand. It replaces manual stock checks and paper-based tracking with barcode/RFID scanning, automated FIFO/FEFO enforcement, location intelligence, and wave picking optimization — covering inbound, production, and outbound warehouse operations end to end.
        </p>
      </div>    </div>`;

  return base.wrapInDiviSection('Section', html, 'Section: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === SECTION (S2) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .dw-section{...;${base.fontSmoothingReset(P)}font-size:16px} */


/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-section--blue::before{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:radial-gradient(ellipse at 20% 30%, rgba(255,255,255,0.15) 0%, transparent 50%);pointer-events:none} */
${base.reducedMotion('')}
`.trim();
}

module.exports = { blocks, css };
