/**
 * wms-hero.js — Hero Section (S1)
 *
 * AUTO-GENERATED by scaffold-builder.js — review and customize before pushing.
 * Source: wms.html line 1271
 *
 * styles.css: 26 base, 3 hover, 1 pseudo, 0 hidden
 * Original classes: wms-hero, dw-d-bg, dw-d-bg--top, dw-d-parallax, wms-hero-inner (+23 more)
 */

const base = require('../../lib/templates/_base');
const superD = require('../../lib/super-d');

const P = 'hero'; // CSS prefix — customize if needed

// ════════════════════════════════════════════════════════════════
// BLOCKS
// ════════════════════════════════════════════════════════════════
function blocks() {
  const html = `
    <div class="wms-hero">
    <div class="dw-d-bg dw-d-bg--top dw-d-parallax" style="opacity: 0.12;"></div>
            <div class="wms-hero-inner">
                <div class="wms-hero-grid">
                    <div class="wms-hero-content">
                        <div class="wms-hero-badge">Warehouse Management System</div>
                        <h1>Every Item. Every Location. Every Time.</h1>
                        <p class="wms-hero-subtitle">Smart warehouse management that eliminates searching, reduces errors, and keeps inventory accurate—without endless manual counts.</p>
                        <div class="wms-hero-ctas">
                            <a href="../demo.html" class="btn-white">Let's Talk</a>
                            <a href="#capabilities" class="btn-outline-white">Explore sFLS</a>
                        </div>
                        <div class="wms-hero-stats">
                            <div class="wms-hero-stat">
                                <div class="wms-hero-stat-number dw-years">44</div>
                                <div class="wms-hero-stat-label">Years in Mfg</div>
                            </div>
                            <div class="wms-hero-stat">
                                <div class="wms-hero-stat-number">50K+</div>
                                <div class="wms-hero-stat-label">Factories</div>
                            </div>
                            <div class="wms-hero-stat">
                                <div class="wms-hero-stat-number">100+</div>
                                <div class="wms-hero-stat-label">Thai Sites</div>
                            </div>
                        </div>
                    </div>
                    <div class="wms-hero-visual">
                        <div class="wms-mockup">
                            <div class="wms-mockup-grid">
                                <div class="wms-mockup-cell occupied">A1</div>
                                <div class="wms-mockup-cell occupied">A2</div>
                                <div class="wms-mockup-cell">A3</div>
                                <div class="wms-mockup-cell occupied">A4</div>
                                <div class="wms-mockup-cell active">A5</div>
                                <div class="wms-mockup-cell occupied">B1</div>
                                <div class="wms-mockup-cell">B2</div>
                                <div class="wms-mockup-cell occupied">B3</div>
                                <div class="wms-mockup-cell occupied">B4</div>
                                <div class="wms-mockup-cell">B5</div>
                                <div class="wms-mockup-cell">C1</div>
                                <div class="wms-mockup-cell occupied">C2</div>
                                <div class="wms-mockup-cell occupied">C3</div>
                                <div class="wms-mockup-cell">C4</div>
                                <div class="wms-mockup-cell occupied">C5</div>
                            </div>
                            <div class="wms-mockup-stats">
                                <div class="wms-mockup-stat">
                                    <div class="wms-mockup-stat-value green">99.2%</div>
                                    <div class="wms-mockup-stat-label">Accuracy</div>
                                </div>
                                <div class="wms-mockup-stat">
                                    <div class="wms-mockup-stat-value">847</div>
                                    <div class="wms-mockup-stat-label">Locations</div>
                                </div>
                                <div class="wms-mockup-stat">
                                    <div class="wms-mockup-stat-value">73%</div>
                                    <div class="wms-mockup-stat-label">Utilized</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    `;

  return base.wrapInDiviSection('Hero', html, 'Hero: Content');
}

// ════════════════════════════════════════════════════════════════
// CSS
// ════════════════════════════════════════════════════════════════
function css() {
  return `
/* === HERO (S1) === */
/* TODO: Review and remap class selectors to use ${P} prefix */
/* TODO: Add section container: .${P}-section{...;${base.fontSmoothingReset(P)}font-size:16px} */
.wms-hero {
            background: linear-gradient(135deg, #1a2d3d 0%, #000864 50%, #001080 100%);
            padding: 140px 0 100px;
            position: relative;
            overflow: hidden;
        }
.wms-hero::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: url('data:image/svg+xml,<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="rgba(255,255,255,0.03)" stroke-width="0.5"/></pattern></defs><rect width="100" height="100" fill="url(%23grid)"/></svg>');
            opacity: 0.5;
        }
.wms-hero-inner {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 24px;
            text-align: center;
            position: relative;
            z-index: 1;
        }
.wms-hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(0, 175, 240, 0.15);
            border: 1px solid rgba(0, 175, 240, 0.3);
            padding: 8px 20px;
            border-radius: 50px;
            color: #7fc4fd;
            font-size: 11px;
            font-weight: 500;
            margin-bottom: 24px;
            font-family: 'JetBrains Mono', monospace;
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }
.wms-hero-stats {
            display: flex;
            justify-content: center;
            gap: 48px;
            margin-top: 40px;
            padding-top: 32px;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
        }
.wms-hero-stat-number {
            font-family: 'Noto Sans', sans-serif;
            font-size: 32px;
            font-weight: 800;
            color: #00AFF0;
        }
.wms-hero-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 10px;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            letter-spacing: 0.1em;
            margin-top: 4px;
        }
.wms-hero-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 60px;
            align-items: center;
            text-align: left;
        }
.wms-hero-content { max-width: 560px; }
.wms-mockup {
            background: rgba(255, 255, 255, 0.03);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 16px;
            padding: 20px;
            box-shadow: 0 40px 80px rgba(0, 0, 0, 0.3);
        }
.wms-mockup-grid {
            display: grid;
            grid-template-columns: repeat(5, 1fr);
            gap: 6px;
            margin-bottom: 16px;
        }
.wms-mockup-cell {
            aspect-ratio: 1;
            background: rgba(0, 175, 240, 0.08);
            border: 1px solid rgba(0, 175, 240, 0.15);
            border-radius: 4px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-family: 'JetBrains Mono', monospace;
            font-size: 8px;
            color: rgba(255, 255, 255, 0.75);
        }
.wms-mockup-cell.occupied {
            background: rgba(0, 175, 240, 0.25);
            border-color: rgba(0, 175, 240, 0.4);
            color: #00AFF0;
        }
.wms-mockup-cell.active {
            background: rgba(16, 185, 129, 0.3);
            border-color: #10b981;
            color: #047857;
        }
.wms-mockup-stats {
            display: flex;
            gap: 10px;
        }
.wms-mockup-stat {
            flex: 1;
            background: rgba(255, 255, 255, 0.05);
            border-radius: 8px;
            padding: 10px;
            text-align: center;
        }
.wms-mockup-stat-value {
            font-family: 'Noto Sans', sans-serif;
            font-size: 16px;
            font-weight: 700;
            color: #00AFF0;
        }
.wms-mockup-stat-value.green { color: #10b981; }
.wms-mockup-stat-label {
            font-family: 'JetBrains Mono', monospace;
            font-size: 8px;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            margin-top: 2px;
        }
.wms-hero h1 {
            font-family: 'Noto Sans', sans-serif;
            font-size: 48px;
            font-weight: 700;
            color: #ffffff;
            margin-bottom: 20px;
            line-height: 1.15;
        }
.wms-hero-subtitle {
            font-family: 'Noto Sans', sans-serif;
            font-size: 20px;
            color: rgba(255, 255, 255, 0.85);
            max-width: 700px;
            margin: 0 auto 32px;
            line-height: 1.6;
        }
.wms-hero-ctas {
            display: flex;
            gap: 16px;
            justify-content: center;
            flex-wrap: wrap;
        }
.integration-node.active {
            border-color: #00AFF0;
            background: linear-gradient(135deg, #f0f7ff 0%, #ffffff 100%);
            box-shadow: 0 8px 24px rgba(0, 175, 240, 0.15);
        }
@media (max-width: 1024px) {
            .wms-hero-grid { grid-template-columns: 1fr; text-align: center; }
            .wms-hero-content { max-width: 100%; }
            .wms-mockup { display: none; }
            .wms-hero-stats { justify-content: center; }
        }
@media (max-width: 640px) {
            .wms-hero {
                padding: 120px 0 60px;
            }
            .wms-hero h1 {
                font-size: 32px;
            }
            .problems-grid {
                grid-template-columns: 1fr;
                max-width: 400px;
                margin: 0 auto;
            }
            .mobile-modules-grid {
                grid-template-columns: 1fr;
                max-width: 360px;
                margin: 0 auto;
            }
            .step-reduction-columns {
                grid-template-columns: 1fr;
            }
            .step-number {
                font-size: 36px;
            }
        }
@media (prefers-reduced-motion: reduce) {
            .capability-box,
            .integration-node,
            .integration-link,
            .problem-card,
            .mobile-module,
            .dw-d-bg,
            .dw-d-parallax,
            .dw-wave-flow,
            .dw-d-glow {
                animation: none !important;
                transition: none !important;
            }
        }

/* TODO: HOVER STATES using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link svg,.dw-nav-item:hover .dw-nav-link svg{transform:rotate(180deg)} */
/* Buttons */
.btn-white{background:#ffffff;color:#003CC8;padding:20px 40px;border-radius:14px;font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.4s cubic-bezier(0.4, 0, 0.2, 1);box-shadow:0 4px 20px rgba(0, 0, 0, 0.15);display:inline-flex;align-items:center;gap:10px}
.btn-white:hover{transform:translateY(-4px);box-shadow:0 16px 48px rgba(0, 0, 0, 0.2)}
.btn-outline-white{background:transparent;color:#ffffff;padding:20px 40px;border-radius:14px;border:2px solid rgba(255, 255, 255, 0.5);font-family:'Noto Sans', sans-serif;font-size:16px;font-weight:600;text-decoration:none;transition:all 0.3s ease}
.btn-outline-white:hover{background:rgba(255, 255, 255, 0.15);border-color:#ffffff}
/* TODO: PSEUDO-ELEMENTS using global classes (port manually) */
/* .dw-nav-item.active .dw-nav-link::after{transform:scaleX(1)} */
\
/* Defensive SVG sizing */
svg:not([width]):not([class]){max-width:48px;max-height:48px}
${base.reducedMotion('')}

/* Super D decoration */
${superD.css('dw-d-bg', { variant: 'outline', position: 'right', modifiers: ['glow'] })}
`.trim();
}

module.exports = { blocks, css };
